import type { CapacityReservation, CapacityGrantV2 } from '@treeseed/sdk/agent-capacity';
import type { CapacityExecutionProvider, CapacityExecutionProviderNativeLimit, CapacityExecutionProviderObservation, CapacityProviderMembershipView } from '@treeseed/sdk/capacity-provider/contracts';

export type ProjectEnvironmentName = 'local' | 'staging' | 'prod';
export interface NativeCapacityAvailability { executionProviderId: string; capacityProviderId: string | null; executionProviderKind: string; nativeUnit: string; scope: string | null; configuredNativeLimit: number | null; observedNativeRemaining: number | null; nativeRemainingSource: 'observation' | 'configured_limit' | 'unknown'; activeReservedNativeAmount: number; activeConsumedNativeAmount: number; reserveBufferPercent: number; reserveBufferNativeAmount: number; availableNativeAmount: number; confidence: 'low' | 'medium' | 'high' | string; resetAt?: string | null; accountingWindowStartAt?: string | null; accountingWindowEndAt?: string | null; accountingWindowSource?: 'observation' | 'configured_reset' | 'unknown'; reasons: string[]; metadata?: Record<string, unknown> }
export interface NativeCapacitySummary { entries: NativeCapacityAvailability[]; availableNativeByUnit?: Record<string, number>; providers?: Array<{ capacityProviderId: string; entries?: NativeCapacityAvailability[]; availableNativeByUnit?: Record<string, number>; [key: string]: unknown }>; [key: string]: unknown }
export interface NativeReservationDebitAggregate { activeReservedNativeAmount: number; activeConsumedNativeAmount: number }
export interface NativeCapacityInput { executionProvider: CapacityExecutionProvider; nativeLimit?: CapacityExecutionProviderNativeLimit | null; latestObservation?: CapacityExecutionProviderObservation | null; activeReservations?: CapacityReservation[]; reservationDebits?: NativeReservationDebitAggregate | null; scope?: string | null; nativeUnit?: string | null; now?: Date | string | null }
export interface ApprovalRequest { id: string; teamId: string; projectId: string; workDayId: string | null; taskId: string | null; kind: string; state: string; severity: 'low' | 'medium' | 'high'; requestedByType: 'agent' | 'scheduler' | 'worker' | 'service' | 'user'; requestedById: string | null; title: string; summary: string; options: Record<string, unknown>[]; recommendation: Record<string, unknown>; policySnapshot: Record<string, unknown>; expiresAt: string | null; decidedByType: string | null; decidedById: string | null; decidedAt: string | null; decision: Record<string, unknown> | null; metadata: Record<string, unknown>; createdAt: string; updatedAt: string }
export interface ProjectCapacityDiagnostics { projectId: string; teamId: string; environment: ProjectEnvironmentName; providers: CapacityProviderMembershipView[]; executionProviders: CapacityExecutionProvider[]; grants: CapacityGrantV2[]; activeReservations: CapacityReservation[]; nativeCapacity?: NativeCapacitySummary | null; remaining: { dailyAgentSeconds: number | null; monthlyAgentSeconds: number | null } }
