import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import type { PoolClient } from 'pg';
import { expect, it } from 'vitest';
import { z } from 'zod';
import { PROVIDER_MEMBERSHIP_SCOPES } from '@treeseed/sdk/capacity-provider/contracts';
import { CONTROL_PLANE_OPERATIONS } from '@treeseed/sdk/operator-contracts';
import { canonicalJson, sha256 } from '../../../../../../../../src/api/capacity/security.ts';
import { encodeConfirmation } from '../../../../../../../../src/api/control-plane/confirmation/confirmation-service.ts';
import { dependencyOperator } from '../enrollment/dependency-operator-fixture.ts';
import { tokenProofInputs } from '../tokens/dependency-token-fixture.ts';
import { eventObserved } from '../../../../../realtime/architecture/session-postgres-fixture.ts';

// Full current app + one original disposable PG database/two owning pools.
// Operator JWT/local RBAC and Node signatures are inputs, NOT external issuer
// enrollment, browser login, managed keys, productive dispatch or teardown.
type Owner = Awaited<ReturnType<typeof dependencyOperator>>;
type Registration = Awaited<ReturnType<Owner['register']>>;
type State = Awaited<ReturnType<Owner['state']>>;
const record = z.record(z.string(), z.unknown());
function restPath(rest: { path: string } | undefined) { assert.ok(rest, 'Original public REST binding required'); return rest.path; }
it('native public registration status refuses an absent committed key without false audit and admits only a fresh original persistence retry', async () => {
	const f = await dependencyOperator();
	try {
		const credential = await f.token(), rest = CONTROL_PLANE_OPERATIONS.providers.registrationCode.status.descriptor.rest; assert.ok(rest);
		const path = rest.path.replace('{teamId}', 'team');
		const get = () => f.app.request(new Request(`https://localhost${path}`, { headers: { authorization: `Bearer ${credential}` } }));
		const baseline = await f.state(); expect(await f.state(f.right)).toEqual(baseline);
		await f.left.pool.query("CREATE FUNCTION registration_key_absence() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END $$");
		await f.left.pool.query("CREATE TRIGGER registration_key_absence BEFORE INSERT ON team_capacity_registration_keys FOR EACH ROW WHEN (NEW.team_id='team') EXECUTE FUNCTION registration_key_absence()");
		await denied(await get(), 404, 'registration_key_missing');
		expect(await f.state()).toEqual(baseline); expect(await f.state(f.right)).toEqual(baseline);
		await f.left.pool.query('DROP TRIGGER registration_key_absence ON team_capacity_registration_keys');
		await f.left.pool.query('DROP FUNCTION registration_key_absence()');
		expect((await f.right.pool.query("SELECT tgname FROM pg_trigger WHERE tgname='registration_key_absence'")).rows).toEqual([]);
		expect((await f.right.pool.query("SELECT proname FROM pg_proc WHERE proname='registration_key_absence'")).rows).toEqual([]);
		const response = await get(); expect(response.status).toBe(200);
		const result = CONTROL_PLANE_OPERATIONS.providers.registrationCode.status.schema.output.parse(await response.json());
		expect(z.object({ teamId: z.literal('team'), generation: z.literal(1) }).parse(result.data)).toEqual({ teamId: 'team', generation: 1 });
		const committed = await f.state(); unchangedExcept(baseline, committed, ['team_capacity_registration_keys', 'capacity_audit_events']);
		expect(additions(baseline, committed, 'team_capacity_registration_keys', 1)[0]).toMatchObject({ team_id: 'team', generation: 1, status: 'active' });
		expect(additions(baseline, committed, 'capacity_audit_events', 1)[0]).toMatchObject({ action: 'registration-key.created', team_id: 'team' });
		const replay = await get(); expect(replay.status).toBe(200); expect(await replay.json()).toEqual(result);
		expect(await f.state()).toEqual(committed); expect(await f.state(f.right)).toEqual(committed);
	} finally { await f.close(); }
});
function registeredProviderId(registration: Registration) {
	const fingerprint = z.string().regex(/^sha256:[A-Za-z0-9_-]{43}$/u).parse(registration.inputs.payload.providerFingerprint);
	const expected = `provider_${fingerprint.slice('sha256:'.length, 'sha256:'.length + 32)}`;
	expect(registration.request.providerId).toBe(expected); return expected;
}
function originalAuditId(action: string, resourceId: string, providerId: string, metadata: Record<string, unknown>) {
	return sha256(`${action}:${action === 'provider-identity.rotated' ? `${providerId}:team:${metadata.identityVersion}` : resourceId}`);
}
const rows = (state: State, table: string) => { expect(state).toHaveProperty(table); return state[table]!.map(value => record.parse(value)); };
function unchangedExcept(before: State, after: State, tables: string[]) {
	expect(Object.keys(after)).toEqual(Object.keys(before)); for (const table of Object.keys(before)) if (!tables.includes(table)) expect(after[table], table).toEqual(before[table]);
}
function additions(before: State, after: State, table: string, count: number) {
	const old = rows(before, table), current = rows(after, table); expect(current).toHaveLength(old.length + count);
	for (const value of old) expect(current).toContainEqual(value);
	return current.filter(value => !old.some(previous => JSON.stringify(previous) === JSON.stringify(value)));
}
function changedRow(before: State, after: State, table: string, id: string, changes: Record<string, unknown>, columns: string[]) {
	const old = rows(before, table), current = rows(after, table); expect(current).toHaveLength(old.length);
	const previous = old.find(row => row.id === id), changed = current.find(row => row.id === id); expect(previous).toBeDefined(); expect(changed).toBeDefined(); expect(changed).toMatchObject(changes);
	for (const value of old) if (value.id !== id) expect(current).toContainEqual(value);
	for (const [column, value] of Object.entries(previous!)) if (!columns.includes(column)) expect(changed![column], column).toEqual(value);
}
async function output(response: Response, operation: typeof CONTROL_PLANE_OPERATIONS.providers.exchangeCredential | typeof CONTROL_PLANE_OPERATIONS.providers.issueAccessToken) {
	expect(response.status).toBe(200); const envelope = z.object({ data: z.unknown() }).parse(await response.json()); return operation.schema.output.parse(envelope.data);
}
async function denied(response: Response, status: number, code: string) { expect(response.status).toBe(status); expect(await response.json()).toMatchObject({ status, code }); }
async function approved(f: Owner) {
	const registration = await f.register(), body = { teamAlias: 'genuinely-enrolled-provider' }, key = 'bootstrap-approved';
	const confirmation = await f.challenge(registration.approvalPath, registration.credential, body, key);
	const response = await f.post(registration.approvalPath, registration.credential, body, key, encodeConfirmation(confirmation)); expect(response.status).toBe(200);
	const result = z.object({ data: z.object({ id: z.string(), providerId: z.string(), membershipId: z.string(), status: z.literal('approved') }) }).parse(await response.json()).data;
	expect(result).toMatchObject({ id: registration.request.id, providerId: registration.request.providerId }); return { registration, membershipId: result.membershipId };
}
function stage(f: Owner, registration: Registration, path: string, body: Record<string, unknown>, wire: Record<string, unknown>, authorization?: string) {
	// Every stage retains the SAME registration helper's original three-second
	// expiry, including all retries. Elapsed setup/approval/readback MUST FAIL;
	// no Assignment, Lease, availability or productive window is created.
	const now = new Date(), payload = { ...registration.inputs.payload, path, bodySha256: sha256(canonicalJson(body)), issuedAt: now.toISOString(), jti: randomUUID() };
	const original = structuredClone({ payload, body, wire }); const key = z.string().parse(body.idempotencyKey);
	const post = (fresh = false) => {
		assert.ok(Date.now() < Date.parse(payload.expiresAt), 'Original stage proof expired; no retry extension is allowed');
		const claims = fresh ? { ...payload, jti: randomUUID() } : payload;
		return f.app.request(new Request(`http://localhost${path}`, { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': key, ...(authorization ? { authorization } : {}) }, body: JSON.stringify({ ...wire, proof: registration.inputs.proof(claims) }) }));
	};
	return { payload, post, unchanged() { expect({ payload, body, wire }).toEqual(original); expect(Date.now() < Date.parse(payload.expiresAt)).toBe(true); } };
}
const exchangeStage = (f: Owner, registration: Registration) => stage(f, registration, restPath(CONTROL_PLANE_OPERATIONS.providers.exchangeCredential.descriptor.rest).replace('{requestId}', registration.request.id), { requestId: registration.request.id, idempotencyKey: 'bootstrap-exchange' }, {});

it('genuine enrolled PostgreSQL first access token audit failure retains the exact committed token and fresh nonce recovery restores one original issuance audit without reissuing or erasing failed history', async () => {
	const f = await dependencyOperator();
	try {
		const { registration, membershipId } = await approved(f), providerId = registeredProviderId(registration), memberId = z.string().uuid().parse(membershipId), deadline = registration.inputs.payload.expiresAt, registrationBefore = structuredClone({ payload: registration.inputs.payload, body: registration.inputs.body, publicJwk: registration.inputs.publicJwk });
		const unelapsed = () => { expect(Date.now() < Date.parse(deadline)).toBe(true); expect({ payload: registration.inputs.payload, body: registration.inputs.body, publicJwk: registration.inputs.publicJwk }).toEqual(registrationBefore); };
		const read = async () => { unelapsed(); const value = await f.state(); expect(await f.state(f.right)).toEqual(value); unelapsed(); return value; };
		const clock = (value: unknown, start: string, end: string) => { const time = z.string().parse(value); expect(time >= start && time <= end && end < deadline).toBe(true); return time; };
		const audit = (row: Record<string, unknown>, action: string, resourceType: string, resourceId: string, key: string, time: string, metadata: Record<string, unknown>, requestId: string | null = null) => expect(row).toEqual({ id: originalAuditId(action, resourceId, providerId, metadata), team_id: 'team', capacity_provider_id: providerId, membership_id: membershipId, actor_type: 'provider-identity', actor_id: registration.inputs.payload.providerFingerprint, action, resource_type: resourceType, resource_id: resourceId, request_id: requestId, idempotency_key: key, before_fingerprint: null, after_fingerprint: null, metadata_json: JSON.stringify(metadata), created_at: time });
		const before = await read(), authority = rows(before, 'capacity_provider_credential_issuance_authorizations').find(row => row.membership_id === membershipId)!, exchange = exchangeStage(f, registration), exchangeStart = new Date().toISOString(), credential = record.parse(await output(await exchange.post(), CONTROL_PLANE_OPERATIONS.providers.exchangeCredential)), exchangeEnd = new Date().toISOString(), exchanged = await read();
		const credentialId = z.string().uuid().parse(credential.id), credentialValue = z.string().min(1).parse(credential.credential), credentialRow = additions(before, exchanged, 'capacity_provider_team_credentials', 1)[0]!, credentialTime = clock(credentialRow.created_at, exchangeStart, exchangeEnd);
		expect(authority).toMatchObject({ generation: 1, status: 'pending', issued_credential_id: null }); expect({ ...credential, credential: undefined }).toMatchObject({ membershipId, teamId: 'team', providerId, issuanceGeneration: 1, status: 'active', scopes: [...PROVIDER_MEMBERSHIP_SCOPES] });
		unchangedExcept(before, exchanged, ['capacity_provider_credential_issuance_authorizations', 'capacity_provider_team_credentials', 'capacity_provider_proof_nonces', 'capacity_audit_events']); changedRow(before, exchanged, 'capacity_provider_credential_issuance_authorizations', String(authority.id), {}, ['status', 'issued_credential_id', 'updated_at']); expect(rows(exchanged, 'capacity_provider_credential_issuance_authorizations').find(row => row.id === authority.id)).toEqual({ ...authority, status: 'issued', issued_credential_id: credentialId, updated_at: credentialTime });
		expect(credentialRow).toEqual({ id: credentialId, membership_id: membershipId, team_id: 'team', capacity_provider_id: providerId, key_prefix: z.string().min(1).parse(credential.keyPrefix), key_hash: z.string().min(1).parse(credentialRow.key_hash), issuance_authorization_id: authority.id, issuance_generation: 1, issue_idempotency_key: 'bootstrap-exchange', scopes_json: JSON.stringify(PROVIDER_MEMBERSHIP_SCOPES), status: 'active', last_used_at: null, rotated_from_credential_id: null, expires_at: null, revealed_at: credentialTime, revoked_at: null, revoke_idempotency_key: null, revoke_request_digest: null, created_at: credentialTime, updated_at: credentialTime });
		expect(additions(before, exchanged, 'capacity_provider_proof_nonces', 1)[0]).toEqual({ provider_fingerprint: exchange.payload.providerFingerprint, jti: exchange.payload.jti, expires_at: deadline, created_at: credentialTime }); audit(additions(before, exchanged, 'capacity_audit_events', 1)[0]!, 'provider-credential.issued', 'provider-team-credential', credentialId, 'bootstrap-exchange', credentialTime, {}, registration.request.id); exchange.unchanged(); expect(JSON.stringify(exchanged).includes(credentialValue)).toBe(false);
		// Only this genuinely enrolled membership in the allocated fresh database
		// can encounter this late native audit interruption. No product trigger.
		unelapsed(); await f.left.pool.query("CREATE FUNCTION bootstrap_access_audit_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'native first access token audit interruption' USING ERRCODE='P0001'; END $$");
		unelapsed(); await f.left.pool.query(`CREATE TRIGGER bootstrap_access_audit_failure BEFORE INSERT ON capacity_audit_events FOR EACH ROW WHEN (NEW.action='provider-access-token.issued' AND NEW.membership_id='${memberId}') EXECUTE FUNCTION bootstrap_access_audit_failure()`); unelapsed(); expect(await read()).toEqual(exchanged);
		const path = restPath(CONTROL_PLANE_OPERATIONS.providers.issueAccessToken.descriptor.rest), body = { credentialId, idempotencyKey: 'enrolled-first-token-audit-recovery', requestedValiditySeconds: 60 }, claims = { ...registration.inputs.payload, path, issuedAt: new Date().toISOString(), bodySha256: sha256(canonicalJson(body)), jti: randomUUID() }, request = { credentialId, requestedValiditySeconds: 60, proof: registration.inputs.proof(claims) }, original = structuredClone({ body, claims, request });
		const post = (wire: typeof request) => { unelapsed(); return f.app.request(new Request(`http://localhost${path}`, { method: 'POST', headers: { authorization: `Treeseed-Credential ${credentialValue}`, 'content-type': 'application/json', 'idempotency-key': body.idempotencyKey }, body: JSON.stringify(wire) })); };
		const failedStart = new Date().toISOString(), failed = await post(request), failedEnd = new Date().toISOString(); expect(failed.status).toBe(500); const failure = await read();
		unchangedExcept(exchanged, failure, ['capacity_provider_access_tokens', 'capacity_provider_proof_nonces']); const tokenRow = additions(exchanged, failure, 'capacity_provider_access_tokens', 1)[0]!, tokenId = z.string().uuid().parse(tokenRow.id), issuedAt = clock(tokenRow.issued_at, failedStart, failedEnd), expiresAt = z.string().parse(tokenRow.expires_at); expect(Date.parse(expiresAt) - Date.parse(issuedAt)).toBe(60000);
		expect(tokenRow).toEqual({ id: tokenId, membership_id: membershipId, credential_id: credentialId, idempotency_key: body.idempotencyKey, token_prefix: z.string().min(1).parse(tokenRow.token_prefix), token_hash: z.string().min(1).parse(tokenRow.token_hash), scopes_json: JSON.stringify(PROVIDER_MEMBERSHIP_SCOPES), status: 'active', issued_at: issuedAt, expires_at: expiresAt, last_used_at: null, expired_at: null, revoked_at: null, updated_at: issuedAt });
		expect(additions(exchanged, failure, 'capacity_provider_proof_nonces', 1)[0]).toEqual({ provider_fingerprint: claims.providerFingerprint, jti: claims.jti, expires_at: deadline, created_at: issuedAt }); expect({ body, claims, request }).toEqual(original); expect(JSON.stringify(failure).includes(credentialValue)).toBe(false);
		// Public 500 + retained native rows proves this failed footprint, not
		// whole-HTTP atomicity or visibility of the native exception message.
		unelapsed(); await f.left.pool.query('DROP TRIGGER bootstrap_access_audit_failure ON capacity_audit_events'); unelapsed(); await f.left.pool.query('DROP FUNCTION bootstrap_access_audit_failure()'); unelapsed();
		expect((await f.right.pool.query("SELECT tgname FROM pg_trigger WHERE tgrelid='public.capacity_audit_events'::regclass AND tgname='bootstrap_access_audit_failure'")).rows).toEqual([]); unelapsed(); expect((await f.right.pool.query("SELECT proname FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname='bootstrap_access_audit_failure'")).rows).toEqual([]); expect(await read()).toEqual(failure);
		await denied(await post(request), 409, 'provider_proof_replayed'); expect(await read()).toEqual(failure);
		const recoveryClaims = { ...claims, jti: randomUUID() }, recoveryRequest = { ...request, proof: registration.inputs.proof(recoveryClaims) }, recoveryBefore = structuredClone({ recoveryClaims, recoveryRequest }); expect(recoveryClaims.jti).not.toBe(claims.jti);
		const recoveryStart = new Date().toISOString(), recovered = record.parse(await output(await post(recoveryRequest), CONTROL_PLANE_OPERATIONS.providers.issueAccessToken)), recoveryEnd = new Date().toISOString(), recoveredState = await read(), bearer = z.string().min(1).parse(recovered.accessToken);
		expect({ ...recovered, accessToken: undefined }).toEqual({ id: tokenId, teamId: 'team', providerId, membershipId, credentialId, status: 'active', scopes: [...PROVIDER_MEMBERSHIP_SCOPES], issuedAt, expiresAt, identityVersion: 1, accessToken: undefined }); expect(bearer.startsWith(`${z.string().parse(tokenRow.token_prefix)}_`)).toBe(true);
		unchangedExcept(failure, recoveredState, ['capacity_provider_proof_nonces', 'capacity_audit_events']); const recoveryNonce = additions(failure, recoveredState, 'capacity_provider_proof_nonces', 1)[0]!, recoveryTime = clock(recoveryNonce.created_at, recoveryStart, recoveryEnd); expect(recoveryNonce).toEqual({ provider_fingerprint: recoveryClaims.providerFingerprint, jti: recoveryClaims.jti, expires_at: deadline, created_at: recoveryTime });
		audit(additions(failure, recoveredState, 'capacity_audit_events', 1)[0]!, 'provider-access-token.issued', 'provider-access-token', tokenId, body.idempotencyKey, issuedAt, { credentialId, expiresAt, validitySeconds: 60 }); expect(rows(recoveredState, 'capacity_provider_access_tokens')).toEqual(rows(failure, 'capacity_provider_access_tokens')); expect({ recoveryClaims, recoveryRequest }).toEqual(recoveryBefore); expect(JSON.stringify(recoveredState).includes(bearer)).toBe(false); expect(JSON.stringify(recoveredState).includes(credentialValue)).toBe(false);
		await denied(await post(recoveryRequest), 409, 'provider_proof_replayed'); expect(await read()).toEqual(recoveredState);
		const repeatClaims = { ...claims, jti: randomUUID() }, repeatRequest = { ...request, proof: registration.inputs.proof(repeatClaims) }, repeatBefore = structuredClone({ repeatClaims, repeatRequest }); expect(new Set([claims.jti, recoveryClaims.jti, repeatClaims.jti]).size).toBe(3);
		const repeatStart = new Date().toISOString(), repeated = record.parse(await output(await post(repeatRequest), CONTROL_PLANE_OPERATIONS.providers.issueAccessToken)), repeatEnd = new Date().toISOString(), repeatedState = await read(); expect(repeated.accessToken === bearer).toBe(true); expect({ ...repeated, accessToken: undefined }).toEqual({ ...recovered, accessToken: undefined });
		unchangedExcept(recoveredState, repeatedState, ['capacity_provider_proof_nonces']); const repeatNonce = additions(recoveredState, repeatedState, 'capacity_provider_proof_nonces', 1)[0]!, repeatTime = clock(repeatNonce.created_at, repeatStart, repeatEnd); expect(repeatNonce).toEqual({ provider_fingerprint: repeatClaims.providerFingerprint, jti: repeatClaims.jti, expires_at: deadline, created_at: repeatTime });
		expect({ body, claims, request }).toEqual(original); expect({ recoveryClaims, recoveryRequest }).toEqual(recoveryBefore); expect({ repeatClaims, repeatRequest }).toEqual(repeatBefore); exchange.unchanged(); unelapsed(); expect(JSON.stringify(repeatedState).includes(bearer)).toBe(false); expect(JSON.stringify(repeatedState).includes(credentialValue)).toBe(false);
	} finally { await f.close(); }
});

it('genuine enrolled PostgreSQL final token revocation interruption rolls back the entire identity rotation batch and admits the same original bearer proofs and key on retry without losing history', async () => {
	const f = await dependencyOperator();
	try {
		const { registration, membershipId } = await approved(f), providerId = registeredProviderId(registration), memberId = z.string().uuid().parse(membershipId), deadline = registration.inputs.payload.expiresAt, registrationBefore = structuredClone({ payload: registration.inputs.payload, body: registration.inputs.body, publicJwk: registration.inputs.publicJwk });
		const unelapsed = () => { expect(Date.now() < Date.parse(deadline)).toBe(true); expect({ payload: registration.inputs.payload, body: registration.inputs.body, publicJwk: registration.inputs.publicJwk }).toEqual(registrationBefore); };
		const read = async () => { unelapsed(); const value = await f.state(); expect(await f.state(f.right)).toEqual(value); unelapsed(); return value; };
		const clock = (value: unknown, start: string, end: string) => { const time = z.string().parse(value); expect(time >= start && time <= end && end < deadline).toBe(true); return time; };
		const audit = (row: Record<string, unknown>, action: string, resourceType: string, resourceId: string, key: string, actor: string, time: string, metadata: Record<string, unknown>, requestId: string | null = null) => expect(row).toEqual({ id: originalAuditId(action, resourceId, providerId, metadata), team_id: 'team', capacity_provider_id: providerId, membership_id: membershipId, actor_type: 'provider-identity', actor_id: actor, action, resource_type: resourceType, resource_id: resourceId, request_id: requestId, idempotency_key: key, before_fingerprint: null, after_fingerprint: null, metadata_json: JSON.stringify(metadata), created_at: time });
		const before = await read(), authority = rows(before, 'capacity_provider_credential_issuance_authorizations').find(row => row.membership_id === membershipId)!, exchange = exchangeStage(f, registration), exchangeStart = new Date().toISOString(), credential = record.parse(await output(await exchange.post(), CONTROL_PLANE_OPERATIONS.providers.exchangeCredential)), exchangeEnd = new Date().toISOString(), exchanged = await read();
		const credentialId = z.string().uuid().parse(credential.id), credentialValue = z.string().min(1).parse(credential.credential), credentialRow = additions(before, exchanged, 'capacity_provider_team_credentials', 1)[0]!, credentialTime = clock(credentialRow.created_at, exchangeStart, exchangeEnd);
		expect(authority).toMatchObject({ generation: 1, status: 'pending', issued_credential_id: null }); expect({ ...credential, credential: undefined }).toMatchObject({ membershipId, teamId: 'team', providerId, issuanceGeneration: 1, status: 'active', scopes: [...PROVIDER_MEMBERSHIP_SCOPES] });
		unchangedExcept(before, exchanged, ['capacity_provider_credential_issuance_authorizations', 'capacity_provider_team_credentials', 'capacity_provider_proof_nonces', 'capacity_audit_events']); changedRow(before, exchanged, 'capacity_provider_credential_issuance_authorizations', String(authority.id), {}, ['status', 'issued_credential_id', 'updated_at']); expect(rows(exchanged, 'capacity_provider_credential_issuance_authorizations').find(row => row.id === authority.id)).toEqual({ ...authority, status: 'issued', issued_credential_id: credentialId, updated_at: credentialTime });
		expect(credentialRow).toEqual({ id: credentialId, membership_id: membershipId, team_id: 'team', capacity_provider_id: providerId, key_prefix: z.string().min(1).parse(credential.keyPrefix), key_hash: z.string().min(1).parse(credentialRow.key_hash), issuance_authorization_id: authority.id, issuance_generation: 1, issue_idempotency_key: 'bootstrap-exchange', scopes_json: JSON.stringify(PROVIDER_MEMBERSHIP_SCOPES), status: 'active', last_used_at: null, rotated_from_credential_id: null, expires_at: null, revealed_at: credentialTime, revoked_at: null, revoke_idempotency_key: null, revoke_request_digest: null, created_at: credentialTime, updated_at: credentialTime });
		expect(additions(before, exchanged, 'capacity_provider_proof_nonces', 1)[0]).toEqual({ provider_fingerprint: exchange.payload.providerFingerprint, jti: exchange.payload.jti, expires_at: deadline, created_at: credentialTime }); audit(additions(before, exchanged, 'capacity_audit_events', 1)[0]!, 'provider-credential.issued', 'provider-team-credential', credentialId, 'bootstrap-exchange', exchange.payload.providerFingerprint, credentialTime, {}, registration.request.id); exchange.unchanged();
		const tokenPath = restPath(CONTROL_PLANE_OPERATIONS.providers.issueAccessToken.descriptor.rest), tokenBody = { credentialId, idempotencyKey: 'rotation-rollback-first-token', requestedValiditySeconds: 60 }, issuance = stage(f, registration, tokenPath, tokenBody, { credentialId, requestedValiditySeconds: 60 }, `Treeseed-Credential ${credentialValue}`), tokenStart = new Date().toISOString(), token = record.parse(await output(await issuance.post(), CONTROL_PLANE_OPERATIONS.providers.issueAccessToken)), tokenEnd = new Date().toISOString(), baseline = await read();
		const tokenId = z.string().uuid().parse(token.id), bearer = z.string().min(1).parse(token.accessToken), tokenTime = clock(token.issuedAt, tokenStart, tokenEnd), tokenExpiry = z.string().parse(token.expiresAt), tokenRow = additions(exchanged, baseline, 'capacity_provider_access_tokens', 1)[0]!;
		unchangedExcept(exchanged, baseline, ['capacity_provider_access_tokens', 'capacity_provider_proof_nonces', 'capacity_audit_events']); expect(Date.parse(tokenExpiry) - Date.parse(tokenTime)).toBe(60000); expect({ ...token, accessToken: undefined }).toEqual({ id: tokenId, teamId: 'team', providerId, membershipId, credentialId, status: 'active', scopes: [...PROVIDER_MEMBERSHIP_SCOPES], issuedAt: tokenTime, expiresAt: tokenExpiry, identityVersion: 1, accessToken: undefined });
		expect(tokenRow).toEqual({ id: tokenId, membership_id: membershipId, credential_id: credentialId, idempotency_key: tokenBody.idempotencyKey, token_prefix: z.string().min(1).parse(tokenRow.token_prefix), token_hash: z.string().min(1).parse(tokenRow.token_hash), scopes_json: JSON.stringify(PROVIDER_MEMBERSHIP_SCOPES), status: 'active', issued_at: tokenTime, expires_at: tokenExpiry, last_used_at: null, expired_at: null, revoked_at: null, updated_at: tokenTime });
		expect(additions(exchanged, baseline, 'capacity_provider_proof_nonces', 1)[0]).toEqual({ provider_fingerprint: issuance.payload.providerFingerprint, jti: issuance.payload.jti, expires_at: deadline, created_at: tokenTime }); audit(additions(exchanged, baseline, 'capacity_audit_events', 1)[0]!, 'provider-access-token.issued', 'provider-access-token', tokenId, tokenBody.idempotencyKey, issuance.payload.providerFingerprint, tokenTime, { credentialId, expiresAt: tokenExpiry, validitySeconds: 60 }); issuance.unchanged(); expect(JSON.stringify(baseline).includes(credentialValue)).toBe(false); expect(JSON.stringify(baseline).includes(bearer)).toBe(false);
		const identity = rows(baseline, 'capacity_providers').find(row => row.id === providerId)!, nextKey = tokenProofInputs(new Date(), deadline, registration.inputs.payload.audience), path = restPath(CONTROL_PLANE_OPERATIONS.providers.rotateIdentity.descriptor.rest), key = 'enrolled-rotation-transaction-retry', signed = { expectedIdentityVersion: 1, newPublicJwk: nextKey.publicJwk }, digest = sha256(canonicalJson(signed));
		const oldClaims = { ...registration.inputs.payload, path, issuedAt: new Date().toISOString(), bodySha256: digest, jti: randomUUID() }, newClaims = { ...nextKey.payload, path, identityVersion: 2, bodySha256: digest, jti: randomUUID() }, body = { ...signed, oldProof: registration.inputs.proof(oldClaims), newProof: nextKey.proof(newClaims) }, original = structuredClone({ oldClaims, newClaims, body }); expect(oldClaims.jti).not.toBe(newClaims.jti);
		// Interrupt the LAST original batch write, after nonce/evidence/identity
		// writes have been attempted, ONLY for this allocated native membership.
		unelapsed(); await f.left.pool.query("CREATE FUNCTION bootstrap_rotation_token_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'native final rotation token interruption' USING ERRCODE='P0001'; END $$");
		unelapsed(); await f.left.pool.query(`CREATE TRIGGER bootstrap_rotation_token_failure BEFORE UPDATE ON capacity_provider_access_tokens FOR EACH ROW WHEN (OLD.membership_id='${memberId}' AND OLD.status='active' AND NEW.status='revoked') EXECUTE FUNCTION bootstrap_rotation_token_failure()`); unelapsed();
		unelapsed(); const failedStart = new Date().toISOString(), failed = await f.post(path, bearer, body, key), failedEnd = new Date().toISOString(); expect(failed.status).toBe(500); const failedState = await read();
		// Bearer authentication legitimately precedes the rotation transaction.
		// Its token-use clock is retained, never hidden as a rollback assertion.
		unchangedExcept(baseline, failedState, ['capacity_provider_access_tokens']); const usedAfterFailure = rows(failedState, 'capacity_provider_access_tokens').find(row => row.id === tokenId)!, failedUse = clock(usedAfterFailure.last_used_at, failedStart, failedEnd); changedRow(baseline, failedState, 'capacity_provider_access_tokens', tokenId, {}, ['last_used_at', 'updated_at']); expect(usedAfterFailure).toEqual({ ...tokenRow, last_used_at: failedUse, updated_at: failedUse }); expect({ oldClaims, newClaims, body }).toEqual(original);
		unelapsed(); await f.left.pool.query('DROP TRIGGER bootstrap_rotation_token_failure ON capacity_provider_access_tokens'); unelapsed(); await f.left.pool.query('DROP FUNCTION bootstrap_rotation_token_failure()'); unelapsed(); expect((await f.right.pool.query("SELECT tgname FROM pg_trigger WHERE tgrelid='public.capacity_provider_access_tokens'::regclass AND tgname='bootstrap_rotation_token_failure'")).rows).toEqual([]); unelapsed(); expect((await f.right.pool.query("SELECT proname FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname='bootstrap_rotation_token_failure'")).rows).toEqual([]); expect(await read()).toEqual(failedState);
		// EXACT same original Bearer, key, body and proof nonces/expiry. No fresh
		// proof or replacement token conceals a partially committed transaction.
		unelapsed(); const retryStart = new Date().toISOString(), retry = await f.post(path, bearer, body, key), retryEnd = new Date().toISOString(); expect(retry.status).toBe(200); const envelope = z.object({ data: z.unknown() }).parse(await retry.json()), result = CONTROL_PLANE_OPERATIONS.providers.rotateIdentity.schema.output.parse(envelope.data), rotated = await read(), time = clock(result.rotatedAt, retryStart, retryEnd);
		expect(result).toEqual({ schemaVersion: 1, providerId, fingerprint: newClaims.providerFingerprint, publicJwk: nextKey.publicJwk, displayName: identity.display_name, identityVersion: 2, status: 'active', createdAt: identity.created_at, updatedAt: time, rotatedAt: time, revokedAt: null });
		unchangedExcept(failedState, rotated, ['capacity_providers', 'capacity_provider_identity_rotations', 'capacity_provider_proof_nonces', 'capacity_provider_access_tokens', 'capacity_audit_events']); changedRow(failedState, rotated, 'capacity_providers', providerId, {}, ['fingerprint', 'public_jwk_json', 'identity_version', 'rotated_at', 'updated_at']); expect(rows(rotated, 'capacity_providers').find(row => row.id === providerId)).toEqual({ ...identity, fingerprint: newClaims.providerFingerprint, public_jwk_json: canonicalJson(nextKey.publicJwk), identity_version: 2, rotated_at: time, updated_at: time });
		expect(additions(failedState, rotated, 'capacity_provider_identity_rotations', 1)[0]).toEqual({ id: z.string().uuid().parse(rows(rotated, 'capacity_provider_identity_rotations').find(row => row.idempotency_key === key && row.capacity_provider_id === providerId)!.id), capacity_provider_id: providerId, from_identity_version: 1, to_identity_version: 2, old_fingerprint: oldClaims.providerFingerprint, new_fingerprint: newClaims.providerFingerprint, idempotency_key: key, request_digest: digest, created_at: time });
		const nonces = additions(failedState, rotated, 'capacity_provider_proof_nonces', 2); for (const claims of [oldClaims, newClaims]) expect(nonces).toContainEqual({ provider_fingerprint: claims.providerFingerprint, jti: claims.jti, expires_at: deadline, created_at: time });
		const revoked = rows(rotated, 'capacity_provider_access_tokens').find(row => row.id === tokenId)!, used = clock(revoked.last_used_at, retryStart, retryEnd); expect(used <= time).toBe(true); changedRow(failedState, rotated, 'capacity_provider_access_tokens', tokenId, {}, ['status', 'last_used_at', 'revoked_at', 'updated_at']); expect(revoked).toEqual({ ...usedAfterFailure, status: 'revoked', last_used_at: used, revoked_at: time, updated_at: time });
		audit(additions(failedState, rotated, 'capacity_audit_events', 1)[0]!, 'provider-identity.rotated', 'capacity-provider', providerId, key, oldClaims.providerFingerprint, time, { previousFingerprint: oldClaims.providerFingerprint, fingerprint: newClaims.providerFingerprint, previousVersion: 1, identityVersion: 2 });
		await denied(await f.post(path, bearer, body, key), 401, 'provider_authentication_required'); expect(await read()).toEqual(rotated); expect({ oldClaims, newClaims, body }).toEqual(original); exchange.unchanged(); issuance.unchanged(); unelapsed(); expect(JSON.stringify(rotated).includes(credentialValue)).toBe(false); expect(JSON.stringify(rotated).includes(bearer)).toBe(false);
	} finally { await f.close(); }
});

it('genuine enrolled PostgreSQL late identity rotation audit failure retains committed keys proofs and revocation then current bearer replay recovers one original audit without rewriting failed history', async () => {
	const f = await dependencyOperator();
	try {
		const { registration, membershipId } = await approved(f), providerId = registeredProviderId(registration), deadline = registration.inputs.payload.expiresAt, registrationBefore = structuredClone({ payload: registration.inputs.payload, body: registration.inputs.body, publicJwk: registration.inputs.publicJwk });
		const unelapsed = () => { expect(Date.now() < Date.parse(deadline)).toBe(true); expect({ payload: registration.inputs.payload, body: registration.inputs.body, publicJwk: registration.inputs.publicJwk }).toEqual(registrationBefore); };
		const read = async () => { unelapsed(); const value = await f.state(); expect(await f.state(f.right)).toEqual(value); unelapsed(); return value; };
		const clock = (value: unknown, start: string, end: string) => { const time = z.string().parse(value); expect(time >= start && time <= end && end < deadline).toBe(true); return time; };
		const audit = (row: Record<string, unknown>, action: string, resourceType: string, resourceId: string, key: string, actor: string, time: string, metadata: Record<string, unknown>, requestId: string | null = null) => expect(row).toEqual({ id: originalAuditId(action, resourceId, providerId, metadata), team_id: 'team', capacity_provider_id: providerId, membership_id: membershipId, actor_type: 'provider-identity', actor_id: actor, action, resource_type: resourceType, resource_id: resourceId, request_id: requestId, idempotency_key: key, before_fingerprint: null, after_fingerprint: null, metadata_json: JSON.stringify(metadata), created_at: time });
		const before = await read(), authority = rows(before, 'capacity_provider_credential_issuance_authorizations').find(row => row.membership_id === membershipId)!, exchange = exchangeStage(f, registration), exchangeStart = new Date().toISOString(), credential = record.parse(await output(await exchange.post(), CONTROL_PLANE_OPERATIONS.providers.exchangeCredential)), exchangeEnd = new Date().toISOString(), exchanged = await read();
		const credentialId = z.string().uuid().parse(credential.id), credentialValue = z.string().min(1).parse(credential.credential), credentialRow = additions(before, exchanged, 'capacity_provider_team_credentials', 1)[0]!, credentialTime = clock(credentialRow.created_at, exchangeStart, exchangeEnd);
		expect(authority).toMatchObject({ generation: 1, status: 'pending', issued_credential_id: null }); expect({ ...credential, credential: undefined }).toMatchObject({ membershipId, teamId: 'team', providerId, issuanceGeneration: 1, status: 'active', scopes: [...PROVIDER_MEMBERSHIP_SCOPES] });
		unchangedExcept(before, exchanged, ['capacity_provider_credential_issuance_authorizations', 'capacity_provider_team_credentials', 'capacity_provider_proof_nonces', 'capacity_audit_events']); changedRow(before, exchanged, 'capacity_provider_credential_issuance_authorizations', String(authority.id), {}, ['status', 'issued_credential_id', 'updated_at']); expect(rows(exchanged, 'capacity_provider_credential_issuance_authorizations').find(row => row.id === authority.id)).toEqual({ ...authority, status: 'issued', issued_credential_id: credentialId, updated_at: credentialTime });
		expect(credentialRow).toEqual({ id: credentialId, membership_id: membershipId, team_id: 'team', capacity_provider_id: providerId, key_prefix: z.string().min(1).parse(credential.keyPrefix), key_hash: z.string().min(1).parse(credentialRow.key_hash), issuance_authorization_id: authority.id, issuance_generation: 1, issue_idempotency_key: 'bootstrap-exchange', scopes_json: JSON.stringify(PROVIDER_MEMBERSHIP_SCOPES), status: 'active', last_used_at: null, rotated_from_credential_id: null, expires_at: null, revealed_at: credentialTime, revoked_at: null, revoke_idempotency_key: null, revoke_request_digest: null, created_at: credentialTime, updated_at: credentialTime });
		expect(additions(before, exchanged, 'capacity_provider_proof_nonces', 1)[0]).toEqual({ provider_fingerprint: exchange.payload.providerFingerprint, jti: exchange.payload.jti, expires_at: deadline, created_at: credentialTime }); audit(additions(before, exchanged, 'capacity_audit_events', 1)[0]!, 'provider-credential.issued', 'provider-team-credential', credentialId, 'bootstrap-exchange', exchange.payload.providerFingerprint, credentialTime, {}, registration.request.id); exchange.unchanged();
		const tokenPath = restPath(CONTROL_PLANE_OPERATIONS.providers.issueAccessToken.descriptor.rest), tokenBody = { credentialId, idempotencyKey: 'audit-recovery-token-one', requestedValiditySeconds: 60 }, tokenStage = stage(f, registration, tokenPath, tokenBody, { credentialId, requestedValiditySeconds: 60 }, `Treeseed-Credential ${credentialValue}`), tokenStart = new Date().toISOString(), first = record.parse(await output(await tokenStage.post(), CONTROL_PLANE_OPERATIONS.providers.issueAccessToken)), tokenEnd = new Date().toISOString(), tokenState = await read();
		const tokenFootprint = (prior: State, next: State, token: Record<string, unknown>, key: string, claims: typeof tokenStage.payload, start: string, end: string, version: number) => {
			unchangedExcept(prior, next, ['capacity_provider_access_tokens', 'capacity_provider_proof_nonces', 'capacity_audit_events']); const id = z.string().uuid().parse(token.id), time = clock(token.issuedAt, start, end), expires = z.string().parse(token.expiresAt), saved = additions(prior, next, 'capacity_provider_access_tokens', 1)[0]!;
			expect(Date.parse(expires) - Date.parse(time)).toBe(60000); expect({ ...token, accessToken: undefined }).toEqual({ id, teamId: 'team', providerId, membershipId, credentialId, status: 'active', scopes: [...PROVIDER_MEMBERSHIP_SCOPES], issuedAt: time, expiresAt: expires, identityVersion: version, accessToken: undefined });
			expect(saved).toEqual({ id, membership_id: membershipId, credential_id: credentialId, idempotency_key: key, token_prefix: z.string().min(1).parse(saved.token_prefix), token_hash: z.string().min(1).parse(saved.token_hash), scopes_json: JSON.stringify(PROVIDER_MEMBERSHIP_SCOPES), status: 'active', issued_at: time, expires_at: expires, last_used_at: null, expired_at: null, revoked_at: null, updated_at: time });
			expect(additions(prior, next, 'capacity_provider_proof_nonces', 1)[0]).toEqual({ provider_fingerprint: claims.providerFingerprint, jti: claims.jti, expires_at: deadline, created_at: time }); audit(additions(prior, next, 'capacity_audit_events', 1)[0]!, 'provider-access-token.issued', 'provider-access-token', id, key, claims.providerFingerprint, time, { credentialId, expiresAt: expires, validitySeconds: 60 }); expect(JSON.stringify(next).includes(z.string().min(1).parse(token.accessToken))).toBe(false); expect(JSON.stringify(next).includes(credentialValue)).toBe(false);
		};
		tokenFootprint(exchanged, tokenState, first, tokenBody.idempotencyKey, tokenStage.payload, tokenStart, tokenEnd, 1); tokenStage.unchanged();
		const oldIdentity = rows(tokenState, 'capacity_providers').find(row => row.id === providerId)!, nextKey = tokenProofInputs(new Date(), deadline, registration.inputs.payload.audience), rotationPath = restPath(CONTROL_PLANE_OPERATIONS.providers.rotateIdentity.descriptor.rest), rotationKey = 'enrolled-rotation-audit-recovery', signed = { expectedIdentityVersion: 1, newPublicJwk: nextKey.publicJwk }, digest = sha256(canonicalJson(signed));
		const oldClaims = { ...registration.inputs.payload, path: rotationPath, issuedAt: new Date().toISOString(), bodySha256: digest, jti: randomUUID() }, newClaims = { ...nextKey.payload, path: rotationPath, identityVersion: 2, bodySha256: digest, jti: randomUUID() }, body = { ...signed, oldProof: registration.inputs.proof(oldClaims), newProof: nextKey.proof(newClaims) }, original = structuredClone({ oldClaims, newClaims, body }); expect(oldClaims.jti).not.toBe(newClaims.jti);
		// Native failure injection ONLY in the same allocated fresh database;
		// no returned identity/audit row or failed public response is fabricated.
		await f.left.pool.query("CREATE FUNCTION bootstrap_identity_audit_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'native bootstrap identity audit interruption' USING ERRCODE='P0001'; END $$");
		await f.left.pool.query(`CREATE TRIGGER bootstrap_identity_audit_failure BEFORE INSERT ON capacity_audit_events FOR EACH ROW WHEN (NEW.action='provider-identity.rotated' AND NEW.capacity_provider_id='${providerId}') EXECUTE FUNCTION bootstrap_identity_audit_failure()`);
		unelapsed(); const failedStart = new Date().toISOString(), failedResponse = await f.post(rotationPath, z.string().min(1).parse(first.accessToken), body, rotationKey), failedEnd = new Date().toISOString(); expect(failedResponse.status).toBe(500); const failure = await read();
		unchangedExcept(tokenState, failure, ['capacity_providers', 'capacity_provider_identity_rotations', 'capacity_provider_access_tokens', 'capacity_provider_proof_nonces']);
		const rotation = additions(tokenState, failure, 'capacity_provider_identity_rotations', 1)[0]!, rotationTime = clock(rotation.created_at, failedStart, failedEnd); expect(rotation).toEqual({ id: z.string().uuid().parse(rotation.id), capacity_provider_id: providerId, from_identity_version: 1, to_identity_version: 2, old_fingerprint: oldClaims.providerFingerprint, new_fingerprint: newClaims.providerFingerprint, idempotency_key: rotationKey, request_digest: digest, created_at: rotationTime });
		changedRow(tokenState, failure, 'capacity_providers', providerId, {}, ['fingerprint', 'public_jwk_json', 'identity_version', 'rotated_at', 'updated_at']); expect(rows(failure, 'capacity_providers').find(row => row.id === providerId)).toEqual({ ...oldIdentity, fingerprint: newClaims.providerFingerprint, public_jwk_json: canonicalJson(nextKey.publicJwk), identity_version: 2, rotated_at: rotationTime, updated_at: rotationTime });
		const nonces = additions(tokenState, failure, 'capacity_provider_proof_nonces', 2); for (const claims of [oldClaims, newClaims]) expect(nonces).toContainEqual({ provider_fingerprint: claims.providerFingerprint, jti: claims.jti, expires_at: deadline, created_at: rotationTime });
		const firstId = z.string().uuid().parse(first.id), oldToken = rows(tokenState, 'capacity_provider_access_tokens').find(row => row.id === firstId)!, revoked = rows(failure, 'capacity_provider_access_tokens').find(row => row.id === firstId)!, firstUsed = clock(revoked.last_used_at, failedStart, failedEnd); expect(firstUsed <= rotationTime).toBe(true); changedRow(tokenState, failure, 'capacity_provider_access_tokens', firstId, {}, ['status', 'last_used_at', 'revoked_at', 'updated_at']); expect(revoked).toEqual({ ...oldToken, status: 'revoked', last_used_at: firstUsed, revoked_at: rotationTime, updated_at: rotationTime }); expect({ oldClaims, newClaims, body }).toEqual(original);
		await f.left.pool.query('DROP TRIGGER bootstrap_identity_audit_failure ON capacity_audit_events'); await f.left.pool.query('DROP FUNCTION bootstrap_identity_audit_failure()');
		expect((await f.right.pool.query("SELECT tgname FROM pg_trigger WHERE tgrelid='public.capacity_audit_events'::regclass AND tgname='bootstrap_identity_audit_failure'")).rows).toEqual([]); expect((await f.right.pool.query("SELECT proname FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname='bootstrap_identity_audit_failure'")).rows).toEqual([]); expect(await read()).toEqual(failure);
		await denied(await f.post(rotationPath, z.string().parse(first.accessToken), body, rotationKey), 401, 'provider_authentication_required'); expect(await read()).toEqual(failure);
		const currentBody = { credentialId, idempotencyKey: 'audit-recovery-token-two', requestedValiditySeconds: 60 }, currentClaims = { ...nextKey.payload, identityVersion: 2, bodySha256: sha256(canonicalJson(currentBody)), jti: randomUUID() }, wire = { credentialId, requestedValiditySeconds: 60, proof: nextKey.proof(currentClaims) }, tokenInput = structuredClone({ currentBody, currentClaims, wire }); unelapsed();
		const currentStart = new Date().toISOString(), currentResponse = await f.app.request(new Request(`http://localhost${tokenPath}`, { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': currentBody.idempotencyKey, authorization: `Treeseed-Credential ${credentialValue}` }, body: JSON.stringify(wire) })), currentToken = record.parse(await output(currentResponse, CONTROL_PLANE_OPERATIONS.providers.issueAccessToken)), currentEnd = new Date().toISOString(), beforeRecovery = await read(); tokenFootprint(failure, beforeRecovery, currentToken, currentBody.idempotencyKey, currentClaims, currentStart, currentEnd, 2);
		const expectedIdentity = { schemaVersion: 1, providerId, fingerprint: newClaims.providerFingerprint, publicJwk: nextKey.publicJwk, displayName: oldIdentity.display_name, identityVersion: 2, status: 'active', createdAt: oldIdentity.created_at, updatedAt: rotationTime, rotatedAt: rotationTime, revokedAt: null }, currentId = z.string().uuid().parse(currentToken.id), beforeToken = rows(beforeRecovery, 'capacity_provider_access_tokens').find(row => row.id === currentId)!;
		unelapsed(); const recoveryStart = new Date().toISOString(), recovery = await f.post(rotationPath, z.string().min(1).parse(currentToken.accessToken), body, rotationKey), recoveryEnd = new Date().toISOString(); expect(recovery.status).toBe(200); const recoveryEnvelope = z.object({ data: z.unknown() }).parse(await recovery.json()); expect(CONTROL_PLANE_OPERATIONS.providers.rotateIdentity.schema.output.parse(recoveryEnvelope.data)).toEqual(expectedIdentity);
		const recovered = await read(); unchangedExcept(beforeRecovery, recovered, ['capacity_provider_access_tokens', 'capacity_audit_events']); const recoveryToken = rows(recovered, 'capacity_provider_access_tokens').find(row => row.id === currentId)!, used = clock(recoveryToken.last_used_at, recoveryStart, recoveryEnd); changedRow(beforeRecovery, recovered, 'capacity_provider_access_tokens', currentId, {}, ['last_used_at', 'updated_at']); expect(recoveryToken).toEqual({ ...beforeToken, last_used_at: used, updated_at: used });
		// The missing event belongs to the original committed transition, not
		// the retry's new key, current actor, clock, or reconstructed identity.
		audit(additions(beforeRecovery, recovered, 'capacity_audit_events', 1)[0]!, 'provider-identity.rotated', 'capacity-provider', providerId, rotationKey, oldClaims.providerFingerprint, rotationTime, { previousFingerprint: oldClaims.providerFingerprint, fingerprint: newClaims.providerFingerprint, previousVersion: 1, identityVersion: 2 });
		unelapsed(); const replayStart = new Date().toISOString(), replay = await f.post(rotationPath, z.string().parse(currentToken.accessToken), body, rotationKey), replayEnd = new Date().toISOString(); expect(replay.status).toBe(200); expect(await replay.json()).toEqual(recoveryEnvelope); const replayed = await read(), usedAgain = rows(replayed, 'capacity_provider_access_tokens').find(row => row.id === currentId)!, replayTime = clock(usedAgain.last_used_at, replayStart, replayEnd); unchangedExcept(recovered, replayed, ['capacity_provider_access_tokens']); changedRow(recovered, replayed, 'capacity_provider_access_tokens', currentId, {}, ['last_used_at', 'updated_at']); expect(usedAgain).toEqual({ ...recoveryToken, last_used_at: replayTime, updated_at: replayTime });
		expect({ oldClaims, newClaims, body }).toEqual(original); expect({ currentBody, currentClaims, wire }).toEqual(tokenInput); unelapsed();
	} finally { await f.close(); }
});

it('genuine enrolled PostgreSQL two key identity rotation admits the current signed version and denies stale future and old key token proofs without consuming authority or rewriting independent history', async () => {
	const f = await dependencyOperator();
	try {
		const { registration, membershipId } = await approved(f), deadline = registration.inputs.payload.expiresAt, providerId = registeredProviderId(registration), originalRegistration = structuredClone({ payload: registration.inputs.payload, body: registration.inputs.body, publicJwk: registration.inputs.publicJwk });
		const unelapsed = () => { expect(Date.now() < Date.parse(deadline)).toBe(true); expect({ payload: registration.inputs.payload, body: registration.inputs.body, publicJwk: registration.inputs.publicJwk }).toEqual(originalRegistration); };
		const read = async () => { unelapsed(); const state = await f.state(); expect(await f.state(f.right)).toEqual(state); unelapsed(); return state; };
		const clock = (value: unknown, start: string, end: string) => { const time = z.string().parse(value); expect(time >= start && time <= end && end < deadline).toBe(true); return time; };
		const audit = (row: Record<string, unknown>, action: string, resourceType: string, resourceId: string, key: string, fingerprint: string, time: string, metadata: Record<string, unknown>, requestId: string | null = null) => {
			expect(row).toEqual({ id: originalAuditId(action, resourceId, providerId, metadata), team_id: 'team', capacity_provider_id: providerId, membership_id: membershipId, actor_type: 'provider-identity', actor_id: fingerprint, action, resource_type: resourceType, resource_id: resourceId, request_id: requestId, idempotency_key: key, before_fingerprint: null, after_fingerprint: null, metadata_json: JSON.stringify(metadata), created_at: time });
		};
		const before = await read(), exchange = exchangeStage(f, registration), exchangeStarted = new Date().toISOString(), credential = record.parse(await output(await exchange.post(), CONTROL_PLANE_OPERATIONS.providers.exchangeCredential)), exchangeReceived = new Date().toISOString(), exchanged = await read();
		const credentialId = z.string().uuid().parse(credential.id), credentialValue = z.string().min(1).parse(credential.credential), authority = rows(before, 'capacity_provider_credential_issuance_authorizations').find(row => row.membership_id === membershipId)!;
		expect(authority).toMatchObject({ generation: 1, status: 'pending', issued_credential_id: null }); expect({ ...credential, credential: undefined }).toMatchObject({ membershipId, teamId: 'team', providerId, issuanceGeneration: 1, status: 'active', scopes: [...PROVIDER_MEMBERSHIP_SCOPES] });
		unchangedExcept(before, exchanged, ['capacity_provider_credential_issuance_authorizations', 'capacity_provider_team_credentials', 'capacity_provider_proof_nonces', 'capacity_audit_events']);
		const issuedCredential = additions(before, exchanged, 'capacity_provider_team_credentials', 1)[0]!, credentialTime = clock(issuedCredential.created_at, exchangeStarted, exchangeReceived);
		expect(issuedCredential).toEqual({ id: credentialId, membership_id: membershipId, team_id: 'team', capacity_provider_id: providerId, key_prefix: z.string().min(1).parse(credential.keyPrefix), key_hash: z.string().min(1).parse(issuedCredential.key_hash), issuance_authorization_id: authority.id, issuance_generation: 1, issue_idempotency_key: 'bootstrap-exchange', scopes_json: JSON.stringify(PROVIDER_MEMBERSHIP_SCOPES), status: 'active', last_used_at: null, rotated_from_credential_id: null, expires_at: null, revealed_at: credentialTime, revoked_at: null, revoke_idempotency_key: null, revoke_request_digest: null, created_at: credentialTime, updated_at: credentialTime });
		changedRow(before, exchanged, 'capacity_provider_credential_issuance_authorizations', String(authority.id), {}, ['status', 'issued_credential_id', 'updated_at']);
		// Exact old-row replacement, including every original column, rather
		// than treating an enrollment helper's return as durable authority.
		const changedAuthority = rows(exchanged, 'capacity_provider_credential_issuance_authorizations').find(row => row.id === authority.id)!;
		expect(changedAuthority).toEqual({ ...authority, status: 'issued', issued_credential_id: credentialId, updated_at: credentialTime });
		expect(additions(before, exchanged, 'capacity_provider_proof_nonces', 1)[0]).toEqual({ provider_fingerprint: exchange.payload.providerFingerprint, jti: exchange.payload.jti, expires_at: deadline, created_at: credentialTime });
		audit(additions(before, exchanged, 'capacity_audit_events', 1)[0]!, 'provider-credential.issued', 'provider-team-credential', credentialId, 'bootstrap-exchange', exchange.payload.providerFingerprint, credentialTime, {}, registration.request.id); exchange.unchanged();
		const tokenPath = restPath(CONTROL_PLANE_OPERATIONS.providers.issueAccessToken.descriptor.rest), firstBody = { credentialId, idempotencyKey: 'enrolled-identity-token-one', requestedValiditySeconds: 60 }, firstStage = stage(f, registration, tokenPath, firstBody, { credentialId, requestedValiditySeconds: 60 }, `Treeseed-Credential ${credentialValue}`);
		const firstStart = new Date().toISOString(), firstToken = record.parse(await output(await firstStage.post(), CONTROL_PLANE_OPERATIONS.providers.issueAccessToken)), firstEnd = new Date().toISOString(), tokenState = await read();
		const tokenFootprint = (prior: State, next: State, token: Record<string, unknown>, body: typeof firstBody, payload: typeof firstStage.payload, start: string, end: string, version: number) => {
			unchangedExcept(prior, next, ['capacity_provider_access_tokens', 'capacity_provider_proof_nonces', 'capacity_audit_events']); const id = z.string().uuid().parse(token.id), time = clock(token.issuedAt, start, end), expires = z.string().parse(token.expiresAt), saved = additions(prior, next, 'capacity_provider_access_tokens', 1)[0]!;
			expect(Date.parse(expires) - Date.parse(time)).toBe(60000); expect({ ...token, accessToken: undefined }).toEqual({ id, teamId: 'team', providerId, membershipId, credentialId, status: 'active', scopes: [...PROVIDER_MEMBERSHIP_SCOPES], issuedAt: time, expiresAt: expires, identityVersion: version, accessToken: undefined });
			expect(saved).toEqual({ id, membership_id: membershipId, credential_id: credentialId, idempotency_key: body.idempotencyKey, token_prefix: z.string().min(1).parse(saved.token_prefix), token_hash: z.string().min(1).parse(saved.token_hash), scopes_json: JSON.stringify(PROVIDER_MEMBERSHIP_SCOPES), status: 'active', issued_at: time, expires_at: expires, last_used_at: null, expired_at: null, revoked_at: null, updated_at: time });
			expect(additions(prior, next, 'capacity_provider_proof_nonces', 1)[0]).toEqual({ provider_fingerprint: payload.providerFingerprint, jti: payload.jti, expires_at: deadline, created_at: time }); audit(additions(prior, next, 'capacity_audit_events', 1)[0]!, 'provider-access-token.issued', 'provider-access-token', id, body.idempotencyKey, payload.providerFingerprint, time, { credentialId, expiresAt: expires, validitySeconds: 60 });
			expect(JSON.stringify(next).includes(z.string().min(1).parse(token.accessToken))).toBe(false); expect(JSON.stringify(next).includes(credentialValue)).toBe(false);
		};
		tokenFootprint(exchanged, tokenState, record.parse(firstToken), firstBody, firstStage.payload, firstStart, firstEnd, 1); firstStage.unchanged();
		const originalIdentity = rows(tokenState, 'capacity_providers').find(row => row.id === providerId)!, nextKey = tokenProofInputs(new Date(), deadline, registration.inputs.payload.audience), rotationPath = restPath(CONTROL_PLANE_OPERATIONS.providers.rotateIdentity.descriptor.rest), rotationKey = 'enrolled-two-key-rotation';
		const signedBody = { expectedIdentityVersion: 1, newPublicJwk: nextKey.publicJwk }, digest = sha256(canonicalJson(signedBody)), oldClaims = { ...registration.inputs.payload, path: rotationPath, issuedAt: new Date().toISOString(), bodySha256: digest, jti: randomUUID() }, newClaims = { ...nextKey.payload, path: rotationPath, identityVersion: 2, bodySha256: digest, jti: randomUUID() }, rotationBody = { ...signedBody, oldProof: registration.inputs.proof(oldClaims), newProof: nextKey.proof(newClaims) }, rotationBefore = structuredClone({ oldClaims, newClaims, rotationBody });
		expect(oldClaims.jti).not.toBe(newClaims.jti); unelapsed(); const rotationStart = new Date().toISOString(), response = await f.post(rotationPath, z.string().min(1).parse(firstToken.accessToken), rotationBody, rotationKey), rotationEnd = new Date().toISOString(); expect(response.status).toBe(200);
		const rotationEnvelope = z.object({ data: z.unknown() }).parse(await response.json()), rotatedIdentity = CONTROL_PLANE_OPERATIONS.providers.rotateIdentity.schema.output.parse(rotationEnvelope.data), rotated = await read(), rotationTime = clock(rotatedIdentity.rotatedAt, rotationStart, rotationEnd);
		expect(rotatedIdentity).toEqual({ schemaVersion: 1, providerId, fingerprint: nextKey.payload.providerFingerprint, publicJwk: nextKey.publicJwk, displayName: originalIdentity.display_name, identityVersion: 2, status: 'active', createdAt: originalIdentity.created_at, updatedAt: rotationTime, rotatedAt: rotationTime, revokedAt: null });
		unchangedExcept(tokenState, rotated, ['capacity_providers', 'capacity_provider_identity_rotations', 'capacity_provider_access_tokens', 'capacity_provider_proof_nonces', 'capacity_audit_events']);
		changedRow(tokenState, rotated, 'capacity_providers', providerId, {}, ['fingerprint', 'public_jwk_json', 'identity_version', 'rotated_at', 'updated_at']); expect(rows(rotated, 'capacity_providers').find(row => row.id === providerId)).toEqual({ ...originalIdentity, fingerprint: nextKey.payload.providerFingerprint, public_jwk_json: canonicalJson(nextKey.publicJwk), identity_version: 2, rotated_at: rotationTime, updated_at: rotationTime });
		const rotation = additions(tokenState, rotated, 'capacity_provider_identity_rotations', 1)[0]!; expect(rotation).toEqual({ id: z.string().uuid().parse(rotation.id), capacity_provider_id: providerId, from_identity_version: 1, to_identity_version: 2, old_fingerprint: oldClaims.providerFingerprint, new_fingerprint: newClaims.providerFingerprint, idempotency_key: rotationKey, request_digest: digest, created_at: rotationTime });
		const rotationNonces = additions(tokenState, rotated, 'capacity_provider_proof_nonces', 2); for (const claims of [oldClaims, newClaims]) expect(rotationNonces).toContainEqual({ provider_fingerprint: claims.providerFingerprint, jti: claims.jti, expires_at: deadline, created_at: rotationTime });
		const oldTokenId = z.string().parse(firstToken.id), oldTokenRow = rows(tokenState, 'capacity_provider_access_tokens').find(row => row.id === oldTokenId)!, revokedToken = rows(rotated, 'capacity_provider_access_tokens').find(row => row.id === oldTokenId)!, usedAt = clock(revokedToken.last_used_at, rotationStart, rotationEnd); expect(usedAt <= rotationTime).toBe(true);
		changedRow(tokenState, rotated, 'capacity_provider_access_tokens', oldTokenId, {}, ['status', 'revoked_at', 'updated_at', 'last_used_at']); expect(revokedToken).toEqual({ ...oldTokenRow, status: 'revoked', revoked_at: rotationTime, updated_at: rotationTime, last_used_at: usedAt });
		audit(additions(tokenState, rotated, 'capacity_audit_events', 1)[0]!, 'provider-identity.rotated', 'capacity-provider', providerId, rotationKey, oldClaims.providerFingerprint, rotationTime, { previousFingerprint: oldClaims.providerFingerprint, fingerprint: newClaims.providerFingerprint, previousVersion: 1, identityVersion: 2 }); expect({ oldClaims, newClaims, rotationBody }).toEqual(rotationBefore);
		await denied(await f.post(rotationPath, z.string().parse(firstToken.accessToken), rotationBody, rotationKey), 401, 'provider_authentication_required'); expect(await read()).toEqual(rotated);
		const currentBody = { credentialId, idempotencyKey: 'enrolled-identity-token-two', requestedValiditySeconds: 60 }, currentClaims = { ...nextKey.payload, identityVersion: 2, bodySha256: sha256(canonicalJson(currentBody)), jti: randomUUID() }, currentWire = { credentialId, requestedValiditySeconds: 60, proof: nextKey.proof(currentClaims) }, currentBefore = structuredClone({ currentBody, currentClaims, currentWire });
		const postToken = (key: string, wire: typeof currentWire) => { unelapsed(); return f.app.request(new Request(`http://localhost${tokenPath}`, { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': key, authorization: `Treeseed-Credential ${credentialValue}` }, body: JSON.stringify(wire) })); };
		const currentStart = new Date().toISOString(), currentToken = record.parse(await output(await postToken(currentBody.idempotencyKey, currentWire), CONTROL_PLANE_OPERATIONS.providers.issueAccessToken)), currentEnd = new Date().toISOString(), current = await read(); tokenFootprint(rotated, current, currentToken, currentBody, currentClaims, currentStart, currentEnd, 2);
		for (const version of [1, 3]) {
			const body = { ...currentBody, idempotencyKey: `enrolled-current-key-wrong-version-${version}` }, claims = { ...currentClaims, identityVersion: version, bodySha256: sha256(canonicalJson(body)), jti: randomUUID() }, wire = { credentialId, requestedValiditySeconds: 60, proof: nextKey.proof(claims) }, beforeDenial = structuredClone({ body, claims, wire });
			// Same CURRENT key/fingerprint and genuinely signed body: not an
			// old-key signature failure disguised as a version fence.
			const deniedResponse = await postToken(body.idempotencyKey, wire); expect(deniedResponse.status).toBe(401); expect(await deniedResponse.json()).toMatchObject({ status: 401 }); expect(await read()).toEqual(current); expect({ body, claims, wire }).toEqual(beforeDenial);
		}
		const oldBody = { ...currentBody, idempotencyKey: 'enrolled-old-key-token' }, oldTokenClaims = { ...registration.inputs.payload, path: tokenPath, issuedAt: new Date().toISOString(), bodySha256: sha256(canonicalJson(oldBody)), jti: randomUUID() }, oldWire = { credentialId, requestedValiditySeconds: 60, proof: registration.inputs.proof(oldTokenClaims) }, oldBefore = structuredClone({ oldBody, oldTokenClaims, oldWire });
		await denied(await postToken(oldBody.idempotencyKey, oldWire), 401, 'provider_proof_fingerprint_mismatch'); expect(await read()).toEqual(current); expect({ oldBody, oldTokenClaims, oldWire }).toEqual(oldBefore);
		const replayStart = new Date().toISOString(), replay = await f.post(rotationPath, z.string().min(1).parse(currentToken.accessToken), rotationBody, rotationKey), replayEnd = new Date().toISOString(); expect(replay.status).toBe(200); expect(await replay.json()).toEqual(rotationEnvelope);
		const replayed = await read(), currentId = z.string().parse(currentToken.id), priorCurrent = rows(current, 'capacity_provider_access_tokens').find(row => row.id === currentId)!, usedCurrent = rows(replayed, 'capacity_provider_access_tokens').find(row => row.id === currentId)!, replayTime = clock(usedCurrent.last_used_at, replayStart, replayEnd);
		unchangedExcept(current, replayed, ['capacity_provider_access_tokens']); changedRow(current, replayed, 'capacity_provider_access_tokens', currentId, {}, ['last_used_at', 'updated_at']); expect(usedCurrent).toEqual({ ...priorCurrent, last_used_at: replayTime, updated_at: replayTime });
		expect({ oldClaims, newClaims, rotationBody }).toEqual(rotationBefore); expect({ currentBody, currentClaims, currentWire }).toEqual(currentBefore); unelapsed();
	} finally { await f.close(); }
});

it('genuine authenticated PostgreSQL enrollment exchanges its first credential issues a signed token and uses the real bearer to rotate authority with exact immutable replay and independent history', async () => {
	const f = await dependencyOperator();
	try {
		const { registration, membershipId } = await approved(f), before = await f.state(); expect(await f.state(f.right)).toEqual(before);
		expect(rows(before, 'capacity_providers').filter(row => row.id === registration.request.providerId)).toHaveLength(1);
		const identity = rows(before, 'capacity_providers').find(row => row.id === registration.request.providerId)!; expect(identity).toMatchObject({ status: 'active', identity_version: 1, fingerprint: registration.inputs.payload.providerFingerprint }); expect(JSON.parse(String(identity.public_jwk_json))).toEqual(registration.inputs.publicJwk);
		expect(rows(before, 'capacity_provider_team_memberships').filter(row => row.capacity_provider_id === registration.request.providerId)).toHaveLength(1); expect(rows(before, 'capacity_provider_registration_requests').find(row => row.id === registration.request.id)).toMatchObject({ status: 'approved', membership_id: membershipId, reviewed_by_id: 'mapped-operator' });
		const authority = rows(before, 'capacity_provider_credential_issuance_authorizations').find(row => row.membership_id === membershipId)!; expect(authority).toMatchObject({ generation: 1, status: 'pending', issued_credential_id: null });
		const exchange = exchangeStage(f, registration), exchangeStarted = new Date().toISOString(), first = await output(await exchange.post(), CONTROL_PLANE_OPERATIONS.providers.exchangeCredential), exchangeReceived = new Date().toISOString();
		const credential = z.object({ id: z.string(), credential: z.string().min(1), membershipId: z.string(), teamId: z.string(), providerId: z.string(), issuanceGeneration: z.number(), status: z.string(), scopes: z.array(z.string()) }).parse(first);
		expect({ ...credential, credential: undefined }).toMatchObject({ membershipId, teamId: 'team', providerId: registration.request.providerId, issuanceGeneration: 1, status: 'active', scopes: [...PROVIDER_MEMBERSHIP_SCOPES] });
		const exchanged = await f.state(); unchangedExcept(before, exchanged, ['capacity_provider_credential_issuance_authorizations', 'capacity_provider_team_credentials', 'capacity_provider_proof_nonces', 'capacity_audit_events']);
		changedRow(before, exchanged, 'capacity_provider_credential_issuance_authorizations', String(authority.id), { status: 'issued', issued_credential_id: credential.id }, ['status', 'issued_credential_id', 'updated_at']);
		const credentials = additions(before, exchanged, 'capacity_provider_team_credentials', 1); expect(credentials[0]).toMatchObject({ id: credential.id, membership_id: membershipId, capacity_provider_id: registration.request.providerId, team_id: 'team', issuance_authorization_id: authority.id, issuance_generation: 1, issue_idempotency_key: 'bootstrap-exchange', status: 'active', rotated_from_credential_id: null }); expect(JSON.parse(String(credentials[0]!.scopes_json))).toEqual([...PROVIDER_MEMBERSHIP_SCOPES]); expect(credentials[0]!.revealed_at).toBeTypeOf('string');
		expect(String(credentials[0]!.created_at) >= exchangeStarted && String(credentials[0]!.created_at) <= exchangeReceived && exchangeReceived < exchange.payload.expiresAt).toBe(true); expect(JSON.stringify(exchanged).includes(credential.credential)).toBe(false);
		expect(additions(before, exchanged, 'capacity_provider_proof_nonces', 1)[0]).toMatchObject({ provider_fingerprint: exchange.payload.providerFingerprint, jti: exchange.payload.jti, expires_at: exchange.payload.expiresAt });
		expect(additions(before, exchanged, 'capacity_audit_events', 1)[0]).toMatchObject({ action: 'provider-credential.issued', resource_id: credential.id, membership_id: membershipId, actor_type: 'provider-identity', actor_id: exchange.payload.providerFingerprint, idempotency_key: 'bootstrap-exchange' }); expect(await f.state(f.right)).toEqual(exchanged);
		await denied(await exchange.post(), 409, 'provider_proof_replayed'); expect(await f.state()).toEqual(exchanged);
		const replay = await output(await exchange.post(true), CONTROL_PLANE_OPERATIONS.providers.exchangeCredential); expect(replay.credential === credential.credential).toBe(true); expect({ ...replay, credential: undefined }).toEqual({ ...first, credential: undefined });
		const exchangeReplay = await f.state(); unchangedExcept(exchanged, exchangeReplay, ['capacity_provider_proof_nonces']); additions(exchanged, exchangeReplay, 'capacity_provider_proof_nonces', 1); exchange.unchanged();
		const tokenBody = { credentialId: credential.id, idempotencyKey: 'bootstrap-token', requestedValiditySeconds: 60 }, tokenStage = stage(f, registration, restPath(CONTROL_PLANE_OPERATIONS.providers.issueAccessToken.descriptor.rest), tokenBody, { credentialId: credential.id, requestedValiditySeconds: 60 }, `Treeseed-Credential ${credential.credential}`);
		const start = new Date().toISOString(), issued = await output(await tokenStage.post(), CONTROL_PLANE_OPERATIONS.providers.issueAccessToken), received = new Date().toISOString();
		const token = z.object({ id: z.string(), accessToken: z.string().min(1), membershipId: z.string(), credentialId: z.string(), teamId: z.string(), providerId: z.string(), identityVersion: z.number(), scopes: z.array(z.string()), issuedAt: z.string(), expiresAt: z.string(), status: z.string() }).parse(issued);
		expect({ ...token, accessToken: undefined }).toMatchObject({ membershipId, credentialId: credential.id, teamId: 'team', providerId: registration.request.providerId, identityVersion: 1, scopes: [...PROVIDER_MEMBERSHIP_SCOPES], status: 'active' }); expect(token.issuedAt >= start && token.issuedAt <= received).toBe(true); expect(Date.parse(token.expiresAt) - Date.parse(token.issuedAt)).toBe(60000);
		const tokenState = await f.state(); unchangedExcept(exchangeReplay, tokenState, ['capacity_provider_access_tokens', 'capacity_provider_proof_nonces', 'capacity_audit_events']); expect(additions(exchangeReplay, tokenState, 'capacity_provider_access_tokens', 1)[0]).toMatchObject({ id: token.id, credential_id: credential.id, membership_id: membershipId, status: 'active', issued_at: token.issuedAt, expires_at: token.expiresAt, idempotency_key: 'bootstrap-token' }); additions(exchangeReplay, tokenState, 'capacity_provider_proof_nonces', 1); expect(additions(exchangeReplay, tokenState, 'capacity_audit_events', 1)[0]).toMatchObject({ action: 'provider-access-token.issued', resource_id: token.id, membership_id: membershipId, idempotency_key: 'bootstrap-token' }); expect(await f.state(f.right)).toEqual(tokenState);
		expect(JSON.stringify(tokenState).includes(token.accessToken)).toBe(false); expect(received < tokenStage.payload.expiresAt).toBe(true);
		await denied(await tokenStage.post(), 409, 'provider_proof_replayed'); expect(await f.state()).toEqual(tokenState);
		const tokenReplay = await output(await tokenStage.post(true), CONTROL_PLANE_OPERATIONS.providers.issueAccessToken); expect(tokenReplay.accessToken === token.accessToken).toBe(true); expect({ ...tokenReplay, accessToken: undefined }).toEqual({ ...issued, accessToken: undefined });
		const replayed = await f.state(); unchangedExcept(tokenState, replayed, ['capacity_provider_proof_nonces']); additions(tokenState, replayed, 'capacity_provider_proof_nonces', 1); tokenStage.unchanged();
		const rotationPath = restPath(CONTROL_PLANE_OPERATIONS.providers.rotateCredential.descriptor.rest), rotation = await f.post(rotationPath, token.accessToken, {}, 'bootstrap-rotation'); expect(rotation.status).toBe(200);
		const rotated = await f.state(); unchangedExcept(replayed, rotated, ['capacity_provider_credential_issuance_authorizations', 'capacity_provider_team_credentials', 'capacity_provider_access_tokens', 'capacity_audit_events']);
		expect(additions(replayed, rotated, 'capacity_provider_credential_issuance_authorizations', 1)[0]).toMatchObject({ membership_id: membershipId, capacity_provider_id: registration.request.providerId, generation: 2, status: 'pending', issued_credential_id: null, created_by_type: 'provider-identity', created_by_id: registration.request.providerId, idempotency_key: 'bootstrap-rotation' });
		changedRow(replayed, rotated, 'capacity_provider_team_credentials', credential.id, { status: 'revoked' }, ['status', 'revoked_at', 'updated_at']); changedRow(replayed, rotated, 'capacity_provider_access_tokens', token.id, { status: 'revoked' }, ['status', 'revoked_at', 'updated_at', 'last_used_at']);
		const savedToken = rows(rotated, 'capacity_provider_access_tokens').find(row => row.id === token.id)!; expect(savedToken.last_used_at).toBeTypeOf('string'); expect(savedToken.revoked_at).toBeTypeOf('string'); expect(rows(rotated, 'capacity_provider_team_credentials').find(row => row.id === credential.id)!.revoked_at).toBeTypeOf('string'); expect(additions(replayed, rotated, 'capacity_audit_events', 1)[0]).toMatchObject({ action: 'provider-credential.rotation-authorized', actor_type: 'provider-identity', actor_id: registration.request.providerId, membership_id: membershipId, idempotency_key: 'bootstrap-rotation' }); expect(await f.state(f.right)).toEqual(rotated);
		await denied(await f.post(rotationPath, token.accessToken, {}, 'bootstrap-rotation'), 401, 'provider_authentication_required'); expect(await f.state()).toEqual(rotated); expect(await f.state(f.right)).toEqual(rotated);
	} finally { await f.close(); }
});

it('genuine enrolled PostgreSQL credential insertion failure rolls back original authorization and credential together retains the consumed proof and admits only a fresh nonce retry within the same stage expiry', async () => {
	const f = await dependencyOperator();
	try {
		const { registration, membershipId } = await approved(f), before = await f.state();
		// Failure injection lives ONLY in the same fresh disposable database.
		await f.left.pool.query("CREATE FUNCTION bootstrap_credential_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'native bootstrap credential interruption' USING ERRCODE='P0001'; END $$");
		await f.left.pool.query('CREATE TRIGGER bootstrap_credential_failure BEFORE INSERT ON capacity_provider_team_credentials FOR EACH ROW EXECUTE FUNCTION bootstrap_credential_failure()');
		const exchange = exchangeStage(f, registration), failed = await exchange.post(); expect(failed.status).toBe(500);
		const failure = await f.state(); unchangedExcept(before, failure, ['capacity_provider_proof_nonces']); expect(additions(before, failure, 'capacity_provider_proof_nonces', 1)[0]).toMatchObject({ jti: exchange.payload.jti, provider_fingerprint: exchange.payload.providerFingerprint }); expect(await f.state(f.right)).toEqual(failure);
		expect(rows(failure, 'capacity_provider_credential_issuance_authorizations').find(row => row.membership_id === membershipId)).toMatchObject({ generation: 1, status: 'pending', issued_credential_id: null });
		await f.left.pool.query('DROP TRIGGER bootstrap_credential_failure ON capacity_provider_team_credentials'); await f.left.pool.query('DROP FUNCTION bootstrap_credential_failure()');
		expect((await f.right.pool.query("SELECT tgname FROM pg_trigger WHERE tgname='bootstrap_credential_failure'")).rows).toEqual([]); expect((await f.right.pool.query("SELECT proname FROM pg_proc WHERE proname='bootstrap_credential_failure' AND pronamespace='public'::regnamespace")).rows).toEqual([]);
		await denied(await exchange.post(), 409, 'provider_proof_replayed'); expect(await f.state()).toEqual(failure);
		const result = await output(await exchange.post(true), CONTROL_PLANE_OPERATIONS.providers.exchangeCredential), credentialId = z.string().parse(result.id), after = await f.state();
		unchangedExcept(failure, after, ['capacity_provider_credential_issuance_authorizations', 'capacity_provider_team_credentials', 'capacity_provider_proof_nonces', 'capacity_audit_events']); additions(failure, after, 'capacity_provider_proof_nonces', 1);
		const authorization = rows(failure, 'capacity_provider_credential_issuance_authorizations').find(row => row.membership_id === membershipId)!;
		changedRow(failure, after, 'capacity_provider_credential_issuance_authorizations', String(authorization.id), { status: 'issued', issued_credential_id: credentialId }, ['status', 'issued_credential_id', 'updated_at']);
		expect(additions(failure, after, 'capacity_provider_team_credentials', 1)[0]).toMatchObject({ id: credentialId, membership_id: membershipId, issuance_authorization_id: authorization.id, issuance_generation: 1, status: 'active' }); expect(additions(failure, after, 'capacity_audit_events', 1)[0]).toMatchObject({ action: 'provider-credential.issued', resource_id: credentialId, idempotency_key: 'bootstrap-exchange' }); expect(await f.state(f.right)).toEqual(after); exchange.unchanged();
	} finally { await f.close(); }
});

it('genuine enrolled PostgreSQL overlapping first exchanges share one credential authorization and audit with two independently blocked native transactions and exact replay history', async () => {
	const f = await dependencyOperator(); let holder: PoolClient | undefined; const pending: Promise<Response>[] = [], settled: boolean[] = [];
	try {
		const { registration, membershipId } = await approved(f), before = await f.state();
		const authority = rows(before, 'capacity_provider_credential_issuance_authorizations').find(row => row.membership_id === membershipId)!; expect(authority).toMatchObject({ generation: 1, status: 'pending', issued_credential_id: null });
		// ONLY fresh-DB transaction locks and trigger; no service/query/SQL mock,
		// supplied enrollment row, other database, server signal or new runner.
		await f.left.pool.query('CREATE FUNCTION bootstrap_exchange_barrier() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN PERFORM pg_advisory_xact_lock(393,239); RETURN NEW; END $$');
		await f.left.pool.query("CREATE TRIGGER bootstrap_exchange_barrier BEFORE UPDATE ON capacity_provider_credential_issuance_authorizations FOR EACH ROW WHEN (OLD.status='pending' AND NEW.status='issued') EXECUTE FUNCTION bootstrap_exchange_barrier()");
		holder = await f.right.pool.connect(); const owned = await holder.query<{ name: string; pid: number }>('SELECT current_database() AS name, pg_backend_pid() AS pid'); expect(owned.rows).toHaveLength(1); const held = owned.rows[0]!; expect(held.name).toBe(f.name); expect(Number.isSafeInteger(held.pid) && held.pid > 0).toBe(true);
		await holder.query('BEGIN'); await holder.query('SELECT pg_advisory_xact_lock(393,239)');
		const exchange = exchangeStage(f, registration);
		for (const fresh of [false, true]) { const index = pending.length, promise = Promise.resolve(exchange.post(fresh)); settled.push(false); pending.push(promise); void promise.then(() => { settled[index] = true; }, () => { settled[index] = true; }); }
		let observed: Array<{ pid: number; blockers: number[] }> = [];
		await eventObserved(async () => {
			assert.ok(Date.now() < Date.parse(exchange.payload.expiresAt), 'Original exchange expiry elapsed before native overlap observation');
			observed = (await f.right.pool.query<{ pid: number; blockers: number[] }>("SELECT pid, pg_blocking_pids(pid) AS blockers FROM pg_stat_activity WHERE datname=current_database() AND backend_type='client backend' AND wait_event_type='Lock' AND query LIKE '%UPDATE capacity_provider_credential_issuance_authorizations%' ORDER BY pid")).rows;
			const first = observed.find(row => row.blockers.includes(held.pid)); return observed.length === 2 && Boolean(first && observed.some(row => row.pid !== first.pid && row.blockers.includes(first.pid)));
		});
		expect(new Set(observed.map(row => row.pid)).size).toBe(2); for (const row of observed) expect(Number.isSafeInteger(row.pid) && row.pid > 0 && row.pid !== held.pid).toBe(true);
		const firstBlocked = observed.find(row => row.blockers.includes(held.pid))!; expect(firstBlocked.blockers).toEqual([held.pid]); expect(observed.find(row => row.pid !== firstBlocked.pid)!.blockers).toEqual([firstBlocked.pid]); expect(settled).toEqual([false, false]);
		const blocked = await f.state(); unchangedExcept(before, blocked, ['capacity_provider_proof_nonces']); const nonces = additions(before, blocked, 'capacity_provider_proof_nonces', 2); expect(nonces.map(row => row.jti)).toContain(exchange.payload.jti); expect(new Set(nonces.map(row => row.jti)).size).toBe(2); for (const nonce of nonces) expect(nonce).toMatchObject({ provider_fingerprint: exchange.payload.providerFingerprint, expires_at: exchange.payload.expiresAt }); expect(await f.state(f.right)).toEqual(blocked);
		await holder.query('ROLLBACK'); holder.release(); holder = undefined;
		// Await ORIGINAL promises; a losing 500/409/rejection is never relabeled
		// an idempotent success. The desired same-key contract requires BOTH200.
		const responses = await Promise.all(pending), outputs = await Promise.all(responses.map(response => output(response, CONTROL_PLANE_OPERATIONS.providers.exchangeCredential)));
		const credentialValue = z.string().min(1).parse(outputs[0]!.credential); expect(credentialValue === outputs[1]!.credential).toBe(true); expect({ ...outputs[0], credential: undefined }).toEqual({ ...outputs[1], credential: undefined }); expect({ ...outputs[0], credential: undefined }).toMatchObject({ membershipId, teamId: 'team', providerId: registration.request.providerId, issuanceGeneration: 1, status: 'active', scopes: [...PROVIDER_MEMBERSHIP_SCOPES] });
		const credentialId = z.string().parse(outputs[0]!.id), after = await f.state(); unchangedExcept(blocked, after, ['capacity_provider_credential_issuance_authorizations', 'capacity_provider_team_credentials', 'capacity_audit_events']);
		changedRow(blocked, after, 'capacity_provider_credential_issuance_authorizations', String(authority.id), { status: 'issued', issued_credential_id: credentialId }, ['status', 'issued_credential_id', 'updated_at']);
		expect(additions(blocked, after, 'capacity_provider_team_credentials', 1)[0]).toMatchObject({ id: credentialId, membership_id: membershipId, capacity_provider_id: registration.request.providerId, issuance_authorization_id: authority.id, issuance_generation: 1, issue_idempotency_key: 'bootstrap-exchange', status: 'active' }); expect(additions(blocked, after, 'capacity_audit_events', 1)[0]).toMatchObject({ action: 'provider-credential.issued', resource_id: credentialId, request_id: registration.request.id, membership_id: membershipId, idempotency_key: 'bootstrap-exchange' }); expect(await f.state(f.right)).toEqual(after);
		expect(JSON.stringify(after).includes(credentialValue)).toBe(false);
		expect((await f.right.pool.query("SELECT pid FROM pg_locks WHERE locktype='advisory' AND database=(SELECT oid FROM pg_database WHERE datname=current_database()) AND classid=393 AND objid=239 AND objsubid=2")).rows).toEqual([]);
		await f.left.pool.query('DROP TRIGGER bootstrap_exchange_barrier ON capacity_provider_credential_issuance_authorizations'); await f.left.pool.query('DROP FUNCTION bootstrap_exchange_barrier()');
		expect((await f.right.pool.query("SELECT tgname FROM pg_trigger WHERE tgname='bootstrap_exchange_barrier'")).rows).toEqual([]); expect((await f.right.pool.query("SELECT proname FROM pg_proc WHERE proname='bootstrap_exchange_barrier' AND pronamespace='public'::regnamespace")).rows).toEqual([]);
		await denied(await exchange.post(), 409, 'provider_proof_replayed'); expect(await f.state()).toEqual(after);
		const replay = await output(await exchange.post(true), CONTROL_PLANE_OPERATIONS.providers.exchangeCredential); expect(replay.credential === outputs[0]!.credential).toBe(true); expect({ ...replay, credential: undefined }).toEqual({ ...outputs[0], credential: undefined });
		const replayed = await f.state(); unchangedExcept(after, replayed, ['capacity_provider_proof_nonces']); additions(after, replayed, 'capacity_provider_proof_nonces', 1); expect(await f.state(f.right)).toEqual(replayed); exchange.unchanged();
	} finally {
		try { if (holder) await holder.query('ROLLBACK'); await eventObserved(() => settled.every(Boolean)); await Promise.allSettled(pending); }
		finally { try { holder?.release(); } finally { await f.close(); } }
	}
});

it('genuine enrolled PostgreSQL late credential audit failure retains issued authority and secret custody then fresh nonce replay recovers one missing audit without hiding the failed footprint', async () => {
	const f = await dependencyOperator();
	try {
		const { registration, membershipId } = await approved(f), before = await f.state(), authority = rows(before, 'capacity_provider_credential_issuance_authorizations').find(row => row.membership_id === membershipId)!;
		await f.left.pool.query("CREATE FUNCTION bootstrap_credential_audit_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'native bootstrap credential audit interruption' USING ERRCODE='P0001'; END $$");
		await f.left.pool.query("CREATE TRIGGER bootstrap_credential_audit_failure BEFORE INSERT ON capacity_audit_events FOR EACH ROW WHEN (NEW.action='provider-credential.issued') EXECUTE FUNCTION bootstrap_credential_audit_failure()");
		const exchange = exchangeStage(f, registration), failed = await exchange.post(); expect(failed.status).toBe(500);
		const failure = await f.state(); unchangedExcept(before, failure, ['capacity_provider_credential_issuance_authorizations', 'capacity_provider_team_credentials', 'capacity_provider_proof_nonces']);
		const credential = additions(before, failure, 'capacity_provider_team_credentials', 1)[0]!; expect(credential).toMatchObject({ membership_id: membershipId, issuance_authorization_id: authority.id, issuance_generation: 1, status: 'active', issue_idempotency_key: 'bootstrap-exchange' }); expect(credential.revealed_at).toBeTypeOf('string'); const credentialId = z.string().parse(credential.id);
		changedRow(before, failure, 'capacity_provider_credential_issuance_authorizations', String(authority.id), { status: 'issued', issued_credential_id: credentialId }, ['status', 'issued_credential_id', 'updated_at']); expect(additions(before, failure, 'capacity_provider_proof_nonces', 1)[0]).toMatchObject({ jti: exchange.payload.jti, expires_at: exchange.payload.expiresAt, provider_fingerprint: exchange.payload.providerFingerprint }); expect(await f.state(f.right)).toEqual(failure);
		await f.left.pool.query('DROP TRIGGER bootstrap_credential_audit_failure ON capacity_audit_events'); await f.left.pool.query('DROP FUNCTION bootstrap_credential_audit_failure()');
		expect((await f.right.pool.query("SELECT tgname FROM pg_trigger WHERE tgname='bootstrap_credential_audit_failure'")).rows).toEqual([]); expect((await f.right.pool.query("SELECT proname FROM pg_proc WHERE proname='bootstrap_credential_audit_failure' AND pronamespace='public'::regnamespace")).rows).toEqual([]);
		await denied(await exchange.post(), 409, 'provider_proof_replayed'); expect(await f.state()).toEqual(failure);
		const replay = await output(await exchange.post(true), CONTROL_PLANE_OPERATIONS.providers.exchangeCredential); expect(replay.id).toBe(credentialId); expect({ ...replay, credential: undefined }).toMatchObject({ membershipId, teamId: 'team', providerId: registration.request.providerId, issuanceGeneration: 1, status: 'active', scopes: [...PROVIDER_MEMBERSHIP_SCOPES] }); const credentialValue = z.string().min(1).parse(replay.credential);
		const recovered = await f.state(); unchangedExcept(failure, recovered, ['capacity_provider_proof_nonces', 'capacity_audit_events']); additions(failure, recovered, 'capacity_provider_proof_nonces', 1); expect(additions(failure, recovered, 'capacity_audit_events', 1)[0]).toMatchObject({ action: 'provider-credential.issued', actor_type: 'provider-identity', actor_id: exchange.payload.providerFingerprint, resource_type: 'provider-team-credential', resource_id: credentialId, request_id: registration.request.id, membership_id: membershipId, idempotency_key: 'bootstrap-exchange' }); expect(await f.state(f.right)).toEqual(recovered); expect(JSON.stringify(recovered).includes(credentialValue)).toBe(false);
		const repeated = await output(await exchange.post(true), CONTROL_PLANE_OPERATIONS.providers.exchangeCredential); expect(repeated.credential === credentialValue).toBe(true); expect({ ...repeated, credential: undefined }).toEqual({ ...replay, credential: undefined });
		const repeatedState = await f.state(); unchangedExcept(recovered, repeatedState, ['capacity_provider_proof_nonces']); additions(recovered, repeatedState, 'capacity_provider_proof_nonces', 1); expect(await f.state(f.right)).toEqual(repeatedState); exchange.unchanged();
	} finally { await f.close(); }
});
