import { installAuthenticationAccountProfileAndNotificationsRoutes } from "../routes/accounts/authentication-account-profile-and-notifications.ts";
import { installAuthenticationDeviceSignupAndOauthRoutes } from "../routes/accounts/authentication-device-signup-and-oauth.ts";
import { installAuthenticationPasswordAndAccountSecurityRoutes } from "../routes/accounts/authentication-password-and-account-security.ts";
import { installFoundationUsersByUsernameItemProfileRoutes } from "../routes/accounts/foundation-users-by-username-item-profile.ts";
import { installFeedbackAdministrationRoutes } from "../routes/feedback/administration.ts";
import { installFeedbackSubmissionRoutes } from "../routes/feedback/submission.ts";
import { installDiscussionRoutes } from "../routes/discussions/discussions.ts";
import { installSessionEventRoutes } from "../routes/realtime/session-events.ts";
import { installClientActionRoutes } from "../routes/realtime/client-actions.ts";
import { installGovernanceCommonsProposalsQuestionsAndVotesRoutes } from "../routes/governance/commons/governance-commons-proposals-questions-and-votes.ts";
import { installGovernanceCommonsReviewsDecisionsAndDelegationsRoutes } from "../routes/governance/commons/governance-commons-reviews-decisions-and-delegations.ts";
import { installKnowledgeAuthoringRoutes } from "../routes/knowledge/authoring.ts";
import { installKnowledgePackRoutes } from "../routes/knowledge/packs.ts";
import { installKnowledgePublicationRoutes } from "../routes/knowledge/publication.ts";
import { installKnowledgeLifecycleRoutes } from "../routes/knowledge/lifecycle.ts";
import { installOperationsPlatformRunnersAndJobsRoutes } from "../routes/operations/operations-platform-runners-and-jobs.ts";
import { installGovernanceProjectsItemApprovalsItemDecisionRoutes } from "../routes/projects/governance/governance-projects-item-approvals-item-decision.ts";
import { installGovernanceTeamProjectDelegationsAndApprovalsRoutes } from "../routes/projects/governance/governance-team-project-delegations-and-approvals.ts";
import { installGovernanceTeamProjectPolicyRoutes } from "../routes/projects/governance/governance-team-project-policy.ts";
import { installProjectsProposalsAndDecisionsRoutes } from "../routes/projects/governance/projects-proposals-and-decisions.ts";
import { installOperationsProjectJobsRoutes } from "../routes/projects/operations/operations-project-jobs.ts";
import { installProjectsSettingsAndSummariesRoutes } from "../routes/projects/projects-settings-and-summaries.ts";
import { installProjectsRepositoryTopologyRoutes } from "../routes/projects/repositories/projects-repository-topology.ts";
import { installProjectWorkflowOperationRoutes } from "../routes/projects/operations/workflow-operations.ts";
import { installProjectWorkflowConfigurationRoutes } from "../routes/projects/operations/workflow-configuration.ts";
import { installGitHubConnectorRoutes } from "../routes/providers/github-connectors.ts";
import { installGitHubWebhookRoutes } from "../routes/providers/github-webhooks.ts";
import { installSeedResourceResolutionRoutes } from "../routes/seeds/seed-resource-resolution.ts";
import { installSeedRunLifecycleRoutes } from "../routes/seeds/seed-run-lifecycle.ts";
import { installContextualKnowledgeRoutes } from "../routes/support/contextual-knowledge.ts";
import { installFoundationApprovalDecisionsRoutes } from "../routes/support/foundation-approval-decisions.ts";
import { installFoundationHealthAndControlPlaneRoutes } from "../routes/support/foundation-health-and-control-plane.ts";
import { installFoundationStewardTransitionCommonsProposalRoutes } from "../routes/support/foundation-stewardTransitionCommonsProposal.ts";
import { installTeamServicesRoutes } from "../routes/teams/team-services.ts";
import { installTeamServiceAuthorityRoutes } from "../routes/teams/team-service-authorities.ts";
import { installTeamsInvitationsMembershipAndApiKeysRoutes } from "../routes/teams/teams-invitations-membership-and-api-keys.ts";
import { installTeamsStorageAndContentPreviewsRoutes } from "../routes/teams/teams-storage-and-content-previews.ts";
import { installTreedxCredentialsMirrorsAndSharesRoutes } from "../routes/treedx/repositories/treedx-credentials-mirrors-and-shares.ts";
import { installTreedxInternalTreedxPublicFederationStatusRoutes } from "../routes/treedx/repositories/treedx-internal-treedx-public-federation-status.ts";
import { installTreedxTeamServiceAndPublicFederationRoutes } from "../routes/treedx/repositories/treedx-team-service-and-public-federation.ts";

export function installPlatformRoutes(context: any): void {
  installFoundationHealthAndControlPlaneRoutes(context);
  installFeedbackSubmissionRoutes(context);
  installDiscussionRoutes(context);
  installSessionEventRoutes(context);
  installClientActionRoutes(context);
  installFeedbackAdministrationRoutes(context);
  installContextualKnowledgeRoutes(context);
  installKnowledgeAuthoringRoutes(context);
  installKnowledgePackRoutes(context);
  installKnowledgePublicationRoutes(context);
  installKnowledgeLifecycleRoutes(context);
  installSeedResourceResolutionRoutes(context);
  installSeedRunLifecycleRoutes(context);
  installOperationsPlatformRunnersAndJobsRoutes(context);
  installAuthenticationDeviceSignupAndOauthRoutes(context);
  installAuthenticationAccountProfileAndNotificationsRoutes(context);
  installAuthenticationPasswordAndAccountSecurityRoutes(context);
  installFoundationUsersByUsernameItemProfileRoutes(context);
  installTeamsInvitationsMembershipAndApiKeysRoutes(context);
  installTreedxTeamServiceAndPublicFederationRoutes(context);
  installTreedxInternalTreedxPublicFederationStatusRoutes(context);
  installTreedxCredentialsMirrorsAndSharesRoutes(context);
  installTeamServicesRoutes(context);
  installTeamServiceAuthorityRoutes(context);
  installProjectsRepositoryTopologyRoutes(context);
  installProjectWorkflowOperationRoutes(context);
  installProjectWorkflowConfigurationRoutes(context);
  installGitHubConnectorRoutes(context);
  installGitHubWebhookRoutes(context);
  installProjectsSettingsAndSummariesRoutes(context);
  installGovernanceTeamProjectPolicyRoutes(context);
  installProjectsProposalsAndDecisionsRoutes(context);
  installGovernanceTeamProjectDelegationsAndApprovalsRoutes(context);
  installGovernanceProjectsItemApprovalsItemDecisionRoutes(context);
  installOperationsProjectJobsRoutes(context);
  installFoundationApprovalDecisionsRoutes(context);
  installGovernanceCommonsProposalsQuestionsAndVotesRoutes(context);
  installFoundationStewardTransitionCommonsProposalRoutes(context);
  installGovernanceCommonsReviewsDecisionsAndDelegationsRoutes(context);
  installTeamsStorageAndContentPreviewsRoutes(context);
}
