import { installAuthenticationAccountProfileAndNotificationsRoutes } from "../routes/accounts/authentication-account-profile-and-notifications.ts";
import { installAuthenticationDeviceSignupAndOauthRoutes } from "../routes/accounts/authentication-device-signup-and-oauth.ts";
import { installAuthenticationPasswordAndAccountSecurityRoutes } from "../routes/accounts/authentication-password-and-account-security.ts";
import { installFoundationUsersByUsernameItemProfileRoutes } from "../routes/accounts/foundation-users-by-username-item-profile.ts";
import { installProjectionsInfrastructureKnowledgeAndWorkdaysRoutes } from "../routes/capacity/workdays/projections-infrastructure-knowledge-and-workdays.ts";
import { installCommerceProductGovernanceAndCapacityListingsRoutes } from "../routes/commerce/capacity/commerce-product-governance-and-capacity-listings.ts";
import { installCatalogSeedRunLifecycleRoutes } from "../routes/commerce/catalog/catalog-seed-run-lifecycle.ts";
import { installCatalogTemplateRoutes } from "../routes/commerce/catalog/catalog-templates.ts";
import { installCommerceCapacityInquiriesProductVersionsAndOffersRoutes } from "../routes/commerce/catalog/commerce-capacity-inquiries-product-versions-and-offers.ts";
import { installCommerceStripePriceReconciliationAndGovernanceEventsRoutes } from "../routes/commerce/catalog/commerce-stripe-price-reconciliation-and-governance-events.ts";
import { installTeamsTeamsItemCatalogItemsRoutes } from "../routes/commerce/catalog/teams-teams-item-catalog-items.ts";
import { installCatalogCatalogItemArtifactsRoutes } from "../routes/commerce/orders/catalog-catalog-item-artifacts.ts";
import { installCatalogItemsAndArtifactsRoutes } from "../routes/commerce/orders/catalog-items-and-artifacts.ts";
import { installCommerceSalesFulfillmentAndProductCatalogRoutes } from "../routes/commerce/orders/commerce-sales-fulfillment-and-product-catalog.ts";
import { installCommerceServiceRequestsContractsAndOrdersRoutes } from "../routes/commerce/services/commerce-service-requests-contracts-and-orders.ts";
import { installCommerceVendorOnboardingStripeAndCheckoutRoutes } from "../routes/commerce/vendors/commerce-vendor-onboarding-stripe-and-checkout.ts";
import { installFeedbackAdministrationRoutes } from "../routes/feedback/administration.ts";
import { installFeedbackSubmissionRoutes } from "../routes/feedback/submission.ts";
import { installDiscussionRoutes } from "../routes/discussions/discussions.ts";
import { installGovernanceCommonsProposalsQuestionsAndVotesRoutes } from "../routes/governance/commons/governance-commons-proposals-questions-and-votes.ts";
import { installGovernanceCommonsReviewsDecisionsAndDelegationsRoutes } from "../routes/governance/commons/governance-commons-reviews-decisions-and-delegations.ts";
import { installKnowledgeAuthoringRoutes } from "../routes/knowledge/authoring.ts";
import { installKnowledgePackRoutes } from "../routes/knowledge/packs.ts";
import { installKnowledgePublicationRoutes } from "../routes/knowledge/publication.ts";
import { installKnowledgeLifecycleRoutes } from "../routes/knowledge/lifecycle.ts";
import { installOperationsPlatformRunnersAndJobsRoutes } from "../routes/operations/operations-platform-runners-and-jobs.ts";
import { installGovernanceProjectionRoutes } from "../routes/projects/governance/governance-projection.ts";
import { installGovernanceProjectsItemApprovalsItemDecisionRoutes } from "../routes/projects/governance/governance-projects-item-approvals-item-decision.ts";
import { installGovernanceTeamProjectDelegationsAndApprovalsRoutes } from "../routes/projects/governance/governance-team-project-delegations-and-approvals.ts";
import { installGovernanceTeamProjectPolicyRoutes } from "../routes/projects/governance/governance-team-project-policy.ts";
import { installProjectsProposalsAndDecisionsRoutes } from "../routes/projects/governance/projects-proposals-and-decisions.ts";
import { installOperationsProjectJobsRoutes } from "../routes/projects/operations/operations-project-jobs.ts";
import { installProjectsCollectionRoutes } from "../routes/projects/projects-collection.ts";
import { installProjectsSettingsAndSummariesRoutes } from "../routes/projects/projects-settings-and-summaries.ts";
import { installProjectsRepositoryTopologyRoutes } from "../routes/projects/repositories/projects-repository-topology.ts";
import { installProjectWorkflowOperationRoutes } from "../routes/projects/operations/workflow-operations.ts";
import { installProjectWorkflowConfigurationRoutes } from "../routes/projects/operations/workflow-configuration.ts";
import { installGitHubConnectorRoutes } from "../routes/providers/github-connectors.ts";
import { installGitHubWebhookRoutes } from "../routes/providers/github-webhooks.ts";
import { installFoundationAcceptanceSeedRoutes } from "../routes/seeds/foundation-acceptance-seed.ts";
import { installContextualKnowledgeRoutes } from "../routes/support/contextual-knowledge.ts";
import { installFoundationApprovalDecisionsRoutes } from "../routes/support/foundation-approval-decisions.ts";
import { installFoundationCurrentUserMarketsRoutes } from "../routes/support/foundation-current-user-markets.ts";
import { installFoundationHealthAndMarketRoutes } from "../routes/support/foundation-health-and-market.ts";
import { installFoundationStewardTransitionCommonsProposalRoutes } from "../routes/support/foundation-stewardTransitionCommonsProposal.ts";
import { installTeamServicesRoutes } from "../routes/teams/team-services.ts";
import { installTeamServiceAuthorityRoutes } from "../routes/teams/team-service-authorities.ts";
import { installTeamsDirectoryRoutes } from "../routes/teams/teams-directory.ts";
import { installTeamsInvitationsMembershipAndApiKeysRoutes } from "../routes/teams/teams-invitations-membership-and-api-keys.ts";
import { installTeamsLifecycleAndConsentRoutes } from "../routes/teams/teams-lifecycle-and-consent.ts";
import { installTeamsStorageAndContentPreviewsRoutes } from "../routes/teams/teams-storage-and-content-previews.ts";
import { installTreedxCredentialsMirrorsAndSharesRoutes } from "../routes/treedx/repositories/treedx-credentials-mirrors-and-shares.ts";
import { installTreedxInternalTreedxPublicFederationStatusRoutes } from "../routes/treedx/repositories/treedx-internal-treedx-public-federation-status.ts";
import { installTreedxTeamServiceAndPublicFederationRoutes } from "../routes/treedx/repositories/treedx-team-service-and-public-federation.ts";

export function installPlatformRoutes(context: any): void {
  installFoundationHealthAndMarketRoutes(context);
  installFeedbackSubmissionRoutes(context);
  installDiscussionRoutes(context);
  installFeedbackAdministrationRoutes(context);
  installContextualKnowledgeRoutes(context);
  installKnowledgeAuthoringRoutes(context);
  installKnowledgePackRoutes(context);
  installKnowledgePublicationRoutes(context);
  installKnowledgeLifecycleRoutes(context);
  installFoundationAcceptanceSeedRoutes(context);
  installOperationsPlatformRunnersAndJobsRoutes(context);
  installAuthenticationDeviceSignupAndOauthRoutes(context);
  installAuthenticationAccountProfileAndNotificationsRoutes(context);
  installAuthenticationPasswordAndAccountSecurityRoutes(context);
  installFoundationCurrentUserMarketsRoutes(context);
  installGovernanceProjectionRoutes(context);
  installProjectionsInfrastructureKnowledgeAndWorkdaysRoutes(context);
  installTeamsDirectoryRoutes(context);
  installFoundationUsersByUsernameItemProfileRoutes(context);
  installCatalogSeedRunLifecycleRoutes(context);
  installTeamsInvitationsMembershipAndApiKeysRoutes(context);
  installTeamsLifecycleAndConsentRoutes(context);
  installTreedxTeamServiceAndPublicFederationRoutes(context);
  installTreedxInternalTreedxPublicFederationStatusRoutes(context);
  installTreedxCredentialsMirrorsAndSharesRoutes(context);
  installTeamServicesRoutes(context);
  installTeamServiceAuthorityRoutes(context);
  installProjectsCollectionRoutes(context);
  installProjectsRepositoryTopologyRoutes(context);
  installProjectWorkflowOperationRoutes(context);
  installProjectWorkflowConfigurationRoutes(context);
  installGitHubConnectorRoutes(context);
  installGitHubWebhookRoutes(context);
  installProjectsSettingsAndSummariesRoutes(context);
  installGovernanceTeamProjectPolicyRoutes(context);
  installProjectsProposalsAndDecisionsRoutes(context);
  installGovernanceTeamProjectDelegationsAndApprovalsRoutes(context);
  installGovernanceProjectsItemApprovalsItemDecisionRoutes(context);
  installOperationsProjectJobsRoutes(context);
  installFoundationApprovalDecisionsRoutes(context);
  installGovernanceCommonsProposalsQuestionsAndVotesRoutes(context);
  installFoundationStewardTransitionCommonsProposalRoutes(context);
  installGovernanceCommonsReviewsDecisionsAndDelegationsRoutes(context);
  installCommerceVendorOnboardingStripeAndCheckoutRoutes(context);
  installCommerceServiceRequestsContractsAndOrdersRoutes(context);
  installCommerceSalesFulfillmentAndProductCatalogRoutes(context);
  installCommerceProductGovernanceAndCapacityListingsRoutes(context);
  installCommerceCapacityInquiriesProductVersionsAndOffersRoutes(context);
  installCommerceStripePriceReconciliationAndGovernanceEventsRoutes(context);
  installCatalogItemsAndArtifactsRoutes(context);
  installTeamsTeamsItemCatalogItemsRoutes(context);
  installCatalogCatalogItemArtifactsRoutes(context);
  installTeamsStorageAndContentPreviewsRoutes(context);
  installCatalogTemplateRoutes(context);
}
