import { createHash } from 'node:crypto';
import type { AgentLabOverview } from '@treeseed/sdk/agent-capacity';
import type { GovernanceProposalReadiness } from '@treeseed/sdk';
import type { AgentLabProjectionRow as Row, AgentLabSourceRows } from './agent-lab-projection-service.ts';
import { commandPrimaryView } from './command-primary-view.ts';

interface Store { all(query: string, values?: unknown[]): Promise<Row[]>; first(query: string, values?: unknown[]): Promise<Row | null>; governanceProposalReadiness(id: string): Promise<GovernanceProposalReadiness | null> }
interface Snapshot { overview: AgentLabOverview; rows: AgentLabSourceRows; artifacts: Row[] }
type Surface = 'inbox' | 'decisions' | 'build' | 'direction' | 'results' | 'find';
type Kind = 'proposal' | 'decision' | 'question' | 'artifact' | 'error' | 'agent' | 'signal' | 'proposal-type' | 'assignment' | 'execution' | 'simulation' | 'seed' | 'workday' | 'note';

function object(value: unknown): Row { if (value && typeof value === 'object' && !Array.isArray(value)) return value as Row; if (typeof value === 'string') try { return object(JSON.parse(value)); } catch { return {}; } return {}; }
function array(value: unknown): unknown[] { if (Array.isArray(value)) return value; if (typeof value === 'string') try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed : []; } catch { return []; } return []; }
function text(...values: unknown[]) { return String(values.find((value) => typeof value === 'string' && value) ?? ''); }
function number(value: unknown) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; }
function iso(value: unknown) { const parsed = Date.parse(String(value ?? '')); return Number.isFinite(parsed) ? new Date(parsed).toISOString() : null; }
function profile(row: Row) { const selected = object(row.selected_input_json); const decision = object(row.decision_input_json); return text(selected.activityType, object(decision.input).activityType, row.handler_id, row.mode, 'planning'); }
function capacity(row: Row) { const selected = object(row.selected_input_json); const usage = object(row.usage_json); return { requestedSeconds: number(row.requested_seconds ?? selected.requestedSeconds), reservedSeconds: number(row.reserved_seconds), activeSeconds: number(row.active_seconds ?? usage.activeSeconds), elapsedSeconds: number(row.elapsed_seconds ?? usage.elapsedSeconds), tokens: number(usage.totalTokens ?? usage.total_tokens) }; }
function minutes(seconds: number) { return `${Math.round(seconds / 60)}m`; }
function projectName(snapshot: Snapshot, projectId: string) { return text(snapshot.rows.projects.find((row) => text(row.id) === projectId)?.name, 'Portfolio'); }
function agentName(row: Row, snapshot: Snapshot) { const identity = text(row.project_agent_class_id, row.agent_class_id, row.agent_id); const configured = snapshot.rows.classes.find((candidate) => [text(candidate.id), text(candidate.slug)].includes(identity)); return text(configured?.name, configured?.slug, row.agent_name, row.handler_id, 'Unassigned agent'); }
function readableEvent(value: unknown) { const raw = text(value, 'recorded event').replace(/[._-]+/gu, ' '); return raw.charAt(0).toUpperCase() + raw.slice(1); }
function timelineCategory(row: Row) { const type = text(row.event_type); if (/proposal|decision|governance|vote|electorate/iu.test(type)) return 'Governance'; if (row.execution_provider_id || row.started_at) return 'Execution provider'; if (/assignment|lease|reservation|capacity/iu.test(type)) return 'Assignment and capacity'; return 'System'; }

function execution(row: Row, snapshot: Snapshot) { const usage = capacity(row); return { id: text(row.id), kind: 'execution' as Kind, title: agentName(row, snapshot), description: `${profile(row)} · ${text(row.execution_provider_id, 'execution provider')}`, status: text(row.status, 'unknown'), projectId: text(row.project_id), projectName: text(row.project_name, projectName(snapshot, text(row.project_id))), activityProfile: profile(row), occurredAt: iso(row.started_at ?? row.created_at), metrics: [{ label: 'Active time', value: minutes(usage.activeSeconds) }, { label: 'Elapsed', value: minutes(usage.elapsedSeconds) }, { label: 'Tokens', value: usage.tokens }], data: { ...row, assignmentId: row.provider_assignment_id } }; }
function assignment(row: Row, snapshot: Snapshot) { const usage = capacity(row); return { id: text(row.id), kind: 'assignment' as Kind, title: agentName(row, snapshot), description: text(row.lifecycle_reason, row.handler_id, `${profile(row)} assignment`), status: text(row.status, 'unknown'), projectId: text(row.project_id), projectName: text(row.project_name, projectName(snapshot, text(row.project_id))), activityProfile: profile(row), occurredAt: iso(row.created_at), metrics: [{ label: 'Requested', value: minutes(usage.requestedSeconds) }, { label: 'Reserved', value: minutes(usage.reservedSeconds) }, { label: 'Active', value: minutes(usage.activeSeconds) }], data: row }; }
function artifact(row: Row, snapshot: Snapshot) { const path = text(row.contentPath, row.path, row.outputRef); return { id: text(row.id, row.receiptId, path, JSON.stringify(row)), kind: 'artifact' as Kind, title: path || 'Generated artifact', description: text(row.model, row.artifactKind, 'Repository content'), projectId: text(row.projectId, row.project_id), projectName: projectName(snapshot, text(row.projectId, row.project_id)), status: 'generated', occurredAt: iso(row.createdAt, row.created_at), tags: [text(row.model), text(row.artifactKind)].filter(Boolean), data: row }; }
function agent(row: Row, snapshot: Snapshot) { const identity = text(row.id, row.agentId, row.agentSlug, row.slug); const executions = snapshot.rows.executions.filter((entry) => [text(entry.agent_id),text(entry.project_agent_class_id)].includes(identity)); return { id: identity, kind: 'agent' as Kind, title: text(row.name, row.title, row.agentSlug, row.slug, 'Configured agent'), description: text(row.description, row.summary, row.agentClass, 'Repository-backed agent'), status: text(row.runtimeStatus, row.status, 'configured'), projectId: text(row.project_id), projectName: projectName(snapshot, text(row.project_id)), metrics: [{ label: 'Profiles', value: Object.keys(object(row.activities)).length }, { label: 'Executions', value: executions.length }, { label: 'Active', value: executions.filter((entry) => text(entry.status) === 'running').length }], tags: [text(row.agentClass), 'configured agent'].filter(Boolean), data: row }; }
function event(row: Row, snapshot: Snapshot) { const failed = /fail|error|expired|stale/iu.test(text(row.event_type, row.severity)); return { id: text(row.id), kind: 'error' as Kind, title: text(row.title, row.event_type, 'Operational event'), description: text(row.message, row.event_type), status: text(row.status, failed ? 'requires attention' : 'observed'), projectId: text(row.project_id), projectName: projectName(snapshot, text(row.project_id)), occurredAt: iso(row.created_at), severity: text(row.severity, failed ? 'danger' : 'info'), actionable: failed, data: row }; }
function proposal(row: Row, snapshot: Snapshot, readiness: GovernanceProposalReadiness | null) { const status = text(row.status); const metadata = object(row.metadata_json); const objectives = array(metadata.relatedObjectives).map(String); const types = [...array(row.proposal_types_json), ...array(metadata.proposalTypes), text(row.proposal_type)].map(String).filter(Boolean).filter((value,index,all) => all.indexOf(value) === index); const objective = objectives[0]?.replace(/^objective:/u, '').replace(/-/gu, ' ') ?? 'Missing objective'; const evidence = array(metadata.evidenceRefs).length; const author = text(metadata.authorAgentId,row.created_by_id) || (text(row.created_by_type) === 'agent' ? 'Configured agent' : 'Team member'); const open = !['accepted','rejected','withdrawn','superseded'].includes(status); return { id: text(row.id), kind: 'proposal' as Kind, title: text(row.title, 'Untitled proposal'), description: text(row.summary, row.body, 'Governance proposal'), status, projectId: text(row.project_id), projectName: projectName(snapshot, text(row.project_id)), occurredAt: iso(row.created_at), actionable: open && readiness?.contentReady === true, version: number(row.active_version), metrics: [{ label: 'Objective', value: objective }, { label: 'Author', value: author }, { label: 'Readiness', value: readiness?.votingReady ? 'Vote ready' : readiness?.contentReady ? 'Ready for review' : `${readiness?.missingContent.length ?? 0} missing requirements` }, { label: 'Evidence', value: evidence }, { label: 'Reviews', value: readiness?.independentReviewCount ?? 0 }, { label: 'Estimates', value: readiness?.estimateCount ?? 0 }], tags: [...types, readiness?.contentReady ? 'structured plan' : 'incomplete draft'], data: { ...row, proposalTypes: types, readiness } }; }
function decision(row: Row, snapshot: Snapshot) { return { id: text(row.id), kind: 'decision' as Kind, title: text(row.title, 'Decision'), description: text(row.summary, 'Governance decision'), status: text(row.status), projectId: text(row.project_id), projectName: projectName(snapshot, text(row.project_id)), occurredAt: iso(row.updated_at), metrics: [{ label: 'Proposal version', value: number(row.proposal_version) }], data: row }; }

export class AgentLabCommandService {
	constructor(private readonly store: Store) {}
	private async governance(teamId: string) { const [proposals, decisions] = await Promise.all([this.store.all(`SELECT * FROM governance_proposals WHERE team_id = ? ORDER BY updated_at DESC LIMIT 200`, [teamId]).catch(() => []), this.store.all(`SELECT * FROM governance_decisions WHERE team_id = ? ORDER BY updated_at DESC LIMIT 200`, [teamId]).catch(() => [])]); return { proposals, decisions }; }
	async surface(surface: Surface, snapshot: Snapshot, query = '') {
		const [governance, operationRows] = await Promise.all([this.governance(snapshot.overview.team.id), this.store.all(`SELECT * FROM platform_operations WHERE namespace = 'agent-lab' ORDER BY created_at DESC LIMIT 100`, []).catch(() => [])]); const proposals = await Promise.all(governance.proposals.map(async (row) => proposal(row, snapshot, await this.store.governanceProposalReadiness(text(row.id))))); const decisions = governance.decisions.map((row) => decision(row, snapshot));
		const assignments = snapshot.rows.assignments.map((row) => assignment(row, snapshot)); const executions = snapshot.rows.executions.map((row) => execution(row, snapshot)); const artifacts = snapshot.artifacts.map((row) => artifact(row, snapshot)); const agents = snapshot.rows.agents.map((row) => agent(row, snapshot)); const events = snapshot.rows.events.map((row) => event(row, snapshot));
		const operationSimulations = operationRows.filter((row) => text(object(row.input_json).teamId) === snapshot.overview.team.id).map((row) => { const input = object(row.input_json); const output = object(row.output_json); return { id: text(row.id), kind: 'simulation' as Kind, title: text(input.scenePath, 'Agent simulation'), description: text(output.sceneId, 'Immutable repository scene operation'), status: text(row.status), projectId: text(input.projectId), projectName: projectName(snapshot, text(input.projectId)), occurredAt: iso(row.created_at), metrics: [{ label: 'Revision', value: text(input.immutableRef).slice(0, 12) }], data: { ...row, input, output, reportUrl: output.reportPath ? `/v1/teams/${snapshot.overview.team.id}/agent-lab/simulations/${row.id}/report` : null } }; });
		const retainedSimulations = snapshot.rows.workdays.filter((row) => text(row.scene_id, object(row.metadata_json).sceneId)).map((row) => ({ id: text(row.id), kind: 'simulation' as Kind, title: text(row.scenario_id, object(row.metadata_json).sceneId, 'Agent simulation'), description: 'Retained production-shaped scene run', status: text(row.status), occurredAt: iso(row.created_at), data: row }));
		const simulations = [...operationSimulations, ...retainedSimulations.filter((entry) => !operationSimulations.some((operation) => operation.id === entry.id))];
		const configuration: Record<Surface, { title: string; description: string; items: ReturnType<typeof event>; secondary?: ReturnType<typeof event>; metrics?: Array<{ label: string; value: number; detail?: string }> }> = {
			inbox: { title: 'Operational Inbox', description: 'Governance and failures that can change what the team does next.', items: [...proposals.filter((item) => item.actionable), ...events.filter((item) => item.actionable), ...artifacts.slice(0, 12)] as ReturnType<typeof event>, metrics: [{ label: 'Awaiting direction', value: proposals.filter((item) => item.actionable).length }, { label: 'Failures', value: events.filter((item) => item.actionable).length }, { label: 'New evidence', value: artifacts.length }] },
			decisions: { title: 'Decision Chamber', description: 'Open proposals beside the durable decisions and work they authorize.', items: proposals as ReturnType<typeof event>, secondary: decisions as ReturnType<typeof event>, metrics: [{ label: 'Open', value: proposals.filter((item) => item.actionable).length }, { label: 'Decided', value: decisions.length }] },
			build: { title: 'Agent Systems Foundry', description: 'Inspect repository-defined agents, their contracts, and production simulations.', items: [...agents, ...simulations] as ReturnType<typeof event>, metrics: [{ label: 'Configured agents', value: agents.length }, { label: 'Live agents', value: new Set(executions.filter((item) => item.status === 'running').map((item) => item.title)).size }, { label: 'Simulation runs', value: simulations.length }] },
			direction: { title: 'Execution Direction', description: 'Follow work from assignment intake through execution-provider evidence and outcomes.', items: assignments as ReturnType<typeof event>, secondary: executions as ReturnType<typeof event>, metrics: [{ label: 'Assigned', value: assignments.length }, { label: 'Started', value: executions.length }, { label: 'Running', value: executions.filter((item) => item.status === 'running').length }] },
			results: { title: 'Result Intelligence', description: 'Research outcomes, generated content, changed files, costs, and recovery evidence.', items: [...artifacts, ...executions.filter((item) => ['succeeded', 'failed'].includes(item.status ?? ''))] as ReturnType<typeof event>, metrics: [{ label: 'Artifacts', value: artifacts.length }, { label: 'Passed', value: executions.filter((item) => item.status === 'succeeded').length }, { label: 'Failed', value: executions.filter((item) => item.status === 'failed').length }] },
			find: { title: 'Relationship Search', description: 'Search operational records and follow how governance, agents, work, and evidence connect.', items: [...proposals, ...decisions, ...agents, ...assignments, ...executions, ...artifacts, ...events] as ReturnType<typeof event>, metrics: [{ label: 'Searchable records', value: proposals.length + decisions.length + agents.length + assignments.length + executions.length + artifacts.length + events.length }] },
		};
		const selected = configuration[surface]; const filter = (items: typeof selected.items) => query ? items.filter((item) => `${item.title} ${item.description} ${item.projectName ?? ''}`.toLowerCase().includes(query.toLowerCase())) : items;
		const items = filter(selected.items); const secondaryItems = selected.secondary ? filter(selected.secondary) : undefined; const relationItems = [...items, ...(secondaryItems ?? [])];
		const relations = surface === 'build' || surface === 'find' ? relationItems.flatMap((item) => { const assignmentId = text(item.data?.assignmentId); const related = assignmentId && relationItems.find((candidate) => candidate.id === assignmentId); return related ? [{ id: `${item.id}:${related.id}`, from: related.id, to: item.id, label: 'produces' }] : []; }) : [];
		return { revision: snapshot.overview.revision, generatedAt: snapshot.overview.generatedAt, surface, title: selected.title, description: selected.description, unreadCount: proposals.filter((item) => item.actionable).length + events.filter((item) => item.actionable).length, items, secondaryItems, metrics: selected.metrics, relations, page: { hasMore: false, nextCursor: null, total: items.length } };
	}
	async detail(kind: Kind, id: string, snapshot: Snapshot) {
		const owningSurface: Surface = ['simulation', 'seed', 'agent', 'signal', 'proposal-type'].includes(kind) ? 'build' : kind === 'proposal' || kind === 'decision' ? 'decisions' : kind === 'assignment' || kind === 'execution' ? 'direction' : kind === 'artifact' || kind === 'workday' ? 'results' : 'inbox';
		const surface = await this.surface(owningSurface, snapshot); const item = [...surface.items, ...(surface.secondaryItems ?? [])].find((entry) => entry.kind === kind && entry.id === id); if (!item) return null;
		const source = object(item.data); const assignmentId = kind === 'assignment' ? id : text(source.provider_assignment_id, item.data?.assignmentId);
		const governanceId = ['proposal', 'decision'].includes(kind) ? id : ''; const linkedAssignmentRows = governanceId ? snapshot.rows.assignments.filter((row) => JSON.stringify([row.decision_input_json, row.metadata_json]).includes(governanceId)) : [];
		const linkedAssignmentIds = new Set(linkedAssignmentRows.map((row) => text(row.id))); const executionRows = snapshot.rows.executions.filter((row) => text(row.id) === id || text(row.provider_assignment_id) === assignmentId || linkedAssignmentIds.has(text(row.provider_assignment_id)));
		const eventRows = snapshot.rows.events.filter((row) => text(row.assignment_id, object(row.payload_json).assignmentId) === assignmentId || linkedAssignmentIds.has(text(row.assignment_id, object(row.payload_json).assignmentId)));
		const governanceEvents = governanceId ? await this.store.all(`SELECT * FROM governance_events WHERE ${kind === 'proposal' ? 'proposal_id' : 'decision_id'} = ? ORDER BY created_at ASC LIMIT 200`, [governanceId]).catch(() => []) : [];
		const discussionRelations = governanceEvents.filter((row) => text(row.event_type) === 'proposal.discussion').map((row) => { const evidence = object(row.evidence_json); const discussionKind = text(evidence.kind); return { id: text(row.id), kind: discussionKind === 'question' ? 'question' as Kind : 'note' as Kind, title: readableEvent(discussionKind || 'discussion'), description: text(row.message), status: text(evidence.resolvesEventId) ? 'response' : ['question','concern'].includes(discussionKind) ? 'open' : 'recorded', projectId: text(row.project_id), projectName: projectName(snapshot, text(row.project_id)), occurredAt: iso(row.created_at), tags: [discussionKind].filter(Boolean), data: { ...row, discussionKind, proposalId: governanceId, resolvesEventId: evidence.resolvesEventId ?? null } }; });
			const context = object(source.selected_input_json); const decisionInput = object(source.decision_input_json); const usage = object(source.usage_json); const output = object(source.outputs_json); const lifecycle = object(source.lifecycle_output_json);
			const primary = await commandPrimaryView(this.store, kind, item, source);
			return { ...item, primary, permissions: { note: true, question: true, edit: kind === 'proposal', vote: kind === 'proposal' }, links: source.reportUrl ? [{ label: 'Open forensic simulation report', href: text(source.reportUrl), external: true }] : [], metrics: [...(item.metrics ?? []), { label: 'Events', value: eventRows.length }, { label: 'Executions', value: executionRows.length }], sections: [
			{ id: 'identity', title: 'Operational identity', fields: [{ label: 'Status', value: item.status }, { label: 'Project', value: item.projectName }, { label: 'Activity profile', value: item.activityProfile }, { label: 'Handler', value: source.handler_id }, { label: 'Execution provider', value: source.execution_provider_id }] },
			{ id: 'provenance', title: 'Assignment and governance provenance', fields: [{ label: 'Request', value: source.lifecycle_reason }, { label: 'Admission estimate', value: object(object(source.metadata_json).admissionEstimate ?? object(source.metadata_json).admission_estimate) }, { label: 'Decision input', value: decisionInput }, { label: 'Matching', value: object(source.matching_explanation_json) }, { label: 'Lease', value: { expiresAt: source.lease_expires_at, stateVersion: source.state_version } }] },
			{ id: 'context', title: 'Context composition', fields: [{ label: 'Context query', value: context.contextQuery ?? context.context }, { label: 'Context pack', value: context.contextPack ?? context.context_pack }, { label: 'Input tokens', value: usage.inputTokens ?? usage.input_tokens }, { label: 'Cache tokens', value: usage.cacheTokens ?? usage.cache_tokens }] },
			{ id: 'provider', title: 'Execution-provider evidence', fields: [{ label: 'Configuration', value: context.executionProvider ?? source.execution_provider_config_json }, { label: 'Prompt and input', value: context.prompt ?? context.input }, { label: 'Messages and tools', value: object(source.transcript_json) }, { label: 'Usage', value: usage }] },
			{ id: 'outputs', title: 'Outputs and artifacts', fields: [{ label: 'Outputs', value: output }, { label: 'Control-plane submission', value: lifecycle }, { label: 'Diagnostics', value: object(source.diagnostics_json) }, { label: 'Forensic report', value: source.reportUrl }] },
			], timeline: [...governanceEvents, ...eventRows, ...executionRows].map((row) => ({ id: text(row.id), timestamp: text(row.created_at, row.started_at, snapshot.overview.generatedAt), title: readableEvent(row.title ?? row.event_type ?? row.status), description: text(row.message, row.lifecycle_reason), category: timelineCategory(row), status: text(row.next_state, row.status) || null, details: object(row.payload_json ?? row.evidence_json) })).sort((a, b) => a.timestamp.localeCompare(b.timestamp)), related: [...discussionRelations, ...linkedAssignmentRows.map((row) => assignment(row, snapshot)), ...executionRows.filter((row) => text(row.id) !== id).map((row) => execution(row, snapshot))] };
	}
	revision(payload: unknown) { return createHash('sha256').update(JSON.stringify(payload)).digest('hex').slice(0, 24); }
}
