import { createHash, randomUUID } from 'node:crypto';
import { commitInboxQuestion } from './question-content.ts';
import { loadDiscussions } from '../../discussions/content.ts';
import { parseFrontmatterDocument } from '../../content/frontmatter.ts';
import { resolveKnowledgeGatewayConnection } from '../../knowledge/gateway-treedx-connection.ts';

type Row = Record<string, any>;
type Principal = Row | undefined;
export class InboxServiceError extends Error { constructor(readonly status: 400|401|403|404|409|412|422|503, readonly code: string, message: string) { super(message); } }
const text = (value: unknown, fallback = '') => typeof value === 'string' && value.trim() ? value.trim() : fallback;
const record = (value: unknown): Row => value && typeof value === 'object' && !Array.isArray(value) ? value as Row : typeof value === 'string' ? (() => { try { return record(JSON.parse(value)); } catch { return {}; } })() : {};
const timestamp = (value: unknown) => value instanceof Date ? value.toISOString() : text(value, new Date().toISOString());
const etag = (row: Row) => `inbox:${row.id}:${Number(row.version ?? 1)}:${timestamp(row.updated_at)}`;

export function createInboxService(input: { store: any; discussions: any; communications: any; governance: any }) {
	const { store, discussions, communications, governance } = input;
	async function authorize(principal: Principal, teamId: string, manage = false) {
		if (!principal) throw new InboxServiceError(401, 'authentication_required', 'Authentication is required.');
		const admin = principal.roles?.some((role: string) => ['admin','platform_admin'].includes(role));
		if (!admin && !await store.principalCanAccessTeam(principal, teamId)) throw new InboxServiceError(403, 'inbox_access_denied', 'Team access is required.');
		if (manage && !admin) { const access = await store.getTeamAccessSummary(teamId, principal); if (!access.permissions?.some((permission: string) => ['projects:manage:team','*:*:*'].includes(permission))) throw new InboxServiceError(403, 'inbox_manage_denied', 'Project management permission is required.'); }
	}
	async function syncProposals(teamId: string) {
		await store.run(`INSERT INTO inbox_items (id,team_id,project_id,kind,title,markdown,status,author_id,author_label,version,repository_id,content_path,commit_sha,digest,metadata_json,created_at,updated_at)
			SELECT proposal.id,proposal.team_id,proposal.project_id,'proposal',proposal.title,proposal.body,
			CASE WHEN proposal.status IN ('accepted','approved') THEN 'approved' WHEN proposal.status='rejected' THEN 'rejected' WHEN proposal.status IN ('withdrawn','superseded','expired') THEN 'closed' ELSE 'outstanding' END,
			COALESCE(proposal.created_by_id,'unknown'),COALESCE(proposal.created_by_id,'unknown'),proposal.active_version,
			proposal.metadata_json::jsonb->'contentProvenance'->>'repositoryId',proposal.metadata_json::jsonb->'contentProvenance'->>'contentPath',proposal.metadata_json::jsonb->'contentProvenance'->>'commitSha',proposal.metadata_json::jsonb->'contentProvenance'->>'digest',proposal.metadata_json::jsonb,proposal.created_at::timestamptz,proposal.updated_at::timestamptz
			FROM governance_proposals proposal WHERE proposal.team_id=? ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,markdown=EXCLUDED.markdown,status=EXCLUDED.status,version=EXCLUDED.version,repository_id=EXCLUDED.repository_id,content_path=EXCLUDED.content_path,commit_sha=EXCLUDED.commit_sha,digest=EXCLUDED.digest,metadata_json=EXCLUDED.metadata_json,updated_at=EXCLUDED.updated_at`, [teamId]);
	}
	async function syncQuestions(teamId: string) {
		const signals=await store.all("SELECT project_id,subject_id,commit_sha,agent_id,created_at FROM agent_signals WHERE team_id=? AND subject_kind='question' AND commit_sha IS NOT NULL ORDER BY created_at DESC LIMIT 1000",[teamId]);
		for(const signal of signals){
			const path=text(signal.subject_id),commitSha=text(signal.commit_sha);if(!path||!commitSha)continue;
			const existing=await store.first("SELECT id,commit_sha FROM inbox_items WHERE team_id=? AND kind='question' AND project_id=? AND content_path=? LIMIT 1",[teamId,signal.project_id,path]);if(text(existing?.commit_sha)===commitSha)continue;
			try{
				const connection=await resolveKnowledgeGatewayConnection(store,{projectId:signal.project_id,write:false,readRefs:[commitSha]});if(!connection)continue;
				const read=await connection.client.readRepositoryFiles({repoId:connection.repositoryId,ref:commitSha,paths:[path],encoding:'utf8',parseFrontmatter:false,allowProtected:true});const file=(read.files??[])[0];
				if(!file){if(existing){await store.run("UPDATE inbox_items SET status='deleted',updated_at=? WHERE id=?",[new Date().toISOString(),existing.id]);await store.run('DELETE FROM inbox_drafts WHERE item_id=?',[existing.id]);}continue;}
				const source=text(file.content),parsed=parseFrontmatterDocument(source),frontmatter=record(parsed.frontmatter);
				const fallbackId=`question:${signal.project_id}:${createHash('sha256').update(path).digest('hex').slice(0,24)}`;
				const id=text(frontmatter.id,text(existing?.id,fallbackId)),now=timestamp(frontmatter.updatedAt ?? signal.created_at),questionStatus=['answered','closed'].includes(text(frontmatter.status))?text(frontmatter.status):'outstanding',digest=createHash('sha256').update(source).digest('hex');
				const authorId=text(frontmatter.createdBy,text(signal.agent_id,'unknown'));
				await store.run(`INSERT INTO inbox_items (id,team_id,project_id,kind,title,markdown,status,author_id,author_label,version,repository_id,content_path,commit_sha,digest,metadata_json,created_at,updated_at) VALUES (?,?,?,'question',?,?,?,?,?,1,?,?,?,?,?::jsonb,?,?) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,markdown=EXCLUDED.markdown,status=EXCLUDED.status,repository_id=EXCLUDED.repository_id,content_path=EXCLUDED.content_path,commit_sha=EXCLUDED.commit_sha,digest=EXCLUDED.digest,metadata_json=EXCLUDED.metadata_json,updated_at=EXCLUDED.updated_at`,[id,teamId,signal.project_id,text(frontmatter.title,path),parsed.body,questionStatus,authorId,authorId,connection.repositoryId,path,commitSha,digest,JSON.stringify(frontmatter),timestamp(frontmatter.createdAt ?? signal.created_at),now]);
			}catch{/* A later list request retries transient exact-ref reads. */}
		}
	}
	async function projectSlug(projectId: string) { return text((await store.getProjectDetails(projectId))?.project?.slug, projectId); }
	function actions(row: Row) {
		const outstanding = row.status === 'outstanding';
		const action = (name: string, label: string, enabled: boolean, reason: string|null = null, feedback = false, confirmation: 'never'|'input_required' = 'never') => ({ action: name, label, enabled, reason, requiresFeedback: feedback, confirmation });
		return row.kind === 'proposal' ? [action('publish_revision','Publish Revision',outstanding,outstanding ? null : 'Proposal is closed.',false), action('approve','Approve',outstanding,null,true,'input_required'), action('reject','Reject',outstanding,null,true,'input_required'), action('comment','Comment',true,null,true)]
			: [action('answer','Answer',outstanding,outstanding ? null : 'Question is already answered.',true), action('comment','Comment',true,null,true), action('reopen','Reopen',row.status === 'answered',row.status === 'answered' ? null : 'Only answered questions can be reopened.')];
	}
	async function comments(row: Row) {
		if (!row.discussion_id) return [];
		const history = await loadDiscussions({ store, projectId: row.project_id, discussionId: row.discussion_id, collection: 'messages', limit: 500 }).catch(() => ({ messages: [] }));
		return history.messages.map((message: Row) => { const fm = record(message.frontmatter); return { id: text(message.id), parentId: text(fm.replyTo) || null,
			kind: text(fm.inboxIntent, text(fm.intent) === 'answer' ? 'answer' : fm.replyTo ? 'reply' : 'comment'), authorId: text(fm.authorId,'unknown'), authorLabel: text(message.authorLabel,text(fm.authorId,'unknown')),
			markdown: text(message.body), createdAt: timestamp(fm.createdAt), provenance: { repositoryId: null, contentPath: text(message.path)||null, commitSha: text(fm.commitSha)||null, digest: createHash('sha256').update(text(message.body)).digest('hex') } }; });
	}
	async function syncAgentAnswer(row: Row) {
		if (row.kind !== 'question' || row.status !== 'outstanding' || !row.discussion_id) return row;
		const history = await loadDiscussions({ store, projectId: row.project_id, discussionId: row.discussion_id, collection: 'messages', limit: 500 }).catch(() => ({ messages: [] }));
		const answer = history.messages.find((message: Row) => text(record(message.frontmatter).authorType) === 'agent');
		if (!answer) return row;
		const frontmatter = record(answer.frontmatter), now = timestamp(frontmatter.createdAt);
		await store.run("UPDATE inbox_items SET status='answered',updated_at=? WHERE id=? AND status='outstanding'", [now,row.id]);
		await event(row.team_id,row.id,'question.answered',text(frontmatter.authorId,'agent'),'Agent answer received.',{ messageRef: answer.path });
		return { ...row, status: 'answered', updated_at: now };
	}
	async function view(row: Row) { const slug = await projectSlug(row.project_id); return { schemaVersion: 'treeseed.inbox-item/v1', id: text(row.id), teamId: text(row.team_id), projectId: text(row.project_id), projectSlug: slug,
		kind: row.kind, title: text(row.title), markdown: text(row.markdown), status: row.status, authorId: text(row.author_id), authorLabel: text(row.author_label), version: Number(row.version), discussionId: text(row.discussion_id)||null,
		createdAt: timestamp(row.created_at), updatedAt: timestamp(row.updated_at), provenance: { repositoryId: text(row.repository_id)||null, contentPath: text(row.content_path)||null, commitSha: text(row.commit_sha)||null, digest: text(row.digest)||null },
		availableActions: actions(row), comments: await comments(row), etag: etag(row) }; }
	async function item(teamId: string, itemId: string) { const row = await store.first('SELECT * FROM inbox_items WHERE team_id=? AND id=? LIMIT 1',[teamId,itemId]); if (!row) throw new InboxServiceError(404,'inbox_item_not_found','Inbox item not found.'); return row; }
	async function event(teamId: string, itemId: string|null, type: string, actorId: string, summary: string, payload: Row = {}) { const id=`inbox-event-${randomUUID()}`, now=new Date().toISOString(); await store.run('INSERT INTO inbox_events (id,team_id,item_id,event_type,actor_id,summary,payload_json,occurred_at) VALUES (?,?,?,?,?,?,?::jsonb,?)',[id,teamId,itemId,type,actorId,summary,JSON.stringify(payload),now]); return id; }
	return {
		async list(principal: Principal, teamId: string, query: Row) { await authorize(principal,teamId); await Promise.all([syncProposals(teamId),syncQuestions(teamId)]); const clauses=['team_id=?'], values:any[]=[teamId]; if (query.projectId) {clauses.push('project_id=?');values.push(query.projectId);} if (query.kind && query.kind!=='all') {clauses.push('kind=?');values.push(query.kind);} if (query.state!=='all') clauses.push("status='outstanding'"); if (query.cursor){clauses.push('updated_at<?');values.push(query.cursor);} const limit=Math.max(1,Math.min(500,Number(query.limit)||200)); const rows=await store.all(`SELECT * FROM inbox_items WHERE ${clauses.join(' AND ')} ORDER BY updated_at DESC,id DESC LIMIT ?`,[...values,limit]); const items=await Promise.all(rows.map(async(row:Row)=>{const full=await view(await syncAgentAnswer(row));const {schemaVersion,markdown,provenance,availableActions,comments,discussionId,...summary}=full;void schemaVersion;return summary;})); return {schemaVersion:'treeseed.inbox-page/v1',items,cursor:rows.length===limit?timestamp(rows.at(-1)?.updated_at):null}; },
		async show(principal: Principal, teamId: string, itemId: string) { await authorize(principal,teamId); await Promise.all([syncProposals(teamId),syncQuestions(teamId)]); return view(await syncAgentAnswer(await item(teamId,itemId))); },
		async events(principal: Principal, teamId: string, query: Row) { await authorize(principal,teamId); const after=Math.max(0,Number(query.after)||0),limit=Math.max(1,Math.min(500,Number(query.limit)||200)),deadline=Date.now()+Math.max(0,Math.min(30,Number(query.waitSeconds)||0))*1000;let rows:Row[]=[];do{rows=await store.all('SELECT * FROM inbox_events WHERE team_id=? AND sequence>? ORDER BY sequence LIMIT ?',[teamId,after,limit]);if(rows.length||Date.now()>=deadline)break;await new Promise(r=>setTimeout(r,Math.min(250,Math.max(1,deadline-Date.now()))));}while(Date.now()<deadline);return{events:rows.map(row=>({schemaVersion:'treeseed.inbox-event/v1',sequence:String(row.sequence),id:row.id,teamId:row.team_id,itemId:row.item_id??null,type:row.event_type,actorId:row.actor_id,occurredAt:timestamp(row.occurred_at),summary:row.summary,payload:record(row.payload_json)})),cursor:rows.length?String(rows.at(-1)?.sequence):String(after)}; },
		async createQuestion(principal: Principal, teamId: string, body: Row, idempotencyKey?: string) { await authorize(principal,teamId,true); if(!idempotencyKey)throw new InboxServiceError(400,'idempotency_key_required','Idempotency-Key is required.');const prior=await store.first('SELECT result_json FROM inbox_action_receipts WHERE team_id=? AND idempotency_key=?',[teamId,idempotencyKey]);if(prior)return{...record(prior.result_json),replayed:true};const project=await store.getProjectDetails(body.projectId);if(project?.project?.teamId!==teamId)throw new InboxServiceError(403,'inbox_project_team_mismatch','The owning project is not in the active team.');const authored=await commitInboxQuestion({store,teamId,projectId:body.projectId,principal:principal!,title:body.title,markdown:body.markdown,relatedObjectives:body.relatedObjectives??[]});let discussionId:string|null=null;const recipients=Array.isArray(body.recipients)?body.recipients.map(String):[];if(recipients.length){const message=`${recipients.join(' ')}\n\n${body.markdown}`;const sent=await communications.send(principal,teamId,`question-${authored.id.slice(-12)}`,{message,recipients},`${idempotencyKey}:route`);discussionId=text(sent.projectStreams?.find((stream:Row)=>stream.projectId===body.projectId)?.discussionId)||null;}const now=authored.createdAt;await store.run(`INSERT INTO inbox_items (id,team_id,project_id,kind,title,markdown,status,author_id,author_label,version,discussion_id,repository_id,content_path,commit_sha,digest,metadata_json,created_at,updated_at) VALUES (?,?,?,'question',?,?,'outstanding',?,?,?,?,?,?,?,?,?::jsonb,?,?)`,[authored.id,teamId,body.projectId,body.title,body.markdown,principal!.id,principal!.displayName??principal!.id,1,discussionId,authored.repositoryId,authored.path,authored.commitSha,authored.digest,JSON.stringify({relatedObjectives:body.relatedObjectives??[],recipients}),now,now]);await event(teamId,authored.id,'item.created',principal!.id,'Question created and routed.',{recipients});const result={schemaVersion:'treeseed.inbox-mutation-receipt/v1',item:await view(await item(teamId,authored.id)),replayed:false,receipts:[{contentPath:authored.path,commitSha:authored.commitSha}]};await store.run('INSERT INTO inbox_action_receipts (team_id,idempotency_key,item_id,action,result_json,created_at) VALUES (?,?,?,?,?::jsonb,?)',[teamId,idempotencyKey,authored.id,'create_question',JSON.stringify(result),now]);return result; },
		async draft(principal: Principal,teamId:string,itemId:string,purpose:string){await authorize(principal,teamId);await item(teamId,itemId);const row=await store.first('SELECT * FROM inbox_drafts WHERE item_id=? AND principal_id=? AND purpose=?',[itemId,principal!.id,purpose]);return row?{schemaVersion:'treeseed.inbox-draft/v1',itemId,purpose,markdown:row.markdown,baseVersion:Number(row.base_version),revision:Number(row.revision),updatedAt:timestamp(row.updated_at),etag:`draft:${itemId}:${row.revision}`}:null;},
		async putDraft(principal:Principal,teamId:string,itemId:string,purpose:string,body:Row,ifMatch?:string){await authorize(principal,teamId,true);await item(teamId,itemId);const existing=await store.first('SELECT * FROM inbox_drafts WHERE item_id=? AND principal_id=? AND purpose=?',[itemId,principal!.id,purpose]);const expected=existing?`draft:${itemId}:${existing.revision}`:'draft:new';if(ifMatch!==expected)throw new InboxServiceError(412,'inbox_draft_precondition_failed','The draft changed after it was loaded.');const revision=Number(existing?.revision??-1)+1,now=new Date().toISOString();await store.run(`INSERT INTO inbox_drafts (item_id,principal_id,purpose,markdown,base_version,revision,updated_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT (item_id,principal_id,purpose) DO UPDATE SET markdown=EXCLUDED.markdown,base_version=EXCLUDED.base_version,revision=EXCLUDED.revision,updated_at=EXCLUDED.updated_at`,[itemId,principal!.id,purpose,body.markdown,body.baseVersion,revision,now]);await event(teamId,itemId,'draft.updated',principal!.id,'Private draft saved.');return{schemaVersion:'treeseed.inbox-draft/v1',itemId,purpose,markdown:body.markdown,baseVersion:body.baseVersion,revision,updatedAt:now,etag:`draft:${itemId}:${revision}`};},
		async deleteDraft(principal:Principal,teamId:string,itemId:string,purpose:string){await authorize(principal,teamId,true);await store.run('DELETE FROM inbox_drafts WHERE item_id=? AND principal_id=? AND purpose=?',[itemId,principal!.id,purpose]);return{deleted:true};},
		async action(principal:Principal,teamId:string,itemId:string,body:Row,idempotencyKey?:string,ifMatch?:string){await authorize(principal,teamId,true);if(!idempotencyKey)throw new InboxServiceError(400,'idempotency_key_required','Idempotency-Key is required.');const replay=await store.first('SELECT result_json FROM inbox_action_receipts WHERE team_id=? AND idempotency_key=?',[teamId,idempotencyKey]);if(replay)return{...record(replay.result_json),replayed:true};let row=await item(teamId,itemId);if(ifMatch!==etag(row))throw new InboxServiceError(412,'inbox_item_precondition_failed','The item changed after it was loaded.');const action=text(body.action),now=new Date().toISOString(),receipts:Row[]=[];
			if(['comment','answer','reply'].includes(action)){if(!text(body.markdown))throw new InboxServiceError(422,'inbox_feedback_required','Markdown feedback is required.');const result=await discussions.create(principal,{teamId,projectId:row.project_id,discussionId:row.discussion_id||undefined,createDiscussion:!row.discussion_id,body:body.markdown,intent:'discuss',inboxIntent:action,replyTo:text(body.parentId)||undefined},`${idempotencyKey}:discussion`);const discussionId=text(result.discussion?.id);await store.run('UPDATE inbox_items SET discussion_id=COALESCE(discussion_id,?),status=CASE WHEN ?=\'answer\' THEN \'answered\' ELSE status END,updated_at=? WHERE id=?',[discussionId,action,now,itemId]);receipts.push({messageRef:result.message?.path,commitSha:result.commitSha});if(row.kind==='proposal')await store.recordGovernanceEvent({eventType:'proposal.discussion',actorType:'user',actorId:principal!.id,teamId,projectId:row.project_id,proposalId:itemId,proposalVersion:row.version,message:body.markdown,evidence:{kind:'response',contentPath:result.message?.path,commitSha:result.commitSha}});await event(teamId,itemId,action==='answer'?'question.answered':'comment.created',principal!.id,action==='answer'?'Question answered.':'Comment added.',{messageRef:result.message?.path});}
			else if(action==='reopen'){if(row.kind!=='question'||row.status!=='answered')throw new InboxServiceError(409,'inbox_reopen_invalid','Only answered questions can be reopened.');await store.run("UPDATE inbox_items SET status='outstanding',updated_at=? WHERE id=?",[now,itemId]);await event(teamId,itemId,'question.reopened',principal!.id,'Question reopened.');}
			else if(action==='publish_revision'){if(row.kind!=='proposal'||!text(body.markdown)||!text(body.changeReason))throw new InboxServiceError(422,'inbox_revision_invalid','Proposal markdown and a change summary are required.');const result=await governance.updateProposal(principal,row.project_id,itemId,{body:body.markdown,changeReason:body.changeReason,expectedProposalVersion:row.version},String(row.version));receipts.push(result.authoringReceipt??{});await syncProposals(teamId);await event(teamId,itemId,'proposal.revised',principal!.id,'Proposal revision published.');}
			else if(['approve','reject'].includes(action)){if(row.kind!=='proposal'||!text(body.markdown))throw new InboxServiceError(422,'inbox_decision_reason_required','A decision rationale is required.');await store.adminDecideGovernanceProposal(principal,itemId,{status:action==='approve'?'approved':'rejected',reason:body.markdown,expectedProposalVersion:row.version});await syncProposals(teamId);await event(teamId,itemId,'proposal.decided',principal!.id,`Proposal ${action}d.`,{action});}
			else throw new InboxServiceError(400,'inbox_action_invalid','Unsupported inbox action.');row=await item(teamId,itemId);const result={schemaVersion:'treeseed.inbox-mutation-receipt/v1',item:await view(row),action,replayed:false,receipts};await store.run('INSERT INTO inbox_action_receipts (team_id,idempotency_key,item_id,action,result_json,created_at) VALUES (?,?,?,?,?::jsonb,?)',[teamId,idempotencyKey,itemId,action,JSON.stringify(result),now]);return result;},
	};
}
