import type { MarketControlPlaneStore } from '../../store.ts';
import { getCommerceVendorForTeamMethod } from '../get-commerce-vendor-for-team.ts';
import { getCommerceVendorMethod } from '../get-commerce-vendor.ts';
import { requestCommerceVendorMethod } from '../request-commerce-vendor.ts';
import { updateCommerceVendorMethod } from '../update-commerce-vendor.ts';
import { approveCommerceVendorMethod } from '../approve-commerce-vendor.ts';
import { getCommerceVendorStripeAccountMethod } from '../get-commerce-vendor-stripe-account.ts';
import { getCommerceVendorStripeAccountForTeamMethod } from '../get-commerce-vendor-stripe-account-for-team.ts';
import { getCommerceVendorStripeAccountByStripeIdMethod } from '../get-commerce-vendor-stripe-account-by-stripe-id.ts';
import { createCommerceVendorStripeAccountMethod } from '../create-commerce-vendor-stripe-account.ts';
import { updateCommerceVendorStripeAccountMethod } from '../update-commerce-vendor-stripe-account.ts';
import { upsertCommerceVendorStripeAccountMethod } from '../upsert-commerce-vendor-stripe-account.ts';
import { markCommerceStripeOnboardingStartedMethod } from '../mark-commerce-stripe-onboarding-started.ts';
import { markCommerceStripeOnboardingReturnedMethod } from '../mark-commerce-stripe-onboarding-returned.ts';
import { recordCommerceStripeAccountStatusMethod } from '../record-commerce-stripe-account-status.ts';
import { createCommerceProductDraftMethod } from '../create-commerce-product-draft.ts';
import { getCommerceProductMethod } from '../get-commerce-product.ts';
import { listCommerceProductsMethod } from '../list-commerce-products.ts';
import { commerceMarketplaceProductSummaryMethod } from '../commerce-marketplace-product-summary.ts';
import { listCommerceMarketplaceProductsMethod } from '../list-commerce-marketplace-products.ts';
import { getCommerceMarketplaceProductMethod } from '../get-commerce-marketplace-product.ts';
import { updateCommerceProductMethod } from '../update-commerce-product.ts';
import { transitionCommerceProductMethod } from '../transition-commerce-product.ts';
import { submitCommerceProductMethod } from '../submit-commerce-product.ts';
import { approveCommerceProductMethod } from '../approve-commerce-product.ts';
import { archiveCommerceProductMethod } from '../archive-commerce-product.ts';
import { createCommerceOwnershipRecordMethod } from '../create-commerce-ownership-record.ts';
import { listCommerceOwnershipRecordsMethod } from '../list-commerce-ownership-records.ts';
import { updateCommerceOwnershipRecordMethod } from '../update-commerce-ownership-record.ts';
import { setCurrentCommerceOwnershipRecordMethod } from '../set-current-commerce-ownership-record.ts';
import { createCommerceStewardshipAssignmentMethod } from '../create-commerce-stewardship-assignment.ts';
import { listCommerceStewardshipAssignmentsMethod } from '../list-commerce-stewardship-assignments.ts';
import { updateCommerceStewardshipAssignmentMethod } from '../update-commerce-stewardship-assignment.ts';
import { endCommerceStewardshipAssignmentMethod } from '../end-commerce-stewardship-assignment.ts';
import { createCommerceContributionMethod } from '../create-commerce-contribution.ts';
import { listCommerceContributionsMethod } from '../list-commerce-contributions.ts';
import { updateCommerceContributionMethod } from '../update-commerce-contribution.ts';
import { createCommerceGovernancePolicyMethod } from '../create-commerce-governance-policy.ts';
import { listCommerceGovernancePoliciesMethod } from '../list-commerce-governance-policies.ts';
import { updateCommerceGovernancePolicyMethod } from '../update-commerce-governance-policy.ts';
import { createCommerceOwnershipTransferMethod } from '../create-commerce-ownership-transfer.ts';
import { updateCommerceOwnershipTransferStateMethod } from '../update-commerce-ownership-transfer-state.ts';
import { submitCommerceOwnershipTransferMethod } from '../submit-commerce-ownership-transfer.ts';
import { approveCommerceOwnershipTransferMethod } from '../approve-commerce-ownership-transfer.ts';
import { rejectCommerceOwnershipTransferMethod } from '../reject-commerce-ownership-transfer.ts';
import { cancelCommerceOwnershipTransferMethod } from '../cancel-commerce-ownership-transfer.ts';
import { createCommerceSuccessionEventMethod } from '../create-commerce-succession-event.ts';
import { listCommerceSuccessionEventsMethod } from '../list-commerce-succession-events.ts';
import { getCommerceOwnershipWorkflowSummaryMethod } from '../get-commerce-ownership-workflow-summary.ts';
import { commerceCapacityOwnershipSnapshotMethod } from '../commerce-capacity-ownership-snapshot.ts';
import { validateCommerceCapacityProviderDisclosureMethod } from '../validate-commerce-capacity-provider-disclosure.ts';
import { ensureCommerceCapacityListingEligibilityMethod } from '../ensure-commerce-capacity-listing-eligibility.ts';
import { createCommerceCapacityListingMethod } from '../create-commerce-capacity-listing.ts';
import { getCommerceCapacityListingMethod } from '../get-commerce-capacity-listing.ts';
import { getCommerceCapacityListingForProductMethod } from '../get-commerce-capacity-listing-for-product.ts';
import { listCommerceCapacityListingsMethod } from '../list-commerce-capacity-listings.ts';
import { updateCommerceCapacityListingMethod } from '../update-commerce-capacity-listing.ts';
import { transitionCommerceCapacityListingMethod } from '../transition-commerce-capacity-listing.ts';
import { submitCommerceCapacityListingMethod } from '../submit-commerce-capacity-listing.ts';
import { approveCommerceCapacityListingMethod } from '../approve-commerce-capacity-listing.ts';
import { rejectCommerceCapacityListingMethod } from '../reject-commerce-capacity-listing.ts';
import { suspendCommerceCapacityListingMethod } from '../suspend-commerce-capacity-listing.ts';
import { archiveCommerceCapacityListingMethod } from '../archive-commerce-capacity-listing.ts';
import { createCommerceCapacityListingInquiryMethod } from '../create-commerce-capacity-listing-inquiry.ts';
import { getCommerceCapacityListingInquiryMethod } from '../get-commerce-capacity-listing-inquiry.ts';
import { listCommerceCapacityListingInquiriesMethod } from '../list-commerce-capacity-listing-inquiries.ts';
import { transitionCommerceCapacityInquiryMethod } from '../transition-commerce-capacity-inquiry.ts';
import { markCommerceCapacityInquiryReviewingMethod } from '../mark-commerce-capacity-inquiry-reviewing.ts';
import { approveCommerceCapacityInquiryForScopingMethod } from '../approve-commerce-capacity-inquiry-for-scoping.ts';
import { declineCommerceCapacityInquiryMethod } from '../decline-commerce-capacity-inquiry.ts';
import { cancelCommerceCapacityInquiryMethod } from '../cancel-commerce-capacity-inquiry.ts';
import { createCommerceProductVersionMethod } from '../create-commerce-product-version.ts';
import { getCommerceProductVersionMethod } from '../get-commerce-product-version.ts';
import { getCommerceProductVersionByIdMethod } from '../get-commerce-product-version-by-id.ts';
import { listCommerceProductVersionsMethod } from '../list-commerce-product-versions.ts';
import { transitionCommerceProductVersionMethod } from '../transition-commerce-product-version.ts';
import { submitCommerceProductVersionMethod } from '../submit-commerce-product-version.ts';
import { approveCommerceProductVersionMethod } from '../approve-commerce-product-version.ts';
import { createCommerceOfferMethod } from '../create-commerce-offer.ts';
import { getCommerceOfferMethod } from '../get-commerce-offer.ts';
import { listCommerceOffersMethod } from '../list-commerce-offers.ts';
import { updateCommerceOfferMethod } from '../update-commerce-offer.ts';
import { transitionCommerceOfferMethod } from '../transition-commerce-offer.ts';
import { submitCommerceOfferMethod } from '../submit-commerce-offer.ts';
import { approveCommerceOfferMethod } from '../approve-commerce-offer.ts';
import { archiveCommerceOfferMethod } from '../archive-commerce-offer.ts';
import { createCommercePriceMethod } from '../create-commerce-price.ts';
import { listCommercePricesMethod } from '../list-commerce-prices.ts';
import { getCommercePriceMethod } from '../get-commerce-price.ts';
import { activateCommercePriceMethod } from '../activate-commerce-price.ts';
import { updateCommerceOfferStripeProductSyncMethod } from '../update-commerce-offer-stripe-product-sync.ts';
import { markCommerceOfferStripeSyncBlockedMethod } from '../mark-commerce-offer-stripe-sync-blocked.ts';
import { updateCommercePriceStripeSyncMethod } from '../update-commerce-price-stripe-sync.ts';
import { markCommercePriceStripeSyncBlockedMethod } from '../mark-commerce-price-stripe-sync-blocked.ts';
import { recordCommerceGovernanceEventMethod } from '../record-commerce-governance-event.ts';
import { listCommerceGovernanceEventsMethod } from '../list-commerce-governance-events.ts';
import { createCommerceCartMethod } from '../create-commerce-cart.ts';
import { getCommerceCartMethod } from '../get-commerce-cart.ts';
import { listCommerceCartItemsMethod } from '../list-commerce-cart-items.ts';
import { addCommerceCartItemMethod } from '../add-commerce-cart-item.ts';
import { removeCommerceCartItemMethod } from '../remove-commerce-cart-item.ts';
import { clearCommerceCartMethod } from '../clear-commerce-cart.ts';
import { markCommerceCartConvertedMethod } from '../mark-commerce-cart-converted.ts';
import { createCommerceCheckoutMethod } from '../create-commerce-checkout.ts';
import { getCommerceCheckoutMethod } from '../get-commerce-checkout.ts';
import { listCommerceCheckoutOrdersMethod } from '../list-commerce-checkout-orders.ts';
import { updateCommerceCheckoutStatusMethod } from '../update-commerce-checkout-status.ts';
import { createCommerceOrderMethod } from '../create-commerce-order.ts';
import { getCommerceOrderMethod } from '../get-commerce-order.ts';
import { listCommerceOrdersMethod } from '../list-commerce-orders.ts';
import { updateCommerceOrderStatusMethod } from '../update-commerce-order-status.ts';
import { createCommerceOrderItemMethod } from '../create-commerce-order-item.ts';
import { listCommerceOrderItemsMethod } from '../list-commerce-order-items.ts';
import { updateCommerceOrderItemStatusMethod } from '../update-commerce-order-item-status.ts';
import { createCommercePaymentGroupMethod } from '../create-commerce-payment-group.ts';
import { getCommercePaymentGroupMethod } from '../get-commerce-payment-group.ts';
import { getCommercePaymentGroupByStripePaymentIntentMethod } from '../get-commerce-payment-group-by-stripe-payment-intent.ts';
import { getCommercePaymentGroupByStripeSubscriptionMethod } from '../get-commerce-payment-group-by-stripe-subscription.ts';
import { updateCommercePaymentGroupMethod } from '../update-commerce-payment-group.ts';
import { createCommerceSubscriptionMethod } from '../create-commerce-subscription.ts';
import { getCommerceSubscriptionMethod } from '../get-commerce-subscription.ts';
import { getCommerceSubscriptionByStripeIdMethod } from '../get-commerce-subscription-by-stripe-id.ts';
import { updateCommerceSubscriptionFromStripeMethod } from '../update-commerce-subscription-from-stripe.ts';
import { createCommerceEntitlementMethod } from '../create-commerce-entitlement.ts';
import { getCommerceEntitlementMethod } from '../get-commerce-entitlement.ts';
import { listCommerceEntitlementsMethod } from '../list-commerce-entitlements.ts';
import { updateCommerceEntitlementStatusMethod } from '../update-commerce-entitlement-status.ts';
import { activateCommerceEntitlementMethod } from '../activate-commerce-entitlement.ts';
import { suspendCommerceEntitlementMethod } from '../suspend-commerce-entitlement.ts';
import { revokeCommerceEntitlementMethod } from '../revoke-commerce-entitlement.ts';
import { upsertCommerceEntitlementForOrderItemMethod } from '../upsert-commerce-entitlement-for-order-item.ts';
import { updateEntitlementsForSubscriptionMethod } from '../update-entitlements-for-subscription.ts';
import { createCommerceRefundMethod } from '../create-commerce-refund.ts';
import { getCommerceRefundMethod } from '../get-commerce-refund.ts';
import { getCommerceRefundByStripeIdMethod } from '../get-commerce-refund-by-stripe-id.ts';
import { getCommerceRefundByIdempotencyKeyMethod } from '../get-commerce-refund-by-idempotency-key.ts';
import { listCommerceRefundsMethod } from '../list-commerce-refunds.ts';
import { updateCommerceRefundFromStripeMethod } from '../update-commerce-refund-from-stripe.ts';
import { markCommerceOrderRefundStateMethod } from '../mark-commerce-order-refund-state.ts';
import { markCommerceOrderItemRefundStateMethod } from '../mark-commerce-order-item-refund-state.ts';
import { createCommerceFulfillmentEventMethod } from '../create-commerce-fulfillment-event.ts';
import { listCommerceFulfillmentEventsMethod } from '../list-commerce-fulfillment-events.ts';
import { markCommerceOrderItemFulfilledMethod } from '../mark-commerce-order-item-fulfilled.ts';
import { updateCommerceEntitlementFulfillmentMethod } from '../update-commerce-entitlement-fulfillment.ts';
import { buildCommerceOwnershipSnapshotMethod } from '../build-commerce-ownership-snapshot.ts';
import { recordCommerceServiceEventMethod } from '../record-commerce-service-event.ts';
import { recordCommerceServiceGovernanceMethod } from '../record-commerce-service-governance.ts';
import { createCommerceServiceRequestMethod } from '../create-commerce-service-request.ts';
import { getCommerceServiceRequestMethod } from '../get-commerce-service-request.ts';
import { listCommerceServiceRequestsMethod } from '../list-commerce-service-requests.ts';
import { updateCommerceServiceRequestMethod } from '../update-commerce-service-request.ts';
import { transitionCommerceServiceRequestMethod } from '../transition-commerce-service-request.ts';
import { createCommerceServiceQuoteMethod } from '../create-commerce-service-quote.ts';
import { getCommerceServiceQuoteMethod } from '../get-commerce-service-quote.ts';
import { listCommerceServiceQuotesMethod } from '../list-commerce-service-quotes.ts';
import { updateCommerceServiceQuoteStateMethod } from '../update-commerce-service-quote-state.ts';
import { submitCommerceServiceQuoteMethod } from '../submit-commerce-service-quote.ts';
import { approveCommerceServiceQuoteByBuyerMethod } from '../approve-commerce-service-quote-by-buyer.ts';
import { approveCommerceServiceQuoteByVendorMethod } from '../approve-commerce-service-quote-by-vendor.ts';
import { rejectCommerceServiceQuoteMethod } from '../reject-commerce-service-quote.ts';
import { expireCommerceServiceQuoteMethod } from '../expire-commerce-service-quote.ts';
import { createCommerceServiceContractFromQuoteMethod } from '../create-commerce-service-contract-from-quote.ts';
import { getCommerceServiceContractMethod } from '../get-commerce-service-contract.ts';
import { getCommerceServiceContractForRequestMethod } from '../get-commerce-service-contract-for-request.ts';
import { updateCommerceServiceContractMethod } from '../update-commerce-service-contract.ts';
import { attachCommerceServiceOrderMethod } from '../attach-commerce-service-order.ts';
import { activateCommerceServiceContractMethod } from '../activate-commerce-service-contract.ts';
import { fulfillCommerceServiceContractMethod } from '../fulfill-commerce-service-contract.ts';
import { cancelCommerceServiceContractMethod } from '../cancel-commerce-service-contract.ts';
import { linkCommerceServiceContractWorkMethod } from '../link-commerce-service-contract-work.ts';
import { listCommerceServiceEventsMethod } from '../list-commerce-service-events.ts';
import { getCommerceVendorSalesSummaryMethod } from '../get-commerce-vendor-sales-summary.ts';
import { getCommerceVendorCommerceMonitorMethod } from '../get-commerce-vendor-commerce-monitor.ts';
import { listCommerceVendorSalesOrdersMethod } from '../list-commerce-vendor-sales-orders.ts';
import { listCommerceVendorSalesSubscriptionsMethod } from '../list-commerce-vendor-sales-subscriptions.ts';
import { listCommerceVendorSalesEntitlementsMethod } from '../list-commerce-vendor-sales-entitlements.ts';
import { getCommerceBuyerStripeCustomerMethod } from '../get-commerce-buyer-stripe-customer.ts';
import { upsertCommerceBuyerStripeCustomerMethod } from '../upsert-commerce-buyer-stripe-customer.ts';
import { recordCommerceWebhookEventMethod } from '../record-commerce-webhook-event.ts';
import { updateCommerceWebhookEventStatusMethod } from '../update-commerce-webhook-event-status.ts';
import { claimCommerceWebhookEventMethod } from '../claim-commerce-webhook-event.ts';
import { markCommerceWebhookEventProcessedMethod } from '../mark-commerce-webhook-event-processed.ts';
import { markCommerceWebhookEventIgnoredMethod } from '../mark-commerce-webhook-event-ignored.ts';
import { markCommerceWebhookEventFailedMethod } from '../mark-commerce-webhook-event-failed.ts';
import { listTeamProductsMethod } from '../list-team-products.ts';

export function installCommerceStoreMethods(prototype: MarketControlPlaneStore) {
	prototype.getCommerceVendorForTeam = getCommerceVendorForTeamMethod;
	prototype.getCommerceVendor = getCommerceVendorMethod;
	prototype.requestCommerceVendor = requestCommerceVendorMethod;
	prototype.updateCommerceVendor = updateCommerceVendorMethod;
	prototype.approveCommerceVendor = approveCommerceVendorMethod;
	prototype.getCommerceVendorStripeAccount = getCommerceVendorStripeAccountMethod;
	prototype.getCommerceVendorStripeAccountForTeam = getCommerceVendorStripeAccountForTeamMethod;
	prototype.getCommerceVendorStripeAccountByStripeId = getCommerceVendorStripeAccountByStripeIdMethod;
	prototype.createCommerceVendorStripeAccount = createCommerceVendorStripeAccountMethod;
	prototype.updateCommerceVendorStripeAccount = updateCommerceVendorStripeAccountMethod;
	prototype.upsertCommerceVendorStripeAccount = upsertCommerceVendorStripeAccountMethod;
	prototype.markCommerceStripeOnboardingStarted = markCommerceStripeOnboardingStartedMethod;
	prototype.markCommerceStripeOnboardingReturned = markCommerceStripeOnboardingReturnedMethod;
	prototype.recordCommerceStripeAccountStatus = recordCommerceStripeAccountStatusMethod;
	prototype.createCommerceProductDraft = createCommerceProductDraftMethod;
	prototype.getCommerceProduct = getCommerceProductMethod;
	prototype.listCommerceProducts = listCommerceProductsMethod;
	prototype.commerceMarketplaceProductSummary = commerceMarketplaceProductSummaryMethod;
	prototype.listCommerceMarketplaceProducts = listCommerceMarketplaceProductsMethod;
	prototype.getCommerceMarketplaceProduct = getCommerceMarketplaceProductMethod;
	prototype.updateCommerceProduct = updateCommerceProductMethod;
	prototype.transitionCommerceProduct = transitionCommerceProductMethod;
	prototype.submitCommerceProduct = submitCommerceProductMethod;
	prototype.approveCommerceProduct = approveCommerceProductMethod;
	prototype.archiveCommerceProduct = archiveCommerceProductMethod;
	prototype.createCommerceOwnershipRecord = createCommerceOwnershipRecordMethod;
	prototype.listCommerceOwnershipRecords = listCommerceOwnershipRecordsMethod;
	prototype.updateCommerceOwnershipRecord = updateCommerceOwnershipRecordMethod;
	prototype.setCurrentCommerceOwnershipRecord = setCurrentCommerceOwnershipRecordMethod;
	prototype.createCommerceStewardshipAssignment = createCommerceStewardshipAssignmentMethod;
	prototype.listCommerceStewardshipAssignments = listCommerceStewardshipAssignmentsMethod;
	prototype.updateCommerceStewardshipAssignment = updateCommerceStewardshipAssignmentMethod;
	prototype.endCommerceStewardshipAssignment = endCommerceStewardshipAssignmentMethod;
	prototype.createCommerceContribution = createCommerceContributionMethod;
	prototype.listCommerceContributions = listCommerceContributionsMethod;
	prototype.updateCommerceContribution = updateCommerceContributionMethod;
	prototype.createCommerceGovernancePolicy = createCommerceGovernancePolicyMethod;
	prototype.listCommerceGovernancePolicies = listCommerceGovernancePoliciesMethod;
	prototype.updateCommerceGovernancePolicy = updateCommerceGovernancePolicyMethod;
	prototype.createCommerceOwnershipTransfer = createCommerceOwnershipTransferMethod;
	prototype.updateCommerceOwnershipTransferState = updateCommerceOwnershipTransferStateMethod;
	prototype.submitCommerceOwnershipTransfer = submitCommerceOwnershipTransferMethod;
	prototype.approveCommerceOwnershipTransfer = approveCommerceOwnershipTransferMethod;
	prototype.rejectCommerceOwnershipTransfer = rejectCommerceOwnershipTransferMethod;
	prototype.cancelCommerceOwnershipTransfer = cancelCommerceOwnershipTransferMethod;
	prototype.createCommerceSuccessionEvent = createCommerceSuccessionEventMethod;
	prototype.listCommerceSuccessionEvents = listCommerceSuccessionEventsMethod;
	prototype.getCommerceOwnershipWorkflowSummary = getCommerceOwnershipWorkflowSummaryMethod;
	prototype.commerceCapacityOwnershipSnapshot = commerceCapacityOwnershipSnapshotMethod;
	prototype.validateCommerceCapacityProviderDisclosure = validateCommerceCapacityProviderDisclosureMethod;
	prototype.ensureCommerceCapacityListingEligibility = ensureCommerceCapacityListingEligibilityMethod;
	prototype.createCommerceCapacityListing = createCommerceCapacityListingMethod;
	prototype.getCommerceCapacityListing = getCommerceCapacityListingMethod;
	prototype.getCommerceCapacityListingForProduct = getCommerceCapacityListingForProductMethod;
	prototype.listCommerceCapacityListings = listCommerceCapacityListingsMethod;
	prototype.updateCommerceCapacityListing = updateCommerceCapacityListingMethod;
	prototype.transitionCommerceCapacityListing = transitionCommerceCapacityListingMethod;
	prototype.submitCommerceCapacityListing = submitCommerceCapacityListingMethod;
	prototype.approveCommerceCapacityListing = approveCommerceCapacityListingMethod;
	prototype.rejectCommerceCapacityListing = rejectCommerceCapacityListingMethod;
	prototype.suspendCommerceCapacityListing = suspendCommerceCapacityListingMethod;
	prototype.archiveCommerceCapacityListing = archiveCommerceCapacityListingMethod;
	prototype.createCommerceCapacityListingInquiry = createCommerceCapacityListingInquiryMethod;
	prototype.getCommerceCapacityListingInquiry = getCommerceCapacityListingInquiryMethod;
	prototype.listCommerceCapacityListingInquiries = listCommerceCapacityListingInquiriesMethod;
	prototype.transitionCommerceCapacityInquiry = transitionCommerceCapacityInquiryMethod;
	prototype.markCommerceCapacityInquiryReviewing = markCommerceCapacityInquiryReviewingMethod;
	prototype.approveCommerceCapacityInquiryForScoping = approveCommerceCapacityInquiryForScopingMethod;
	prototype.declineCommerceCapacityInquiry = declineCommerceCapacityInquiryMethod;
	prototype.cancelCommerceCapacityInquiry = cancelCommerceCapacityInquiryMethod;
	prototype.createCommerceProductVersion = createCommerceProductVersionMethod;
	prototype.getCommerceProductVersion = getCommerceProductVersionMethod;
	prototype.getCommerceProductVersionById = getCommerceProductVersionByIdMethod;
	prototype.listCommerceProductVersions = listCommerceProductVersionsMethod;
	prototype.transitionCommerceProductVersion = transitionCommerceProductVersionMethod;
	prototype.submitCommerceProductVersion = submitCommerceProductVersionMethod;
	prototype.approveCommerceProductVersion = approveCommerceProductVersionMethod;
	prototype.createCommerceOffer = createCommerceOfferMethod;
	prototype.getCommerceOffer = getCommerceOfferMethod;
	prototype.listCommerceOffers = listCommerceOffersMethod;
	prototype.updateCommerceOffer = updateCommerceOfferMethod;
	prototype.transitionCommerceOffer = transitionCommerceOfferMethod;
	prototype.submitCommerceOffer = submitCommerceOfferMethod;
	prototype.approveCommerceOffer = approveCommerceOfferMethod;
	prototype.archiveCommerceOffer = archiveCommerceOfferMethod;
	prototype.createCommercePrice = createCommercePriceMethod;
	prototype.listCommercePrices = listCommercePricesMethod;
	prototype.getCommercePrice = getCommercePriceMethod;
	prototype.activateCommercePrice = activateCommercePriceMethod;
	prototype.updateCommerceOfferStripeProductSync = updateCommerceOfferStripeProductSyncMethod;
	prototype.markCommerceOfferStripeSyncBlocked = markCommerceOfferStripeSyncBlockedMethod;
	prototype.updateCommercePriceStripeSync = updateCommercePriceStripeSyncMethod;
	prototype.markCommercePriceStripeSyncBlocked = markCommercePriceStripeSyncBlockedMethod;
	prototype.recordCommerceGovernanceEvent = recordCommerceGovernanceEventMethod;
	prototype.listCommerceGovernanceEvents = listCommerceGovernanceEventsMethod;
	prototype.createCommerceCart = createCommerceCartMethod;
	prototype.getCommerceCart = getCommerceCartMethod;
	prototype.listCommerceCartItems = listCommerceCartItemsMethod;
	prototype.addCommerceCartItem = addCommerceCartItemMethod;
	prototype.removeCommerceCartItem = removeCommerceCartItemMethod;
	prototype.clearCommerceCart = clearCommerceCartMethod;
	prototype.markCommerceCartConverted = markCommerceCartConvertedMethod;
	prototype.createCommerceCheckout = createCommerceCheckoutMethod;
	prototype.getCommerceCheckout = getCommerceCheckoutMethod;
	prototype.listCommerceCheckoutOrders = listCommerceCheckoutOrdersMethod;
	prototype.updateCommerceCheckoutStatus = updateCommerceCheckoutStatusMethod;
	prototype.createCommerceOrder = createCommerceOrderMethod;
	prototype.getCommerceOrder = getCommerceOrderMethod;
	prototype.listCommerceOrders = listCommerceOrdersMethod;
	prototype.updateCommerceOrderStatus = updateCommerceOrderStatusMethod;
	prototype.createCommerceOrderItem = createCommerceOrderItemMethod;
	prototype.listCommerceOrderItems = listCommerceOrderItemsMethod;
	prototype.updateCommerceOrderItemStatus = updateCommerceOrderItemStatusMethod;
	prototype.createCommercePaymentGroup = createCommercePaymentGroupMethod;
	prototype.getCommercePaymentGroup = getCommercePaymentGroupMethod;
	prototype.getCommercePaymentGroupByStripePaymentIntent = getCommercePaymentGroupByStripePaymentIntentMethod;
	prototype.getCommercePaymentGroupByStripeSubscription = getCommercePaymentGroupByStripeSubscriptionMethod;
	prototype.updateCommercePaymentGroup = updateCommercePaymentGroupMethod;
	prototype.createCommerceSubscription = createCommerceSubscriptionMethod;
	prototype.getCommerceSubscription = getCommerceSubscriptionMethod;
	prototype.getCommerceSubscriptionByStripeId = getCommerceSubscriptionByStripeIdMethod;
	prototype.updateCommerceSubscriptionFromStripe = updateCommerceSubscriptionFromStripeMethod;
	prototype.createCommerceEntitlement = createCommerceEntitlementMethod;
	prototype.getCommerceEntitlement = getCommerceEntitlementMethod;
	prototype.listCommerceEntitlements = listCommerceEntitlementsMethod;
	prototype.updateCommerceEntitlementStatus = updateCommerceEntitlementStatusMethod;
	prototype.activateCommerceEntitlement = activateCommerceEntitlementMethod;
	prototype.suspendCommerceEntitlement = suspendCommerceEntitlementMethod;
	prototype.revokeCommerceEntitlement = revokeCommerceEntitlementMethod;
	prototype.upsertCommerceEntitlementForOrderItem = upsertCommerceEntitlementForOrderItemMethod;
	prototype.updateEntitlementsForSubscription = updateEntitlementsForSubscriptionMethod;
	prototype.createCommerceRefund = createCommerceRefundMethod;
	prototype.getCommerceRefund = getCommerceRefundMethod;
	prototype.getCommerceRefundByStripeId = getCommerceRefundByStripeIdMethod;
	prototype.getCommerceRefundByIdempotencyKey = getCommerceRefundByIdempotencyKeyMethod;
	prototype.listCommerceRefunds = listCommerceRefundsMethod;
	prototype.updateCommerceRefundFromStripe = updateCommerceRefundFromStripeMethod;
	prototype.markCommerceOrderRefundState = markCommerceOrderRefundStateMethod;
	prototype.markCommerceOrderItemRefundState = markCommerceOrderItemRefundStateMethod;
	prototype.createCommerceFulfillmentEvent = createCommerceFulfillmentEventMethod;
	prototype.listCommerceFulfillmentEvents = listCommerceFulfillmentEventsMethod;
	prototype.markCommerceOrderItemFulfilled = markCommerceOrderItemFulfilledMethod;
	prototype.updateCommerceEntitlementFulfillment = updateCommerceEntitlementFulfillmentMethod;
	prototype.buildCommerceOwnershipSnapshot = buildCommerceOwnershipSnapshotMethod;
	prototype.recordCommerceServiceEvent = recordCommerceServiceEventMethod;
	prototype.recordCommerceServiceGovernance = recordCommerceServiceGovernanceMethod;
	prototype.createCommerceServiceRequest = createCommerceServiceRequestMethod;
	prototype.getCommerceServiceRequest = getCommerceServiceRequestMethod;
	prototype.listCommerceServiceRequests = listCommerceServiceRequestsMethod;
	prototype.updateCommerceServiceRequest = updateCommerceServiceRequestMethod;
	prototype.transitionCommerceServiceRequest = transitionCommerceServiceRequestMethod;
	prototype.createCommerceServiceQuote = createCommerceServiceQuoteMethod;
	prototype.getCommerceServiceQuote = getCommerceServiceQuoteMethod;
	prototype.listCommerceServiceQuotes = listCommerceServiceQuotesMethod;
	prototype.updateCommerceServiceQuoteState = updateCommerceServiceQuoteStateMethod;
	prototype.submitCommerceServiceQuote = submitCommerceServiceQuoteMethod;
	prototype.approveCommerceServiceQuoteByBuyer = approveCommerceServiceQuoteByBuyerMethod;
	prototype.approveCommerceServiceQuoteByVendor = approveCommerceServiceQuoteByVendorMethod;
	prototype.rejectCommerceServiceQuote = rejectCommerceServiceQuoteMethod;
	prototype.expireCommerceServiceQuote = expireCommerceServiceQuoteMethod;
	prototype.createCommerceServiceContractFromQuote = createCommerceServiceContractFromQuoteMethod;
	prototype.getCommerceServiceContract = getCommerceServiceContractMethod;
	prototype.getCommerceServiceContractForRequest = getCommerceServiceContractForRequestMethod;
	prototype.updateCommerceServiceContract = updateCommerceServiceContractMethod;
	prototype.attachCommerceServiceOrder = attachCommerceServiceOrderMethod;
	prototype.activateCommerceServiceContract = activateCommerceServiceContractMethod;
	prototype.fulfillCommerceServiceContract = fulfillCommerceServiceContractMethod;
	prototype.cancelCommerceServiceContract = cancelCommerceServiceContractMethod;
	prototype.linkCommerceServiceContractWork = linkCommerceServiceContractWorkMethod;
	prototype.listCommerceServiceEvents = listCommerceServiceEventsMethod;
	prototype.getCommerceVendorSalesSummary = getCommerceVendorSalesSummaryMethod;
	prototype.getCommerceVendorCommerceMonitor = getCommerceVendorCommerceMonitorMethod;
	prototype.listCommerceVendorSalesOrders = listCommerceVendorSalesOrdersMethod;
	prototype.listCommerceVendorSalesSubscriptions = listCommerceVendorSalesSubscriptionsMethod;
	prototype.listCommerceVendorSalesEntitlements = listCommerceVendorSalesEntitlementsMethod;
	prototype.getCommerceBuyerStripeCustomer = getCommerceBuyerStripeCustomerMethod;
	prototype.upsertCommerceBuyerStripeCustomer = upsertCommerceBuyerStripeCustomerMethod;
	prototype.recordCommerceWebhookEvent = recordCommerceWebhookEventMethod;
	prototype.updateCommerceWebhookEventStatus = updateCommerceWebhookEventStatusMethod;
	prototype.claimCommerceWebhookEvent = claimCommerceWebhookEventMethod;
	prototype.markCommerceWebhookEventProcessed = markCommerceWebhookEventProcessedMethod;
	prototype.markCommerceWebhookEventIgnored = markCommerceWebhookEventIgnoredMethod;
	prototype.markCommerceWebhookEventFailed = markCommerceWebhookEventFailedMethod;
	prototype.listTeamProducts = listTeamProductsMethod;
}
