import type { MarketControlPlaneStore } from '../../store.ts';
import { createProviderCredentialSessionMethod } from '../create-provider-credential-session.ts';
import { getProviderCredentialSessionMethod } from '../get-provider-credential-session.ts';
import { findProviderCredentialSessionMethod } from '../find-provider-credential-session.ts';
import { bindProviderCredentialSessionMethod } from '../bind-provider-credential-session.ts';
import { consumeProviderCredentialSessionMethod } from '../consume-provider-credential-session.ts';
import { markExpiredProviderCredentialSessionsMethod } from '../mark-expired-provider-credential-sessions.ts';
import { cleanupProviderCredentialSessionsMethod } from '../cleanup-provider-credential-sessions.ts';
import { createSecretMetadataRecordMethod } from '../create-secret-metadata-record.ts';
import { getSecretMetadataRecordMethod } from '../get-secret-metadata-record.ts';
import { listSecretMetadataRecordsMethod } from '../list-secret-metadata-records.ts';
import { updateSecretMetadataRecordMethod } from '../update-secret-metadata-record.ts';
import { tombstoneSecretMetadataRecordMethod } from '../tombstone-secret-metadata-record.ts';
import { createClientEncryptedEscrowRecordMethod } from '../create-client-encrypted-escrow-record.ts';
import { getClientEncryptedEscrowRecordMethod } from '../get-client-encrypted-escrow-record.ts';
import { listClientEncryptedEscrowRecordsMethod } from '../list-client-encrypted-escrow-records.ts';
import { updateClientEncryptedEscrowRecordMethod } from '../update-client-encrypted-escrow-record.ts';
import { migrateClientEncryptedEscrowRecordMethod } from '../migrate-client-encrypted-escrow-record.ts';
import { tombstoneClientEncryptedEscrowRecordMethod } from '../tombstone-client-encrypted-escrow-record.ts';
import { upsertGitHubRepositoryGrantMethod } from '../upsert-git-hub-repository-grant.ts';
import { listGitHubRepositoryGrantsMethod } from '../list-git-hub-repository-grants.ts';
import { updateGitHubRepositoryGrantStatusMethod } from '../update-git-hub-repository-grant-status.ts';
import { upsertGitHubAppInstallationRecordMethod } from '../upsert-git-hub-app-installation-record.ts';
import { getGitHubAppInstallationRecordMethod } from '../get-git-hub-app-installation-record.ts';
import { listGitHubAppInstallationRecordsMethod } from '../list-git-hub-app-installation-records.ts';
import { updateGitHubAppInstallationRecordStatusMethod } from '../update-git-hub-app-installation-record-status.ts';
import { recordGitHubAppTokenIssuanceMethod } from '../record-git-hub-app-token-issuance.ts';
import { getGitHubAppTokenIssuanceRecordMethod } from '../get-git-hub-app-token-issuance-record.ts';
import { listGitHubAppTokenIssuanceRecordsMethod } from '../list-git-hub-app-token-issuance-records.ts';
import { updateGitHubAppTokenIssuanceStatusMethod } from '../update-git-hub-app-token-issuance-status.ts';
import { recordSecretCapabilityAuditMethod } from '../record-secret-capability-audit.ts';

export function installCredentialsStoreMethods(prototype: MarketControlPlaneStore) {
	prototype.createProviderCredentialSession = createProviderCredentialSessionMethod;
	prototype.getProviderCredentialSession = getProviderCredentialSessionMethod;
	prototype.findProviderCredentialSession = findProviderCredentialSessionMethod;
	prototype.bindProviderCredentialSession = bindProviderCredentialSessionMethod;
	prototype.consumeProviderCredentialSession = consumeProviderCredentialSessionMethod;
	prototype.markExpiredProviderCredentialSessions = markExpiredProviderCredentialSessionsMethod;
	prototype.cleanupProviderCredentialSessions = cleanupProviderCredentialSessionsMethod;
	prototype.createSecretMetadataRecord = createSecretMetadataRecordMethod;
	prototype.getSecretMetadataRecord = getSecretMetadataRecordMethod;
	prototype.listSecretMetadataRecords = listSecretMetadataRecordsMethod;
	prototype.updateSecretMetadataRecord = updateSecretMetadataRecordMethod;
	prototype.tombstoneSecretMetadataRecord = tombstoneSecretMetadataRecordMethod;
	prototype.createClientEncryptedEscrowRecord = createClientEncryptedEscrowRecordMethod;
	prototype.getClientEncryptedEscrowRecord = getClientEncryptedEscrowRecordMethod;
	prototype.listClientEncryptedEscrowRecords = listClientEncryptedEscrowRecordsMethod;
	prototype.updateClientEncryptedEscrowRecord = updateClientEncryptedEscrowRecordMethod;
	prototype.migrateClientEncryptedEscrowRecord = migrateClientEncryptedEscrowRecordMethod;
	prototype.tombstoneClientEncryptedEscrowRecord = tombstoneClientEncryptedEscrowRecordMethod;
	prototype.upsertGitHubRepositoryGrant = upsertGitHubRepositoryGrantMethod;
	prototype.listGitHubRepositoryGrants = listGitHubRepositoryGrantsMethod;
	prototype.updateGitHubRepositoryGrantStatus = updateGitHubRepositoryGrantStatusMethod;
	prototype.upsertGitHubAppInstallationRecord = upsertGitHubAppInstallationRecordMethod;
	prototype.getGitHubAppInstallationRecord = getGitHubAppInstallationRecordMethod;
	prototype.listGitHubAppInstallationRecords = listGitHubAppInstallationRecordsMethod;
	prototype.updateGitHubAppInstallationRecordStatus = updateGitHubAppInstallationRecordStatusMethod;
	prototype.recordGitHubAppTokenIssuance = recordGitHubAppTokenIssuanceMethod;
	prototype.getGitHubAppTokenIssuanceRecord = getGitHubAppTokenIssuanceRecordMethod;
	prototype.listGitHubAppTokenIssuanceRecords = listGitHubAppTokenIssuanceRecordsMethod;
	prototype.updateGitHubAppTokenIssuanceStatus = updateGitHubAppTokenIssuanceStatusMethod;
	prototype.recordSecretCapabilityAudit = recordSecretCapabilityAuditMethod;
}
