import type { MarketControlPlaneStore } from '../../persistence/store.ts';
import { createProviderCredentialSessionMethod } from '../capacity/providers/creation/create-provider-credential-session.ts';
import { getProviderCredentialSessionMethod } from '../capacity/providers/queries/get-provider-credential-session.ts';
import { findProviderCredentialSessionMethod } from '../capacity/providers/queries/find-provider-credential-session.ts';
import { bindProviderCredentialSessionMethod } from '../capacity/providers/updates/bind-provider-credential-session.ts';
import { consumeProviderCredentialSessionMethod } from '../capacity/providers/contracts/consume-provider-credential-session.ts';
import { markExpiredProviderCredentialSessionsMethod } from '../capacity/providers/updates/mark-expired-provider-credential-sessions.ts';
import { cleanupProviderCredentialSessionsMethod } from '../capacity/providers/retirement/cleanup-provider-credential-sessions.ts';
import { createSecretMetadataRecordMethod } from '../configuration/creation/create-secret-metadata-record.ts';
import { getSecretMetadataRecordMethod } from '../configuration/queries/get-secret-metadata-record.ts';
import { listSecretMetadataRecordsMethod } from '../configuration/queries/list-secret-metadata-records.ts';
import { updateSecretMetadataRecordMethod } from '../configuration/updates/update-secret-metadata-record.ts';
import { tombstoneSecretMetadataRecordMethod } from '../configuration/retirement/tombstone-secret-metadata-record.ts';
import { createClientEncryptedEscrowRecordMethod } from '../support/creation/create-client-encrypted-escrow-record.ts';
import { getClientEncryptedEscrowRecordMethod } from '../support/queries/get-client-encrypted-escrow-record.ts';
import { listClientEncryptedEscrowRecordsMethod } from '../support/queries/list-client-encrypted-escrow-records.ts';
import { updateClientEncryptedEscrowRecordMethod } from '../support/updates/update-client-encrypted-escrow-record.ts';
import { migrateClientEncryptedEscrowRecordMethod } from '../support/updates/migrate-client-encrypted-escrow-record.ts';
import { tombstoneClientEncryptedEscrowRecordMethod } from '../support/retirement/tombstone-client-encrypted-escrow-record.ts';
import { upsertGitHubRepositoryGrantMethod } from '../capacity/allocations/creation/upsert-git-hub-repository-grant.ts';
import { listGitHubRepositoryGrantsMethod } from '../capacity/allocations/queries/list-git-hub-repository-grants.ts';
import { updateGitHubRepositoryGrantStatusMethod } from '../capacity/allocations/updates/update-git-hub-repository-grant-status.ts';
import { upsertGitHubAppInstallationRecordMethod } from '../repositories/creation/upsert-git-hub-app-installation-record.ts';
import { getGitHubAppInstallationRecordMethod } from '../repositories/queries/get-git-hub-app-installation-record.ts';
import { listGitHubAppInstallationRecordsMethod } from '../repositories/queries/list-git-hub-app-installation-records.ts';
import { updateGitHubAppInstallationRecordStatusMethod } from '../repositories/updates/update-git-hub-app-installation-record-status.ts';
import { recordGitHubAppTokenIssuanceMethod } from '../accounts/updates/record-git-hub-app-token-issuance.ts';
import { getGitHubAppTokenIssuanceRecordMethod } from '../accounts/queries/get-git-hub-app-token-issuance-record.ts';
import { listGitHubAppTokenIssuanceRecordsMethod } from '../accounts/queries/list-git-hub-app-token-issuance-records.ts';
import { updateGitHubAppTokenIssuanceStatusMethod } from '../accounts/updates/update-git-hub-app-token-issuance-status.ts';
import { recordSecretCapabilityAuditMethod } from '../configuration/updates/record-secret-capability-audit.ts';

export function installCredentialsStoreMethods(prototype: MarketControlPlaneStore) {
	prototype.createProviderCredentialSession = createProviderCredentialSessionMethod;
	prototype.getProviderCredentialSession = getProviderCredentialSessionMethod;
	prototype.findProviderCredentialSession = findProviderCredentialSessionMethod;
	prototype.bindProviderCredentialSession = bindProviderCredentialSessionMethod;
	prototype.consumeProviderCredentialSession = consumeProviderCredentialSessionMethod;
	prototype.markExpiredProviderCredentialSessions = markExpiredProviderCredentialSessionsMethod;
	prototype.cleanupProviderCredentialSessions = cleanupProviderCredentialSessionsMethod;
	prototype.createSecretMetadataRecord = createSecretMetadataRecordMethod;
	prototype.getSecretMetadataRecord = getSecretMetadataRecordMethod;
	prototype.listSecretMetadataRecords = listSecretMetadataRecordsMethod;
	prototype.updateSecretMetadataRecord = updateSecretMetadataRecordMethod;
	prototype.tombstoneSecretMetadataRecord = tombstoneSecretMetadataRecordMethod;
	prototype.createClientEncryptedEscrowRecord = createClientEncryptedEscrowRecordMethod;
	prototype.getClientEncryptedEscrowRecord = getClientEncryptedEscrowRecordMethod;
	prototype.listClientEncryptedEscrowRecords = listClientEncryptedEscrowRecordsMethod;
	prototype.updateClientEncryptedEscrowRecord = updateClientEncryptedEscrowRecordMethod;
	prototype.migrateClientEncryptedEscrowRecord = migrateClientEncryptedEscrowRecordMethod;
	prototype.tombstoneClientEncryptedEscrowRecord = tombstoneClientEncryptedEscrowRecordMethod;
	prototype.upsertGitHubRepositoryGrant = upsertGitHubRepositoryGrantMethod;
	prototype.listGitHubRepositoryGrants = listGitHubRepositoryGrantsMethod;
	prototype.updateGitHubRepositoryGrantStatus = updateGitHubRepositoryGrantStatusMethod;
	prototype.upsertGitHubAppInstallationRecord = upsertGitHubAppInstallationRecordMethod;
	prototype.getGitHubAppInstallationRecord = getGitHubAppInstallationRecordMethod;
	prototype.listGitHubAppInstallationRecords = listGitHubAppInstallationRecordsMethod;
	prototype.updateGitHubAppInstallationRecordStatus = updateGitHubAppInstallationRecordStatusMethod;
	prototype.recordGitHubAppTokenIssuance = recordGitHubAppTokenIssuanceMethod;
	prototype.getGitHubAppTokenIssuanceRecord = getGitHubAppTokenIssuanceRecordMethod;
	prototype.listGitHubAppTokenIssuanceRecords = listGitHubAppTokenIssuanceRecordsMethod;
	prototype.updateGitHubAppTokenIssuanceStatus = updateGitHubAppTokenIssuanceStatusMethod;
	prototype.recordSecretCapabilityAudit = recordSecretCapabilityAuditMethod;
}
