import type { MarketControlPlaneStore } from '../../persistence/store.ts';
import { runMethod } from '../support/contracts/run.ts';
import { firstMethod } from '../support/contracts/first.ts';
import { allMethod } from '../all.ts';
import { batchMethod } from '../support/contracts/batch.ts';
import { ensureInitializedMethod } from '../support/contracts/ensure-initialized.ts';
import { listRepositoryHostsMethod } from '../hosting/queries/list-repository-hosts.ts';
import { getRepositoryHostMethod } from '../hosting/queries/get-repository-host.ts';
import { upsertRepositoryHostMethod } from '../hosting/creation/upsert-repository-host.ts';
import { deleteRepositoryHostMethod } from '../hosting/retirement/delete-repository-host.ts';
import { buildRepositoryTopologySnapshotMethod } from '../repositories/creation/build-repository-topology-snapshot.ts';
import { upsertHubRepositoryMethod } from '../repositories/creation/upsert-hub-repository.ts';
import { listHubRepositoriesMethod } from '../support/queries/list-hub-repositories.ts';
import { upsertHubContentSourceMethod } from '../content/creation/upsert-hub-content-source.ts';
import { getHubContentSourceMethod } from '../content/queries/get-hub-content-source.ts';
import { createHubLaunchMethod } from '../support/creation/create-hub-launch.ts';
import { getHubLaunchMethod } from '../support/queries/get-hub-launch.ts';
import { getLatestHubLaunchForHubMethod } from '../testing/queries/get-latest-hub-launch-for-hub.ts';
import { updateHubLaunchMethod } from '../support/updates/update-hub-launch.ts';
import { appendHubLaunchEventMethod } from '../support/contracts/append-hub-launch-event.ts';
import { listHubLaunchEventsMethod } from '../support/queries/list-hub-launch-events.ts';
import { upsertHubWorkspaceLinkMethod } from '../treedx/workspaces/creation/upsert-hub-workspace-link.ts';
import { listHubWorkspaceLinksMethod } from '../treedx/workspaces/queries/list-hub-workspace-links.ts';
import { getEffectiveCapabilityMethod } from '../support/queries/get-effective-capability.ts';
import { createWorkflowDispatchRecordMethod } from '../operations/creation/create-workflow-dispatch-record.ts';
import { getWorkflowDispatchRecordMethod } from '../operations/queries/workflows/get-workflow-dispatch-record.ts';
import { updateWorkflowDispatchRecordMethod } from '../operations/updates/update-workflow-dispatch-record.ts';
import { recordAuditEventMethod } from '../support/updates/record-audit-event.ts';
import { listAuditEventsForTargetMethod } from '../support/queries/list-audit-events-for-target.ts';
import { listRecentAuditEventsMethod } from '../support/queries/list-recent-audit-events.ts';

export function installFoundationStoreMethods(prototype: MarketControlPlaneStore) {
	prototype.run = runMethod;
	prototype.first = firstMethod;
	prototype.all = allMethod;
	prototype.batch = batchMethod;
	prototype.ensureInitialized = ensureInitializedMethod;
	prototype.listRepositoryHosts = listRepositoryHostsMethod;
	prototype.getRepositoryHost = getRepositoryHostMethod;
	prototype.upsertRepositoryHost = upsertRepositoryHostMethod;
	prototype.deleteRepositoryHost = deleteRepositoryHostMethod;
	prototype.buildRepositoryTopologySnapshot = buildRepositoryTopologySnapshotMethod;
	prototype.upsertHubRepository = upsertHubRepositoryMethod;
	prototype.listHubRepositories = listHubRepositoriesMethod;
	prototype.upsertHubContentSource = upsertHubContentSourceMethod;
	prototype.getHubContentSource = getHubContentSourceMethod;
	prototype.createHubLaunch = createHubLaunchMethod;
	prototype.getHubLaunch = getHubLaunchMethod;
	prototype.getLatestHubLaunchForHub = getLatestHubLaunchForHubMethod;
	prototype.updateHubLaunch = updateHubLaunchMethod;
	prototype.appendHubLaunchEvent = appendHubLaunchEventMethod;
	prototype.listHubLaunchEvents = listHubLaunchEventsMethod;
	prototype.upsertHubWorkspaceLink = upsertHubWorkspaceLinkMethod;
	prototype.listHubWorkspaceLinks = listHubWorkspaceLinksMethod;
	prototype.getEffectiveCapability = getEffectiveCapabilityMethod;
	prototype.createWorkflowDispatchRecord = createWorkflowDispatchRecordMethod;
	prototype.getWorkflowDispatchRecord = getWorkflowDispatchRecordMethod;
	prototype.updateWorkflowDispatchRecord = updateWorkflowDispatchRecordMethod;
	prototype.recordAuditEvent = recordAuditEventMethod;
	prototype.listAuditEventsForTarget = listAuditEventsForTargetMethod;
	prototype.listRecentAuditEvents = listRecentAuditEventsMethod;
}
