import type { MarketControlPlaneStore } from '../../store.ts';
import { runMethod } from '../run.ts';
import { firstMethod } from '../first.ts';
import { allMethod } from '../all.ts';
import { batchMethod } from '../batch.ts';
import { ensureInitializedMethod } from '../ensure-initialized.ts';
import { listRepositoryHostsMethod } from '../list-repository-hosts.ts';
import { getRepositoryHostMethod } from '../get-repository-host.ts';
import { upsertRepositoryHostMethod } from '../upsert-repository-host.ts';
import { deleteRepositoryHostMethod } from '../delete-repository-host.ts';
import { buildRepositoryTopologySnapshotMethod } from '../build-repository-topology-snapshot.ts';
import { upsertHubRepositoryMethod } from '../upsert-hub-repository.ts';
import { listHubRepositoriesMethod } from '../list-hub-repositories.ts';
import { upsertHubContentSourceMethod } from '../upsert-hub-content-source.ts';
import { getHubContentSourceMethod } from '../get-hub-content-source.ts';
import { createHubLaunchMethod } from '../create-hub-launch.ts';
import { getHubLaunchMethod } from '../get-hub-launch.ts';
import { getLatestHubLaunchForHubMethod } from '../get-latest-hub-launch-for-hub.ts';
import { updateHubLaunchMethod } from '../update-hub-launch.ts';
import { appendHubLaunchEventMethod } from '../append-hub-launch-event.ts';
import { listHubLaunchEventsMethod } from '../list-hub-launch-events.ts';
import { upsertHubWorkspaceLinkMethod } from '../upsert-hub-workspace-link.ts';
import { listHubWorkspaceLinksMethod } from '../list-hub-workspace-links.ts';
import { getEffectiveCapabilityMethod } from '../get-effective-capability.ts';
import { createWorkflowDispatchRecordMethod } from '../create-workflow-dispatch-record.ts';
import { getWorkflowDispatchRecordMethod } from '../get-workflow-dispatch-record.ts';
import { updateWorkflowDispatchRecordMethod } from '../update-workflow-dispatch-record.ts';
import { recordAuditEventMethod } from '../record-audit-event.ts';
import { listAuditEventsForTargetMethod } from '../list-audit-events-for-target.ts';
import { listRecentAuditEventsMethod } from '../list-recent-audit-events.ts';

export function installFoundationStoreMethods(prototype: MarketControlPlaneStore) {
	prototype.run = runMethod;
	prototype.first = firstMethod;
	prototype.all = allMethod;
	prototype.batch = batchMethod;
	prototype.ensureInitialized = ensureInitializedMethod;
	prototype.listRepositoryHosts = listRepositoryHostsMethod;
	prototype.getRepositoryHost = getRepositoryHostMethod;
	prototype.upsertRepositoryHost = upsertRepositoryHostMethod;
	prototype.deleteRepositoryHost = deleteRepositoryHostMethod;
	prototype.buildRepositoryTopologySnapshot = buildRepositoryTopologySnapshotMethod;
	prototype.upsertHubRepository = upsertHubRepositoryMethod;
	prototype.listHubRepositories = listHubRepositoriesMethod;
	prototype.upsertHubContentSource = upsertHubContentSourceMethod;
	prototype.getHubContentSource = getHubContentSourceMethod;
	prototype.createHubLaunch = createHubLaunchMethod;
	prototype.getHubLaunch = getHubLaunchMethod;
	prototype.getLatestHubLaunchForHub = getLatestHubLaunchForHubMethod;
	prototype.updateHubLaunch = updateHubLaunchMethod;
	prototype.appendHubLaunchEvent = appendHubLaunchEventMethod;
	prototype.listHubLaunchEvents = listHubLaunchEventsMethod;
	prototype.upsertHubWorkspaceLink = upsertHubWorkspaceLinkMethod;
	prototype.listHubWorkspaceLinks = listHubWorkspaceLinksMethod;
	prototype.getEffectiveCapability = getEffectiveCapabilityMethod;
	prototype.createWorkflowDispatchRecord = createWorkflowDispatchRecordMethod;
	prototype.getWorkflowDispatchRecord = getWorkflowDispatchRecordMethod;
	prototype.updateWorkflowDispatchRecord = updateWorkflowDispatchRecordMethod;
	prototype.recordAuditEvent = recordAuditEventMethod;
	prototype.listAuditEventsForTarget = listAuditEventsForTargetMethod;
	prototype.listRecentAuditEvents = listRecentAuditEventsMethod;
}
