import type { MarketControlPlaneStore } from '../../store.ts';
import { recordGovernanceEventMethod } from '../record-governance-event.ts';
import { getTeamGovernancePolicyMethod } from '../get-team-governance-policy.ts';
import { ensureDefaultTeamGovernancePolicyMethod } from '../ensure-default-team-governance-policy.ts';
import { setTeamGovernancePolicyMethod } from '../set-team-governance-policy.ts';
import { getProjectGovernancePolicyMethod } from '../get-project-governance-policy.ts';
import { setProjectGovernancePolicyMethod } from '../set-project-governance-policy.ts';
import { resolveGovernancePolicyMethod } from '../resolve-governance-policy.ts';
import { createGovernanceProposalMethod } from '../create-governance-proposal.ts';
import { getGovernanceProposalMethod } from '../get-governance-proposal.ts';
import { listGovernanceProposalsMethod } from '../list-governance-proposals.ts';
import { updateGovernanceProposalDraftMethod } from '../update-governance-proposal-draft.ts';
import { openGovernanceProposalMethod } from '../open-governance-proposal.ts';
import { transitionGovernanceProposalMethod } from '../transition-governance-proposal.ts';
import { governanceEligibleVotersMethod } from '../governance-eligible-voters.ts';
import { activeGovernanceDelegationSnapshotsMethod } from '../active-governance-delegation-snapshots.ts';
import { snapshotGovernanceElectorateMethod } from '../snapshot-governance-electorate.ts';
import { startGovernanceProposalVotingMethod } from '../start-governance-proposal-voting.ts';
import { latestGovernanceElectorateSnapshotMethod } from '../latest-governance-electorate-snapshot.ts';
import { listGovernanceProposalVotesMethod } from '../list-governance-proposal-votes.ts';
import { effectiveGovernanceVotesMethod } from '../effective-governance-votes.ts';
import { voteGovernanceProposalMethod } from '../vote-governance-proposal.ts';
import { evaluateGovernanceProposalMethod } from '../evaluate-governance-proposal.ts';
import { adminDecideGovernanceProposalMethod } from '../admin-decide-governance-proposal.ts';
import { withdrawGovernanceProposalMethod } from '../withdraw-governance-proposal.ts';
import { supersedeGovernanceProposalMethod } from '../supersede-governance-proposal.ts';
import { createGovernanceDecisionFromProposalMethod } from '../create-governance-decision-from-proposal.ts';
import { getGovernanceDecisionMethod } from '../get-governance-decision.ts';
import { listGovernanceDecisionsMethod } from '../list-governance-decisions.ts';
import { listGovernanceEventsMethod } from '../list-governance-events.ts';
import { createGovernanceDelegationMethod } from '../create-governance-delegation.ts';
import { listGovernanceDelegationsMethod } from '../list-governance-delegations.ts';
import { revokeGovernanceDelegationMethod } from '../revoke-governance-delegation.ts';
import { createApprovalRequestMethod } from '../create-approval-request.ts';
import { getApprovalRequestMethod } from '../get-approval-request.ts';
import { listApprovalRequestsForProjectMethod } from '../list-approval-requests-for-project.ts';
import { listApprovalRequestsForTeamMethod } from '../list-approval-requests-for-team.ts';
import { decideApprovalRequestMethod } from '../decide-approval-request.ts';
import { ensureCommonsTreeSeedTeamMethod } from '../ensure-commons-tree-seed-team.ts';
import { recordCommonsGovernanceEventMethod } from '../record-commons-governance-event.ts';
import { getCommonsParticipantByUserIdMethod } from '../get-commons-participant-by-user-id.ts';
import { getCommonsParticipantMethod } from '../get-commons-participant.ts';
import { ensureCommonsParticipantForPrincipalMethod } from '../ensure-commons-participant-for-principal.ts';
import { computeCommonsWeightsMethod } from '../compute-commons-weights.ts';
import { createCommonsWeightSnapshotMethod } from '../create-commons-weight-snapshot.ts';
import { listCommonsParticipantsMethod } from '../list-commons-participants.ts';
import { createCommonsQuestionMethod } from '../create-commons-question.ts';
import { getCommonsQuestionMethod } from '../get-commons-question.ts';
import { listCommonsQuestionsMethod } from '../list-commons-questions.ts';
import { answerCommonsQuestionMethod } from '../answer-commons-question.ts';
import { createCommonsProposalMethod } from '../create-commons-proposal.ts';
import { getCommonsProposalMethod } from '../get-commons-proposal.ts';
import { listCommonsProposalsMethod } from '../list-commons-proposals.ts';
import { transitionCommonsProposalMethod } from '../transition-commons-proposal.ts';
import { submitCommonsProposalMethod } from '../submit-commons-proposal.ts';
import { backCommonsProposalMethod } from '../back-commons-proposal.ts';
import { voteCommonsProposalMethod } from '../vote-commons-proposal.ts';
import { recalculateCommonsProposalVoteTotalsMethod } from '../recalculate-commons-proposal-vote-totals.ts';
import { stewardDecisionForCommonsProposalMethod } from '../steward-decision-for-commons-proposal.ts';
import { listCommonsProposalBackingsMethod } from '../list-commons-proposal-backings.ts';
import { listCommonsProposalVotesMethod } from '../list-commons-proposal-votes.ts';
import { createCommonsDelegationMethod } from '../create-commons-delegation.ts';
import { listCommonsDelegationsMethod } from '../list-commons-delegations.ts';
import { revokeCommonsDelegationMethod } from '../revoke-commons-delegation.ts';
import { listCommonsDecisionsMethod } from '../list-commons-decisions.ts';
import { listCommonsGovernanceEventsMethod } from '../list-commons-governance-events.ts';
import { commonsSummaryMethod } from '../commons-summary.ts';

export function installGovernanceStoreMethods(prototype: MarketControlPlaneStore) {
	prototype.recordGovernanceEvent = recordGovernanceEventMethod;
	prototype.getTeamGovernancePolicy = getTeamGovernancePolicyMethod;
	prototype.ensureDefaultTeamGovernancePolicy = ensureDefaultTeamGovernancePolicyMethod;
	prototype.setTeamGovernancePolicy = setTeamGovernancePolicyMethod;
	prototype.getProjectGovernancePolicy = getProjectGovernancePolicyMethod;
	prototype.setProjectGovernancePolicy = setProjectGovernancePolicyMethod;
	prototype.resolveGovernancePolicy = resolveGovernancePolicyMethod;
	prototype.createGovernanceProposal = createGovernanceProposalMethod;
	prototype.getGovernanceProposal = getGovernanceProposalMethod;
	prototype.listGovernanceProposals = listGovernanceProposalsMethod;
	prototype.updateGovernanceProposalDraft = updateGovernanceProposalDraftMethod;
	prototype.openGovernanceProposal = openGovernanceProposalMethod;
	prototype.transitionGovernanceProposal = transitionGovernanceProposalMethod;
	prototype.governanceEligibleVoters = governanceEligibleVotersMethod;
	prototype.activeGovernanceDelegationSnapshots = activeGovernanceDelegationSnapshotsMethod;
	prototype.snapshotGovernanceElectorate = snapshotGovernanceElectorateMethod;
	prototype.startGovernanceProposalVoting = startGovernanceProposalVotingMethod;
	prototype.latestGovernanceElectorateSnapshot = latestGovernanceElectorateSnapshotMethod;
	prototype.listGovernanceProposalVotes = listGovernanceProposalVotesMethod;
	prototype.effectiveGovernanceVotes = effectiveGovernanceVotesMethod;
	prototype.voteGovernanceProposal = voteGovernanceProposalMethod;
	prototype.evaluateGovernanceProposal = evaluateGovernanceProposalMethod;
	prototype.adminDecideGovernanceProposal = adminDecideGovernanceProposalMethod;
	prototype.withdrawGovernanceProposal = withdrawGovernanceProposalMethod;
	prototype.supersedeGovernanceProposal = supersedeGovernanceProposalMethod;
	prototype.createGovernanceDecisionFromProposal = createGovernanceDecisionFromProposalMethod;
	prototype.getGovernanceDecision = getGovernanceDecisionMethod;
	prototype.listGovernanceDecisions = listGovernanceDecisionsMethod;
	prototype.listGovernanceEvents = listGovernanceEventsMethod;
	prototype.createGovernanceDelegation = createGovernanceDelegationMethod;
	prototype.listGovernanceDelegations = listGovernanceDelegationsMethod;
	prototype.revokeGovernanceDelegation = revokeGovernanceDelegationMethod;
	prototype.createApprovalRequest = createApprovalRequestMethod;
	prototype.getApprovalRequest = getApprovalRequestMethod;
	prototype.listApprovalRequestsForProject = listApprovalRequestsForProjectMethod;
	prototype.listApprovalRequestsForTeam = listApprovalRequestsForTeamMethod;
	prototype.decideApprovalRequest = decideApprovalRequestMethod;
	prototype.ensureCommonsTreeSeedTeam = ensureCommonsTreeSeedTeamMethod;
	prototype.recordCommonsGovernanceEvent = recordCommonsGovernanceEventMethod;
	prototype.getCommonsParticipantByUserId = getCommonsParticipantByUserIdMethod;
	prototype.getCommonsParticipant = getCommonsParticipantMethod;
	prototype.ensureCommonsParticipantForPrincipal = ensureCommonsParticipantForPrincipalMethod;
	prototype.computeCommonsWeights = computeCommonsWeightsMethod;
	prototype.createCommonsWeightSnapshot = createCommonsWeightSnapshotMethod;
	prototype.listCommonsParticipants = listCommonsParticipantsMethod;
	prototype.createCommonsQuestion = createCommonsQuestionMethod;
	prototype.getCommonsQuestion = getCommonsQuestionMethod;
	prototype.listCommonsQuestions = listCommonsQuestionsMethod;
	prototype.answerCommonsQuestion = answerCommonsQuestionMethod;
	prototype.createCommonsProposal = createCommonsProposalMethod;
	prototype.getCommonsProposal = getCommonsProposalMethod;
	prototype.listCommonsProposals = listCommonsProposalsMethod;
	prototype.transitionCommonsProposal = transitionCommonsProposalMethod;
	prototype.submitCommonsProposal = submitCommonsProposalMethod;
	prototype.backCommonsProposal = backCommonsProposalMethod;
	prototype.voteCommonsProposal = voteCommonsProposalMethod;
	prototype.recalculateCommonsProposalVoteTotals = recalculateCommonsProposalVoteTotalsMethod;
	prototype.stewardDecisionForCommonsProposal = stewardDecisionForCommonsProposalMethod;
	prototype.listCommonsProposalBackings = listCommonsProposalBackingsMethod;
	prototype.listCommonsProposalVotes = listCommonsProposalVotesMethod;
	prototype.createCommonsDelegation = createCommonsDelegationMethod;
	prototype.listCommonsDelegations = listCommonsDelegationsMethod;
	prototype.revokeCommonsDelegation = revokeCommonsDelegationMethod;
	prototype.listCommonsDecisions = listCommonsDecisionsMethod;
	prototype.listCommonsGovernanceEvents = listCommonsGovernanceEventsMethod;
	prototype.commonsSummary = commonsSummaryMethod;
}
