import type { MarketControlPlaneStore } from '../../persistence/store.ts';
import { recordGovernanceEventMethod } from '../governance/policy/updates/record-governance-event.ts';
import { getTeamGovernancePolicyMethod } from '../governance/policy/queries/policy/get-team-governance-policy.ts';
import { ensureDefaultTeamGovernancePolicyMethod } from '../governance/policy/contracts/ensure-default-team-governance-policy.ts';
import { setTeamGovernancePolicyMethod } from '../governance/policy/updates/set-team-governance-policy.ts';
import { getProjectGovernancePolicyMethod } from '../projects/queries/governance/get-project-governance-policy.ts';
import { setProjectGovernancePolicyMethod } from '../projects/projects-core/updates/set-project-governance-policy.ts';
import { resolveGovernancePolicyMethod } from '../governance/policy/queries/policy/resolve-governance-policy.ts';
import { createGovernanceProposalMethod } from '../governance/policy/creation/create-governance-proposal.ts';
import { getGovernanceProposalMethod } from '../governance/policy/queries/proposals/get-governance-proposal.ts';
import { listGovernanceProposalsMethod } from '../governance/policy/queries/proposals/list-governance-proposals.ts';
import { updateGovernanceProposalDraftMethod } from '../governance/policy/updates/update-governance-proposal-draft.ts';
import { openGovernanceProposalMethod } from '../governance/policy/lifecycle/open-governance-proposal.ts';
import { transitionGovernanceProposalMethod } from '../governance/policy/updates/transition-governance-proposal.ts';
import { governanceEligibleVotersMethod } from '../governance/policy/contracts/governance-eligible-voters.ts';
import { activeGovernanceDelegationSnapshotsMethod } from '../governance/policy/contracts/active-governance-delegation-snapshots.ts';
import { snapshotGovernanceElectorateMethod } from '../governance/policy/contracts/snapshot-governance-electorate.ts';
import { startGovernanceProposalVotingMethod } from '../governance/policy/creation/start-governance-proposal-voting.ts';
import { latestGovernanceElectorateSnapshotMethod } from '../governance/policy/queries/policy/latest-governance-electorate-snapshot.ts';
import { listGovernanceProposalVotesMethod } from '../governance/policy/queries/proposals/list-governance-proposal-votes.ts';
import { effectiveGovernanceVotesMethod } from '../governance/policy/queries/proposals/effective-governance-votes.ts';
import { voteGovernanceProposalMethod } from '../governance/policy/lifecycle/vote-governance-proposal.ts';
import { evaluateGovernanceProposalMethod } from '../governance/policy/contracts/evaluate-governance-proposal.ts';
import { adminDecideGovernanceProposalMethod } from '../governance/policy/contracts/admin-decide-governance-proposal.ts';
import { withdrawGovernanceProposalMethod } from '../governance/policy/retirement/withdraw-governance-proposal.ts';
import { supersedeGovernanceProposalMethod } from '../governance/policy/updates/supersede-governance-proposal.ts';
import { createGovernanceDecisionFromProposalMethod } from '../governance/policy/creation/create-governance-decision-from-proposal.ts';
import { getGovernanceDecisionMethod } from '../governance/policy/queries/decisions/get-governance-decision.ts';
import { listGovernanceDecisionsMethod } from '../governance/policy/queries/decisions/list-governance-decisions.ts';
import { listGovernanceEventsMethod } from '../governance/policy/queries/events/list-governance-events.ts';
import { createGovernanceDelegationMethod } from '../governance/policy/creation/create-governance-delegation.ts';
import { listGovernanceDelegationsMethod } from '../governance/policy/queries/delegations/list-governance-delegations.ts';
import { revokeGovernanceDelegationMethod } from '../governance/policy/retirement/revoke-governance-delegation.ts';
import { createApprovalRequestMethod } from '../support/creation/create-approval-request.ts';
import { getApprovalRequestMethod } from '../support/queries/get-approval-request.ts';
import { listApprovalRequestsForProjectMethod } from '../projects/queries/governance/list-approval-requests-for-project.ts';
import { listApprovalRequestsForTeamMethod } from '../teams/queries/identity/list-approval-requests-for-team.ts';
import { decideApprovalRequestMethod } from '../support/lifecycle/decide-approval-request.ts';
import { ensureCommonsTeamMethod } from '../governance/commons/contracts/ensure-commons-team.ts';
import { recordCommonsGovernanceEventMethod } from '../governance/commons/updates/record-commons-governance-event.ts';
import { getCommonsParticipantByUserIdMethod } from '../governance/commons/queries/participants/get-commons-participant-by-user-id.ts';
import { getCommonsParticipantMethod } from '../governance/commons/queries/participants/get-commons-participant.ts';
import { ensureCommonsParticipantForPrincipalMethod } from '../governance/commons/contracts/ensure-commons-participant-for-principal.ts';
import { computeCommonsWeightsMethod } from '../governance/commons/contracts/compute-commons-weights.ts';
import { createCommonsWeightSnapshotMethod } from '../governance/commons/creation/create-commons-weight-snapshot.ts';
import { listCommonsParticipantsMethod } from '../governance/commons/queries/participants/list-commons-participants.ts';
import { createCommonsQuestionMethod } from '../governance/commons/creation/create-commons-question.ts';
import { getCommonsQuestionMethod } from '../governance/commons/queries/questions/get-commons-question.ts';
import { listCommonsQuestionsMethod } from '../governance/commons/queries/questions/list-commons-questions.ts';
import { answerCommonsQuestionMethod } from '../governance/commons/contracts/answer-commons-question.ts';
import { createCommonsProposalMethod } from '../governance/commons/creation/create-commons-proposal.ts';
import { getCommonsProposalMethod } from '../governance/commons/queries/proposals/get-commons-proposal.ts';
import { listCommonsProposalsMethod } from '../governance/commons/queries/proposals/list-commons-proposals.ts';
import { transitionCommonsProposalMethod } from '../governance/commons/updates/transition-commons-proposal.ts';
import { submitCommonsProposalMethod } from '../governance/commons/creation/submit-commons-proposal.ts';
import { backCommonsProposalMethod } from '../governance/commons/lifecycle/back-commons-proposal.ts';
import { voteCommonsProposalMethod } from '../governance/commons/lifecycle/vote-commons-proposal.ts';
import { recalculateCommonsProposalVoteTotalsMethod } from '../governance/commons/contracts/recalculate-commons-proposal-vote-totals.ts';
import { stewardDecisionForCommonsProposalMethod } from '../governance/commons/lifecycle/steward-decision-for-commons-proposal.ts';
import { listCommonsProposalBackingsMethod } from '../governance/commons/queries/proposals/list-commons-proposal-backings.ts';
import { listCommonsProposalVotesMethod } from '../governance/commons/queries/proposals/list-commons-proposal-votes.ts';
import { createCommonsDelegationMethod } from '../governance/commons/creation/create-commons-delegation.ts';
import { listCommonsDelegationsMethod } from '../governance/commons/queries/governance/list-commons-delegations.ts';
import { revokeCommonsDelegationMethod } from '../governance/commons/retirement/revoke-commons-delegation.ts';
import { listCommonsDecisionsMethod } from '../governance/commons/queries/governance/list-commons-decisions.ts';
import { listCommonsGovernanceEventsMethod } from '../governance/commons/queries/governance/list-commons-governance-events.ts';
import { commonsSummaryMethod } from '../governance/commons/contracts/commons-summary.ts';

export function installGovernanceStoreMethods(prototype: MarketControlPlaneStore) {
	prototype.recordGovernanceEvent = recordGovernanceEventMethod;
	prototype.getTeamGovernancePolicy = getTeamGovernancePolicyMethod;
	prototype.ensureDefaultTeamGovernancePolicy = ensureDefaultTeamGovernancePolicyMethod;
	prototype.setTeamGovernancePolicy = setTeamGovernancePolicyMethod;
	prototype.getProjectGovernancePolicy = getProjectGovernancePolicyMethod;
	prototype.setProjectGovernancePolicy = setProjectGovernancePolicyMethod;
	prototype.resolveGovernancePolicy = resolveGovernancePolicyMethod;
	prototype.createGovernanceProposal = createGovernanceProposalMethod;
	prototype.getGovernanceProposal = getGovernanceProposalMethod;
	prototype.listGovernanceProposals = listGovernanceProposalsMethod;
	prototype.updateGovernanceProposalDraft = updateGovernanceProposalDraftMethod;
	prototype.openGovernanceProposal = openGovernanceProposalMethod;
	prototype.transitionGovernanceProposal = transitionGovernanceProposalMethod;
	prototype.governanceEligibleVoters = governanceEligibleVotersMethod;
	prototype.activeGovernanceDelegationSnapshots = activeGovernanceDelegationSnapshotsMethod;
	prototype.snapshotGovernanceElectorate = snapshotGovernanceElectorateMethod;
	prototype.startGovernanceProposalVoting = startGovernanceProposalVotingMethod;
	prototype.latestGovernanceElectorateSnapshot = latestGovernanceElectorateSnapshotMethod;
	prototype.listGovernanceProposalVotes = listGovernanceProposalVotesMethod;
	prototype.effectiveGovernanceVotes = effectiveGovernanceVotesMethod;
	prototype.voteGovernanceProposal = voteGovernanceProposalMethod;
	prototype.evaluateGovernanceProposal = evaluateGovernanceProposalMethod;
	prototype.adminDecideGovernanceProposal = adminDecideGovernanceProposalMethod;
	prototype.withdrawGovernanceProposal = withdrawGovernanceProposalMethod;
	prototype.supersedeGovernanceProposal = supersedeGovernanceProposalMethod;
	prototype.createGovernanceDecisionFromProposal = createGovernanceDecisionFromProposalMethod;
	prototype.getGovernanceDecision = getGovernanceDecisionMethod;
	prototype.listGovernanceDecisions = listGovernanceDecisionsMethod;
	prototype.listGovernanceEvents = listGovernanceEventsMethod;
	prototype.createGovernanceDelegation = createGovernanceDelegationMethod;
	prototype.listGovernanceDelegations = listGovernanceDelegationsMethod;
	prototype.revokeGovernanceDelegation = revokeGovernanceDelegationMethod;
	prototype.createApprovalRequest = createApprovalRequestMethod;
	prototype.getApprovalRequest = getApprovalRequestMethod;
	prototype.listApprovalRequestsForProject = listApprovalRequestsForProjectMethod;
	prototype.listApprovalRequestsForTeam = listApprovalRequestsForTeamMethod;
	prototype.decideApprovalRequest = decideApprovalRequestMethod;
	prototype.ensureCommonsTeam = ensureCommonsTeamMethod;
	prototype.recordCommonsGovernanceEvent = recordCommonsGovernanceEventMethod;
	prototype.getCommonsParticipantByUserId = getCommonsParticipantByUserIdMethod;
	prototype.getCommonsParticipant = getCommonsParticipantMethod;
	prototype.ensureCommonsParticipantForPrincipal = ensureCommonsParticipantForPrincipalMethod;
	prototype.computeCommonsWeights = computeCommonsWeightsMethod;
	prototype.createCommonsWeightSnapshot = createCommonsWeightSnapshotMethod;
	prototype.listCommonsParticipants = listCommonsParticipantsMethod;
	prototype.createCommonsQuestion = createCommonsQuestionMethod;
	prototype.getCommonsQuestion = getCommonsQuestionMethod;
	prototype.listCommonsQuestions = listCommonsQuestionsMethod;
	prototype.answerCommonsQuestion = answerCommonsQuestionMethod;
	prototype.createCommonsProposal = createCommonsProposalMethod;
	prototype.getCommonsProposal = getCommonsProposalMethod;
	prototype.listCommonsProposals = listCommonsProposalsMethod;
	prototype.transitionCommonsProposal = transitionCommonsProposalMethod;
	prototype.submitCommonsProposal = submitCommonsProposalMethod;
	prototype.backCommonsProposal = backCommonsProposalMethod;
	prototype.voteCommonsProposal = voteCommonsProposalMethod;
	prototype.recalculateCommonsProposalVoteTotals = recalculateCommonsProposalVoteTotalsMethod;
	prototype.stewardDecisionForCommonsProposal = stewardDecisionForCommonsProposalMethod;
	prototype.listCommonsProposalBackings = listCommonsProposalBackingsMethod;
	prototype.listCommonsProposalVotes = listCommonsProposalVotesMethod;
	prototype.createCommonsDelegation = createCommonsDelegationMethod;
	prototype.listCommonsDelegations = listCommonsDelegationsMethod;
	prototype.revokeCommonsDelegation = revokeCommonsDelegationMethod;
	prototype.listCommonsDecisions = listCommonsDecisionsMethod;
	prototype.listCommonsGovernanceEvents = listCommonsGovernanceEventsMethod;
	prototype.commonsSummary = commonsSummaryMethod;
}
