import type { ControlPlaneStore } from '../../persistence/store.ts';
import { activeGovernanceDelegationSnapshotsMethod } from '../governance/policy/contracts/active-governance-delegation-snapshots.ts';
import { adminDecideGovernanceProposalMethod } from '../governance/policy/contracts/admin-decide-governance-proposal.ts';
import { ensureDefaultTeamGovernancePolicyMethod } from '../governance/policy/contracts/ensure-default-team-governance-policy.ts';
import { evaluateGovernanceProposalMethod } from '../governance/policy/contracts/evaluate-governance-proposal.ts';
import { governanceEligibleVotersMethod } from '../governance/policy/contracts/governance-eligible-voters.ts';
import { governanceProposalReadinessMethod } from '../governance/policy/contracts/governance-proposal-readiness.ts';
import { snapshotGovernanceElectorateMethod } from '../governance/policy/contracts/snapshot-governance-electorate.ts';
import { createGovernanceDecisionFromProposalMethod } from '../governance/policy/creation/create-governance-decision-from-proposal.ts';
import { createGovernanceProposalMethod } from '../governance/policy/creation/create-governance-proposal.ts';
import { startGovernanceProposalVotingMethod } from '../governance/policy/creation/start-governance-proposal-voting.ts';
import { openGovernanceProposalMethod } from '../governance/policy/lifecycle/open-governance-proposal.ts';
import { voteGovernanceProposalMethod } from '../governance/policy/lifecycle/vote-governance-proposal.ts';
import { getGovernanceDecisionMethod } from '../governance/policy/queries/decisions/get-governance-decision.ts';
import { listGovernanceDecisionsMethod } from '../governance/policy/queries/decisions/list-governance-decisions.ts';
import { listGovernanceEventsMethod } from '../governance/policy/queries/events/list-governance-events.ts';
import { getTeamGovernancePolicyMethod } from '../governance/policy/queries/policy/get-team-governance-policy.ts';
import { latestGovernanceElectorateSnapshotMethod } from '../governance/policy/queries/policy/latest-governance-electorate-snapshot.ts';
import { resolveGovernancePolicyMethod } from '../governance/policy/queries/policy/resolve-governance-policy.ts';
import { effectiveGovernanceVotesMethod } from '../governance/policy/queries/proposals/effective-governance-votes.ts';
import { getGovernanceProposalMethod } from '../governance/policy/queries/proposals/get-governance-proposal.ts';
import { listGovernanceProposalVotesMethod } from '../governance/policy/queries/proposals/list-governance-proposal-votes.ts';
import { listGovernanceProposalsMethod } from '../governance/policy/queries/proposals/list-governance-proposals.ts';
import { withdrawGovernanceProposalMethod } from '../governance/policy/retirement/withdraw-governance-proposal.ts';
import { recordGovernanceEventMethod } from '../governance/policy/updates/record-governance-event.ts';
import { supersedeGovernanceProposalMethod } from '../governance/policy/updates/supersede-governance-proposal.ts';
import { transitionGovernanceProposalMethod } from '../governance/policy/updates/transition-governance-proposal.ts';
import { updateGovernanceProposalDraftMethod } from '../governance/policy/updates/update-governance-proposal-draft.ts';
import { getProjectGovernancePolicyMethod } from '../projects/queries/governance/get-project-governance-policy.ts';
import { listApprovalRequestsForProjectMethod } from '../projects/queries/governance/list-approval-requests-for-project.ts';
import { listApprovalRequestsForTeamMethod } from '../teams/queries/identity/list-approval-requests-for-team.ts';
import { createApprovalRequestMethod } from '../support/creation/create-approval-request.ts';
import { decideApprovalRequestMethod } from '../support/lifecycle/decide-approval-request.ts';
import { getApprovalRequestMethod } from '../support/queries/get-approval-request.ts';

export function installGovernanceStoreMethods(prototype: ControlPlaneStore) {
	prototype.recordGovernanceEvent = recordGovernanceEventMethod;
	prototype.getTeamGovernancePolicy = getTeamGovernancePolicyMethod;
	prototype.ensureDefaultTeamGovernancePolicy = ensureDefaultTeamGovernancePolicyMethod;
	prototype.getProjectGovernancePolicy = getProjectGovernancePolicyMethod;
	prototype.resolveGovernancePolicy = resolveGovernancePolicyMethod;
	prototype.createGovernanceProposal = createGovernanceProposalMethod;
	prototype.governanceProposalReadiness = governanceProposalReadinessMethod;
	prototype.getGovernanceProposal = getGovernanceProposalMethod;
	prototype.listGovernanceProposals = listGovernanceProposalsMethod;
	prototype.updateGovernanceProposalDraft = updateGovernanceProposalDraftMethod;
	prototype.openGovernanceProposal = openGovernanceProposalMethod;
	prototype.transitionGovernanceProposal = transitionGovernanceProposalMethod;
	prototype.governanceEligibleVoters = governanceEligibleVotersMethod;
	prototype.activeGovernanceDelegationSnapshots = activeGovernanceDelegationSnapshotsMethod;
	prototype.snapshotGovernanceElectorate = snapshotGovernanceElectorateMethod;
	prototype.startGovernanceProposalVoting = startGovernanceProposalVotingMethod;
	prototype.latestGovernanceElectorateSnapshot = latestGovernanceElectorateSnapshotMethod;
	prototype.listGovernanceProposalVotes = listGovernanceProposalVotesMethod;
	prototype.effectiveGovernanceVotes = effectiveGovernanceVotesMethod;
	prototype.voteGovernanceProposal = voteGovernanceProposalMethod;
	prototype.evaluateGovernanceProposal = evaluateGovernanceProposalMethod;
	prototype.adminDecideGovernanceProposal = adminDecideGovernanceProposalMethod;
	prototype.withdrawGovernanceProposal = withdrawGovernanceProposalMethod;
	prototype.supersedeGovernanceProposal = supersedeGovernanceProposalMethod;
	prototype.createGovernanceDecisionFromProposal = createGovernanceDecisionFromProposalMethod;
	prototype.getGovernanceDecision = getGovernanceDecisionMethod;
	prototype.listGovernanceDecisions = listGovernanceDecisionsMethod;
	prototype.listGovernanceEvents = listGovernanceEventsMethod;
	prototype.createApprovalRequest = createApprovalRequestMethod;
	prototype.getApprovalRequest = getApprovalRequestMethod;
	prototype.listApprovalRequestsForProject = listApprovalRequestsForProjectMethod;
	prototype.listApprovalRequestsForTeam = listApprovalRequestsForTeamMethod;
	prototype.decideApprovalRequest = decideApprovalRequestMethod;
}
