import type { MarketControlPlaneStore } from '../../persistence/store.ts';
import { appendJobEventMethod } from '../operations/contracts/append-job-event.ts';
import { appendPlatformOperationEventMethod } from '../operations/contracts/append-platform-operation-event.ts';
import { assertPlatformOperationRunnerUpdateMethod } from '../operations/contracts/assert-platform-operation-runner-update.ts';
import { checkpointPlatformOperationMethod } from '../operations/contracts/checkpoint-platform-operation.ts';
import { createJobMethod } from '../operations/creation/create-job.ts';
import { createPlatformOperationMethod } from '../operations/creation/create-platform-operation.ts';
import { upsertMarketOperationRunnerMethod } from '../operations/creation/upsert-market-operation-runner.ts';
import { claimPlatformOperationMethod } from '../operations/lifecycle/claims/claim-platform-operation.ts';
import { renewPlatformOperationLeaseMethod } from '../operations/lifecycle/claims/renew-platform-operation-lease.ts';
import { completeJobMethod } from '../operations/lifecycle/jobs/complete-job.ts';
import { failJobMethod } from '../operations/lifecycle/jobs/fail-job.ts';
import { pullJobsForRunnerMethod } from '../operations/lifecycle/jobs/pull-jobs-for-runner.ts';
import { retryJobMethod } from '../operations/lifecycle/jobs/retry-job.ts';
import { completePlatformOperationMethod } from '../operations/lifecycle/platform-operations/complete-platform-operation.ts';
import { failPlatformOperationMethod } from '../operations/lifecycle/platform-operations/fail-platform-operation.ts';
import { retryPlatformOperationMethod } from '../operations/lifecycle/platform-operations/retry-platform-operation.ts';
import { findJobByIdMethod } from '../operations/queries/jobs/find-job-by-id.ts';
import { listJobEventsMethod } from '../operations/queries/jobs/list-job-events.ts';
import { findPlatformOperationByIdMethod } from '../operations/queries/platform-operations/find-platform-operation-by-id.ts';
import { listPlatformOperationEventsMethod } from '../operations/queries/platform-operations/list-platform-operation-events.ts';
import { listPlatformOperationsMethod } from '../operations/queries/platform-operations/list-platform-operations.ts';
import { findMarketOperationRunnerByIdMethod } from '../operations/queries/runners/find-market-operation-runner-by-id.ts';
import { listMarketOperationRunnersMethod } from '../operations/queries/runners/list-market-operation-runners.ts';
import { cancelJobMethod } from '../operations/retirement/cancel-job.ts';
import { cancelPlatformOperationMethod } from '../operations/retirement/cancel-platform-operation.ts';
import { recordJobProgressMethod } from '../operations/updates/record-job-progress.ts';

export function installOperationsStoreMethods(prototype: MarketControlPlaneStore) {
	prototype.appendPlatformOperationEvent = appendPlatformOperationEventMethod;
	prototype.listPlatformOperationEvents = listPlatformOperationEventsMethod;
	prototype.findPlatformOperationById = findPlatformOperationByIdMethod;
	prototype.listPlatformOperations = listPlatformOperationsMethod;
	prototype.createPlatformOperation = createPlatformOperationMethod;
	prototype.cancelPlatformOperation = cancelPlatformOperationMethod;
	prototype.retryPlatformOperation = retryPlatformOperationMethod;
	prototype.assertPlatformOperationRunnerUpdate = assertPlatformOperationRunnerUpdateMethod;
	prototype.upsertMarketOperationRunner = upsertMarketOperationRunnerMethod;
	prototype.findMarketOperationRunnerById = findMarketOperationRunnerByIdMethod;
	prototype.listMarketOperationRunners = listMarketOperationRunnersMethod;
	prototype.claimPlatformOperation = claimPlatformOperationMethod;
	prototype.renewPlatformOperationLease = renewPlatformOperationLeaseMethod;
	prototype.checkpointPlatformOperation = checkpointPlatformOperationMethod;
	prototype.completePlatformOperation = completePlatformOperationMethod;
	prototype.failPlatformOperation = failPlatformOperationMethod;
	prototype.appendJobEvent = appendJobEventMethod;
	prototype.listJobEvents = listJobEventsMethod;
	prototype.findJobById = findJobByIdMethod;
	prototype.createJob = createJobMethod;
	prototype.cancelJob = cancelJobMethod;
	prototype.retryJob = retryJobMethod;
	prototype.pullJobsForRunner = pullJobsForRunnerMethod;
	prototype.recordJobProgress = recordJobProgressMethod;
	prototype.completeJob = completeJobMethod;
	prototype.failJob = failJobMethod;
}
