import type { MarketControlPlaneStore } from '../../store.ts';
import { getHubLaunchByJobIdMethod } from '../get-hub-launch-by-job-id.ts';
import { issueRunnerTokenMethod } from '../issue-runner-token.ts';
import { authenticateRunnerMethod } from '../authenticate-runner.ts';
import { upsertWorkflowOperationRecordMethod } from '../upsert-workflow-operation-record.ts';
import { listWorkflowOperationRecordsMethod } from '../list-workflow-operation-records.ts';
import { getWorkflowOperationRecordMethod } from '../get-workflow-operation-record.ts';
import { updateWorkflowOperationRecordStatusMethod } from '../update-workflow-operation-record-status.ts';
import { appendPlatformOperationEventMethod } from '../append-platform-operation-event.ts';
import { listPlatformOperationEventsMethod } from '../list-platform-operation-events.ts';
import { findPlatformOperationByIdMethod } from '../find-platform-operation-by-id.ts';
import { listPlatformOperationsMethod } from '../list-platform-operations.ts';
import { createPlatformOperationMethod } from '../create-platform-operation.ts';
import { cancelPlatformOperationMethod } from '../cancel-platform-operation.ts';
import { retryPlatformOperationMethod } from '../retry-platform-operation.ts';
import { assertPlatformOperationRunnerUpdateMethod } from '../assert-platform-operation-runner-update.ts';
import { upsertMarketOperationRunnerMethod } from '../upsert-market-operation-runner.ts';
import { findMarketOperationRunnerByIdMethod } from '../find-market-operation-runner-by-id.ts';
import { listMarketOperationRunnersMethod } from '../list-market-operation-runners.ts';
import { upsertPlatformRepositoryClaimMethod } from '../upsert-platform-repository-claim.ts';
import { renewPlatformRepositoryClaimsForRunnerMethod } from '../renew-platform-repository-claims-for-runner.ts';
import { releasePlatformRepositoryClaimsForRunnerMethod } from '../release-platform-repository-claims-for-runner.ts';
import { claimPlatformOperationMethod } from '../claim-platform-operation.ts';
import { renewPlatformOperationLeaseMethod } from '../renew-platform-operation-lease.ts';
import { checkpointPlatformOperationMethod } from '../checkpoint-platform-operation.ts';
import { completePlatformOperationMethod } from '../complete-platform-operation.ts';
import { failPlatformOperationMethod } from '../fail-platform-operation.ts';
import { appendJobEventMethod } from '../append-job-event.ts';
import { listJobEventsMethod } from '../list-job-events.ts';
import { findJobByIdMethod } from '../find-job-by-id.ts';
import { createJobMethod } from '../create-job.ts';
import { cancelJobMethod } from '../cancel-job.ts';
import { retryJobMethod } from '../retry-job.ts';
import { pullJobsForRunnerMethod } from '../pull-jobs-for-runner.ts';
import { pullManagedLaunchJobsMethod } from '../pull-managed-launch-jobs.ts';
import { recordJobProgressMethod } from '../record-job-progress.ts';
import { completeJobMethod } from '../complete-job.ts';
import { failJobMethod } from '../fail-job.ts';

export function installOperationsStoreMethods(prototype: MarketControlPlaneStore) {
	prototype.getHubLaunchByJobId = getHubLaunchByJobIdMethod;
	prototype.issueRunnerToken = issueRunnerTokenMethod;
	prototype.authenticateRunner = authenticateRunnerMethod;
	prototype.upsertWorkflowOperationRecord = upsertWorkflowOperationRecordMethod;
	prototype.listWorkflowOperationRecords = listWorkflowOperationRecordsMethod;
	prototype.getWorkflowOperationRecord = getWorkflowOperationRecordMethod;
	prototype.updateWorkflowOperationRecordStatus = updateWorkflowOperationRecordStatusMethod;
	prototype.appendPlatformOperationEvent = appendPlatformOperationEventMethod;
	prototype.listPlatformOperationEvents = listPlatformOperationEventsMethod;
	prototype.findPlatformOperationById = findPlatformOperationByIdMethod;
	prototype.listPlatformOperations = listPlatformOperationsMethod;
	prototype.createPlatformOperation = createPlatformOperationMethod;
	prototype.cancelPlatformOperation = cancelPlatformOperationMethod;
	prototype.retryPlatformOperation = retryPlatformOperationMethod;
	prototype.assertPlatformOperationRunnerUpdate = assertPlatformOperationRunnerUpdateMethod;
	prototype.upsertMarketOperationRunner = upsertMarketOperationRunnerMethod;
	prototype.findMarketOperationRunnerById = findMarketOperationRunnerByIdMethod;
	prototype.listMarketOperationRunners = listMarketOperationRunnersMethod;
	prototype.upsertPlatformRepositoryClaim = upsertPlatformRepositoryClaimMethod;
	prototype.renewPlatformRepositoryClaimsForRunner = renewPlatformRepositoryClaimsForRunnerMethod;
	prototype.releasePlatformRepositoryClaimsForRunner = releasePlatformRepositoryClaimsForRunnerMethod;
	prototype.claimPlatformOperation = claimPlatformOperationMethod;
	prototype.renewPlatformOperationLease = renewPlatformOperationLeaseMethod;
	prototype.checkpointPlatformOperation = checkpointPlatformOperationMethod;
	prototype.completePlatformOperation = completePlatformOperationMethod;
	prototype.failPlatformOperation = failPlatformOperationMethod;
	prototype.appendJobEvent = appendJobEventMethod;
	prototype.listJobEvents = listJobEventsMethod;
	prototype.findJobById = findJobByIdMethod;
	prototype.createJob = createJobMethod;
	prototype.cancelJob = cancelJobMethod;
	prototype.retryJob = retryJobMethod;
	prototype.pullJobsForRunner = pullJobsForRunnerMethod;
	prototype.pullManagedLaunchJobs = pullManagedLaunchJobsMethod;
	prototype.recordJobProgress = recordJobProgressMethod;
	prototype.completeJob = completeJobMethod;
	prototype.failJob = failJobMethod;
}
