import type { MarketControlPlaneStore } from '../../store.ts';
import { getProjectAccessSummaryMethod } from '../get-project-access-summary.ts';
import { requestProjectRuntimeMethod } from '../request-project-runtime.ts';
import { listProjectsUsingRepositoryHostMethod } from '../list-projects-using-repository-host.ts';
import { listProjectsUsingTeamWebHostMethod } from '../list-projects-using-team-web-host.ts';
import { getProjectRepositoryTopologyMethod } from '../get-project-repository-topology.ts';
import { upsertProjectRepositoryTopologyMethod } from '../upsert-project-repository-topology.ts';
import { getProjectArchitectureMethod } from '../get-project-architecture.ts';
import { upsertProjectArchitectureMethod } from '../upsert-project-architecture.ts';
import { importProjectRepositoryPlanMethod } from '../import-project-repository-plan.ts';
import { projectArchitectureContentBindingsMethod } from '../project-architecture-content-bindings.ts';
import { listProjectsForPrincipalMethod } from '../list-projects-for-principal.ts';
import { listTeamProjectsMethod } from '../list-team-projects.ts';
import { createProjectMethod } from '../create-project.ts';
import { updateProjectMethod } from '../update-project.ts';
import { getProjectMethod } from '../get-project.ts';
import { getProjectByTeamAndSlugMethod } from '../get-project-by-team-and-slug.ts';
import { createProjectUpdatePlanMethod } from '../create-project-update-plan.ts';
import { listProjectUpdatePlansMethod } from '../list-project-update-plans.ts';
import { getProjectConnectionMethod } from '../get-project-connection.ts';
import { getProjectHostingMethod } from '../get-project-hosting.ts';
import { upsertProjectHostingMethod } from '../upsert-project-hosting.ts';
import { listProjectEnvironmentsMethod } from '../list-project-environments.ts';
import { upsertProjectEnvironmentMethod } from '../upsert-project-environment.ts';
import { listProjectInfrastructureResourcesMethod } from '../list-project-infrastructure-resources.ts';
import { upsertProjectInfrastructureResourceMethod } from '../upsert-project-infrastructure-resource.ts';
import { createProjectDeploymentMethod } from '../create-project-deployment.ts';
import { findProjectDeploymentByIdMethod } from '../find-project-deployment-by-id.ts';
import { findProjectDeploymentByOperationIdMethod } from '../find-project-deployment-by-operation-id.ts';
import { findProjectDeploymentByIdempotencyKeyMethod } from '../find-project-deployment-by-idempotency-key.ts';
import { listProjectDeploymentsMethod } from '../list-project-deployments.ts';
import { updateProjectDeploymentMethod } from '../update-project-deployment.ts';
import { findLatestProjectDeploymentMethod } from '../find-latest-project-deployment.ts';
import { listActiveProjectDeploymentsMethod } from '../list-active-project-deployments.ts';
import { createProjectDeploymentRetryMethod } from '../create-project-deployment-retry.ts';
import { markProjectDeploymentCancellationRequestedMethod } from '../mark-project-deployment-cancellation-requested.ts';
import { appendProjectDeploymentEventMethod } from '../append-project-deployment-event.ts';
import { listProjectDeploymentEventsMethod } from '../list-project-deployment-events.ts';
import { upsertProjectConnectionMethod } from '../upsert-project-connection.ts';
import { replaceProjectCapabilitiesMethod } from '../replace-project-capabilities.ts';
import { listProjectCapabilitiesMethod } from '../list-project-capabilities.ts';
import { getProjectDetailsMethod } from '../get-project-details.ts';
import { listRecentJobsForProjectMethod } from '../list-recent-jobs-for-project.ts';
import { listProjectActivityMethod } from '../list-project-activity.ts';
import { getProjectSummaryMethod } from '../get-project-summary.ts';
import { getProjectDirectSummaryMethod } from '../get-project-direct-summary.ts';
import { getProjectWorkstreamsSummaryMethod } from '../get-project-workstreams-summary.ts';
import { getProjectReleasesSummaryMethod } from '../get-project-releases-summary.ts';
import { getProjectShareSummaryMethod } from '../get-project-share-summary.ts';
import { getProjectSummarySnapshotMethod } from '../get-project-summary-snapshot.ts';
import { upsertProjectSummarySnapshotMethod } from '../upsert-project-summary-snapshot.ts';
import { recordProjectDeploymentAuditMethod } from '../record-project-deployment-audit.ts';

export function installProjectsStoreMethods(prototype: MarketControlPlaneStore) {
	prototype.getProjectAccessSummary = getProjectAccessSummaryMethod;
	prototype.requestProjectRuntime = requestProjectRuntimeMethod;
	prototype.listProjectsUsingRepositoryHost = listProjectsUsingRepositoryHostMethod;
	prototype.listProjectsUsingTeamWebHost = listProjectsUsingTeamWebHostMethod;
	prototype.getProjectRepositoryTopology = getProjectRepositoryTopologyMethod;
	prototype.upsertProjectRepositoryTopology = upsertProjectRepositoryTopologyMethod;
	prototype.getProjectArchitecture = getProjectArchitectureMethod;
	prototype.upsertProjectArchitecture = upsertProjectArchitectureMethod;
	prototype.importProjectRepositoryPlan = importProjectRepositoryPlanMethod;
	prototype.projectArchitectureContentBindings = projectArchitectureContentBindingsMethod;
	prototype.listProjectsForPrincipal = listProjectsForPrincipalMethod;
	prototype.listTeamProjects = listTeamProjectsMethod;
	prototype.createProject = createProjectMethod;
	prototype.updateProject = updateProjectMethod;
	prototype.getProject = getProjectMethod;
	prototype.getProjectByTeamAndSlug = getProjectByTeamAndSlugMethod;
	prototype.createProjectUpdatePlan = createProjectUpdatePlanMethod;
	prototype.listProjectUpdatePlans = listProjectUpdatePlansMethod;
	prototype.getProjectConnection = getProjectConnectionMethod;
	prototype.getProjectHosting = getProjectHostingMethod;
	prototype.upsertProjectHosting = upsertProjectHostingMethod;
	prototype.listProjectEnvironments = listProjectEnvironmentsMethod;
	prototype.upsertProjectEnvironment = upsertProjectEnvironmentMethod;
	prototype.listProjectInfrastructureResources = listProjectInfrastructureResourcesMethod;
	prototype.upsertProjectInfrastructureResource = upsertProjectInfrastructureResourceMethod;
	prototype.createProjectDeployment = createProjectDeploymentMethod;
	prototype.findProjectDeploymentById = findProjectDeploymentByIdMethod;
	prototype.findProjectDeploymentByOperationId = findProjectDeploymentByOperationIdMethod;
	prototype.findProjectDeploymentByIdempotencyKey = findProjectDeploymentByIdempotencyKeyMethod;
	prototype.listProjectDeployments = listProjectDeploymentsMethod;
	prototype.updateProjectDeployment = updateProjectDeploymentMethod;
	prototype.findLatestProjectDeployment = findLatestProjectDeploymentMethod;
	prototype.listActiveProjectDeployments = listActiveProjectDeploymentsMethod;
	prototype.createProjectDeploymentRetry = createProjectDeploymentRetryMethod;
	prototype.markProjectDeploymentCancellationRequested = markProjectDeploymentCancellationRequestedMethod;
	prototype.appendProjectDeploymentEvent = appendProjectDeploymentEventMethod;
	prototype.listProjectDeploymentEvents = listProjectDeploymentEventsMethod;
	prototype.upsertProjectConnection = upsertProjectConnectionMethod;
	prototype.replaceProjectCapabilities = replaceProjectCapabilitiesMethod;
	prototype.listProjectCapabilities = listProjectCapabilitiesMethod;
	prototype.getProjectDetails = getProjectDetailsMethod;
	prototype.listRecentJobsForProject = listRecentJobsForProjectMethod;
	prototype.listProjectActivity = listProjectActivityMethod;
	prototype.getProjectSummary = getProjectSummaryMethod;
	prototype.getProjectDirectSummary = getProjectDirectSummaryMethod;
	prototype.getProjectWorkstreamsSummary = getProjectWorkstreamsSummaryMethod;
	prototype.getProjectReleasesSummary = getProjectReleasesSummaryMethod;
	prototype.getProjectShareSummary = getProjectShareSummaryMethod;
	prototype.getProjectSummarySnapshot = getProjectSummarySnapshotMethod;
	prototype.upsertProjectSummarySnapshot = upsertProjectSummarySnapshotMethod;
	prototype.recordProjectDeploymentAudit = recordProjectDeploymentAuditMethod;
}
