import type { MarketControlPlaneStore } from '../../persistence/store.ts';
import { seedTeamRolesMethod } from '../teams/contracts/seed-team-roles.ts';
import { roleIdForKeyMethod } from '../teams/contracts/role-id-for-key.ts';
import { bindRoleToMembershipMethod } from '../teams/updates/bind-role-to-membership.ts';
import { listRoleKeysForMembershipMethod } from '../teams/queries/members/list-role-keys-for-membership.ts';
import { resolvePrincipalTeamContextMethod } from '../teams/queries/access/resolve-principal-team-context.ts';
import { getTeamAccessSummaryMethod } from '../teams/queries/access/get-team-access-summary.ts';
import { teamIdsForPrincipalMethod } from '../teams/contracts/team-ids-for-principal.ts';
import { principalCanAccessTeamMethod } from '../teams/contracts/principal-can-access-team.ts';
import { principalCanManageTeamMethod } from '../teams/contracts/principal-can-manage-team.ts';
import { authenticateTeamApiKeyMethod } from '../teams/contracts/authenticate-team-api-key.ts';
import { createTeamMethod } from '../teams/creation/create-team.ts';
import { getTeamMethod } from '../teams/queries/identity/get-team.ts';
import { getTeamBySlugMethod } from '../teams/queries/identity/get-team-by-slug.ts';
import { getTeamByNameMethod } from '../teams/queries/identity/get-team-by-name.ts';
import { isTeamNameAvailableMethod } from '../teams/queries/identity/is-team-name-available.ts';
import { teamPublicNameExistsMethod } from '../teams/contracts/team-public-name-exists.ts';
import { ensurePersonalResearchTeamForUserMethod } from '../teams/contracts/ensure-personal-research-team-for-user.ts';
import { updateTeamSettingsMethod } from '../teams/updates/update-team-settings.ts';
import { listTeamsForPrincipalMethod } from '../teams/queries/access/list-teams-for-principal.ts';
import { listTeamMembersMethod } from '../teams/queries/members/list-team-members.ts';
import { listTeamWebHostsMethod } from '../teams/queries/hosting/list-team-web-hosts.ts';
import { getTeamWebHostMethod } from '../teams/queries/hosting/get-team-web-host.ts';
import { createTeamWebHostMethod } from '../teams/creation/create-team-web-host.ts';
import { updateTeamWebHostMethod } from '../teams/updates/update-team-web-host.ts';
import { consumeTeamProviderCredentialSessionMethod } from '../capacity/providers/contracts/consume-team-provider-credential-session.ts';
import { deleteTeamWebHostMethod } from '../teams/retirement/delete-team-web-host.ts';
import { listTeamInvitesMethod } from '../teams/queries/invites/list-team-invites.ts';
import { membershipOwnerCountMethod } from '../teams/contracts/membership-owner-count.ts';
import { upsertTeamMemberMethod } from '../teams/creation/upsert-team-member.ts';
import { replaceMembershipRoleMethod } from '../teams/updates/replace-membership-role.ts';
import { updateTeamMemberRoleMethod } from '../teams/updates/update-team-member-role.ts';
import { removeTeamMemberMethod } from '../teams/retirement/remove-team-member.ts';
import { createTeamInviteMethod } from '../teams/creation/create-team-invite.ts';
import { getTeamInviteMethod } from '../teams/queries/invites/get-team-invite.ts';
import { getPendingTeamInviteByTokenMethod } from '../teams/queries/invites/get-pending-team-invite-by-token.ts';
import { getTeamInviteByTokenMethod } from '../teams/queries/invites/get-team-invite-by-token.ts';
import { revokeTeamInviteMethod } from '../teams/retirement/revoke-team-invite.ts';
import { acceptTeamInviteMethod } from '../teams/lifecycle/accept-team-invite.ts';
import { createTeamApiKeyMethod } from '../teams/creation/create-team-api-key.ts';
import { getTeamStorageLocatorMethod } from '../teams/queries/hosting/get-team-storage-locator.ts';
import { upsertTeamStorageLocatorMethod } from '../teams/creation/upsert-team-storage-locator.ts';
import { loadTeamProfileByNameMethod } from '../teams/queries/identity/load-team-profile-by-name.ts';
import { evaluateTeamDeletionBlockersMethod } from '../teams/contracts/evaluate-team-deletion-blockers.ts';
import { prepareTeamDeletionMethod } from '../teams/creation/prepare-team-deletion.ts';
import { listPersistedTeamInboxItemsMethod } from '../teams/queries/inbox/list-persisted-team-inbox-items.ts';
import { upsertTeamInboxItemMethod } from '../teams/creation/upsert-team-inbox-item.ts';
import { deleteTeamInboxItemMethod } from '../teams/retirement/delete-team-inbox-item.ts';
import { deleteTeamInboxItemsByItemKeyMethod } from '../teams/retirement/delete-team-inbox-items-by-item-key.ts';
import { listTeamInboxItemsMethod } from '../teams/queries/inbox/list-team-inbox-items.ts';
import { getTeamHomeSummaryMethod } from '../teams/queries/identity/get-team-home-summary.ts';

export function installTeamsStoreMethods(prototype: MarketControlPlaneStore) {
	prototype.seedTeamRoles = seedTeamRolesMethod;
	prototype.roleIdForKey = roleIdForKeyMethod;
	prototype.bindRoleToMembership = bindRoleToMembershipMethod;
	prototype.listRoleKeysForMembership = listRoleKeysForMembershipMethod;
	prototype.resolvePrincipalTeamContext = resolvePrincipalTeamContextMethod;
	prototype.getTeamAccessSummary = getTeamAccessSummaryMethod;
	prototype.teamIdsForPrincipal = teamIdsForPrincipalMethod;
	prototype.principalCanAccessTeam = principalCanAccessTeamMethod;
	prototype.principalCanManageTeam = principalCanManageTeamMethod;
	prototype.authenticateTeamApiKey = authenticateTeamApiKeyMethod;
	prototype.createTeam = createTeamMethod;
	prototype.getTeam = getTeamMethod;
	prototype.getTeamBySlug = getTeamBySlugMethod;
	prototype.getTeamByName = getTeamByNameMethod;
	prototype.isTeamNameAvailable = isTeamNameAvailableMethod;
	prototype.teamPublicNameExists = teamPublicNameExistsMethod;
	prototype.ensurePersonalResearchTeamForUser = ensurePersonalResearchTeamForUserMethod;
	prototype.updateTeamSettings = updateTeamSettingsMethod;
	prototype.listTeamsForPrincipal = listTeamsForPrincipalMethod;
	prototype.listTeamMembers = listTeamMembersMethod;
	prototype.listTeamWebHosts = listTeamWebHostsMethod;
	prototype.getTeamWebHost = getTeamWebHostMethod;
	prototype.createTeamWebHost = createTeamWebHostMethod;
	prototype.updateTeamWebHost = updateTeamWebHostMethod;
	prototype.consumeTeamProviderCredentialSession = consumeTeamProviderCredentialSessionMethod;
	prototype.deleteTeamWebHost = deleteTeamWebHostMethod;
	prototype.listTeamInvites = listTeamInvitesMethod;
	prototype.membershipOwnerCount = membershipOwnerCountMethod;
	prototype.upsertTeamMember = upsertTeamMemberMethod;
	prototype.replaceMembershipRole = replaceMembershipRoleMethod;
	prototype.updateTeamMemberRole = updateTeamMemberRoleMethod;
	prototype.removeTeamMember = removeTeamMemberMethod;
	prototype.createTeamInvite = createTeamInviteMethod;
	prototype.getTeamInvite = getTeamInviteMethod;
	prototype.getPendingTeamInviteByToken = getPendingTeamInviteByTokenMethod;
	prototype.getTeamInviteByToken = getTeamInviteByTokenMethod;
	prototype.revokeTeamInvite = revokeTeamInviteMethod;
	prototype.acceptTeamInvite = acceptTeamInviteMethod;
	prototype.createTeamApiKey = createTeamApiKeyMethod;
	prototype.getTeamStorageLocator = getTeamStorageLocatorMethod;
	prototype.upsertTeamStorageLocator = upsertTeamStorageLocatorMethod;
	prototype.loadTeamProfileByName = loadTeamProfileByNameMethod;
	prototype.evaluateTeamDeletionBlockers = evaluateTeamDeletionBlockersMethod;
	prototype.prepareTeamDeletion = prepareTeamDeletionMethod;
	prototype.listPersistedTeamInboxItems = listPersistedTeamInboxItemsMethod;
	prototype.upsertTeamInboxItem = upsertTeamInboxItemMethod;
	prototype.deleteTeamInboxItem = deleteTeamInboxItemMethod;
	prototype.deleteTeamInboxItemsByItemKey = deleteTeamInboxItemsByItemKeyMethod;
	prototype.listTeamInboxItems = listTeamInboxItemsMethod;
	prototype.getTeamHomeSummary = getTeamHomeSummaryMethod;
}
