import type { MarketControlPlaneStore } from '../../store.ts';
import { seedTeamRolesMethod } from '../seed-team-roles.ts';
import { roleIdForKeyMethod } from '../role-id-for-key.ts';
import { bindRoleToMembershipMethod } from '../bind-role-to-membership.ts';
import { listRoleKeysForMembershipMethod } from '../list-role-keys-for-membership.ts';
import { resolvePrincipalTeamContextMethod } from '../resolve-principal-team-context.ts';
import { getTeamAccessSummaryMethod } from '../get-team-access-summary.ts';
import { teamIdsForPrincipalMethod } from '../team-ids-for-principal.ts';
import { principalCanAccessTeamMethod } from '../principal-can-access-team.ts';
import { principalCanManageTeamMethod } from '../principal-can-manage-team.ts';
import { authenticateTeamApiKeyMethod } from '../authenticate-team-api-key.ts';
import { createTeamMethod } from '../create-team.ts';
import { getTeamMethod } from '../get-team.ts';
import { getTeamBySlugMethod } from '../get-team-by-slug.ts';
import { getTeamByNameMethod } from '../get-team-by-name.ts';
import { isTeamNameAvailableMethod } from '../is-team-name-available.ts';
import { teamPublicNameExistsMethod } from '../team-public-name-exists.ts';
import { ensurePersonalResearchTeamForUserMethod } from '../ensure-personal-research-team-for-user.ts';
import { updateTeamSettingsMethod } from '../update-team-settings.ts';
import { listTeamsForPrincipalMethod } from '../list-teams-for-principal.ts';
import { listTeamMembersMethod } from '../list-team-members.ts';
import { listTeamWebHostsMethod } from '../list-team-web-hosts.ts';
import { getTeamWebHostMethod } from '../get-team-web-host.ts';
import { createTeamWebHostMethod } from '../create-team-web-host.ts';
import { updateTeamWebHostMethod } from '../update-team-web-host.ts';
import { consumeTeamProviderCredentialSessionMethod } from '../consume-team-provider-credential-session.ts';
import { deleteTeamWebHostMethod } from '../delete-team-web-host.ts';
import { listTeamInvitesMethod } from '../list-team-invites.ts';
import { membershipOwnerCountMethod } from '../membership-owner-count.ts';
import { upsertTeamMemberMethod } from '../upsert-team-member.ts';
import { replaceMembershipRoleMethod } from '../replace-membership-role.ts';
import { updateTeamMemberRoleMethod } from '../update-team-member-role.ts';
import { removeTeamMemberMethod } from '../remove-team-member.ts';
import { createTeamInviteMethod } from '../create-team-invite.ts';
import { getTeamInviteMethod } from '../get-team-invite.ts';
import { getPendingTeamInviteByTokenMethod } from '../get-pending-team-invite-by-token.ts';
import { getTeamInviteByTokenMethod } from '../get-team-invite-by-token.ts';
import { revokeTeamInviteMethod } from '../revoke-team-invite.ts';
import { acceptTeamInviteMethod } from '../accept-team-invite.ts';
import { createTeamApiKeyMethod } from '../create-team-api-key.ts';
import { getTeamStorageLocatorMethod } from '../get-team-storage-locator.ts';
import { upsertTeamStorageLocatorMethod } from '../upsert-team-storage-locator.ts';
import { loadTeamProfileByNameMethod } from '../load-team-profile-by-name.ts';
import { evaluateTeamDeletionBlockersMethod } from '../evaluate-team-deletion-blockers.ts';
import { prepareTeamDeletionMethod } from '../prepare-team-deletion.ts';
import { listPersistedTeamInboxItemsMethod } from '../list-persisted-team-inbox-items.ts';
import { upsertTeamInboxItemMethod } from '../upsert-team-inbox-item.ts';
import { deleteTeamInboxItemMethod } from '../delete-team-inbox-item.ts';
import { deleteTeamInboxItemsByItemKeyMethod } from '../delete-team-inbox-items-by-item-key.ts';
import { listTeamInboxItemsMethod } from '../list-team-inbox-items.ts';
import { getTeamHomeSummaryMethod } from '../get-team-home-summary.ts';

export function installTeamsStoreMethods(prototype: MarketControlPlaneStore) {
	prototype.seedTeamRoles = seedTeamRolesMethod;
	prototype.roleIdForKey = roleIdForKeyMethod;
	prototype.bindRoleToMembership = bindRoleToMembershipMethod;
	prototype.listRoleKeysForMembership = listRoleKeysForMembershipMethod;
	prototype.resolvePrincipalTeamContext = resolvePrincipalTeamContextMethod;
	prototype.getTeamAccessSummary = getTeamAccessSummaryMethod;
	prototype.teamIdsForPrincipal = teamIdsForPrincipalMethod;
	prototype.principalCanAccessTeam = principalCanAccessTeamMethod;
	prototype.principalCanManageTeam = principalCanManageTeamMethod;
	prototype.authenticateTeamApiKey = authenticateTeamApiKeyMethod;
	prototype.createTeam = createTeamMethod;
	prototype.getTeam = getTeamMethod;
	prototype.getTeamBySlug = getTeamBySlugMethod;
	prototype.getTeamByName = getTeamByNameMethod;
	prototype.isTeamNameAvailable = isTeamNameAvailableMethod;
	prototype.teamPublicNameExists = teamPublicNameExistsMethod;
	prototype.ensurePersonalResearchTeamForUser = ensurePersonalResearchTeamForUserMethod;
	prototype.updateTeamSettings = updateTeamSettingsMethod;
	prototype.listTeamsForPrincipal = listTeamsForPrincipalMethod;
	prototype.listTeamMembers = listTeamMembersMethod;
	prototype.listTeamWebHosts = listTeamWebHostsMethod;
	prototype.getTeamWebHost = getTeamWebHostMethod;
	prototype.createTeamWebHost = createTeamWebHostMethod;
	prototype.updateTeamWebHost = updateTeamWebHostMethod;
	prototype.consumeTeamProviderCredentialSession = consumeTeamProviderCredentialSessionMethod;
	prototype.deleteTeamWebHost = deleteTeamWebHostMethod;
	prototype.listTeamInvites = listTeamInvitesMethod;
	prototype.membershipOwnerCount = membershipOwnerCountMethod;
	prototype.upsertTeamMember = upsertTeamMemberMethod;
	prototype.replaceMembershipRole = replaceMembershipRoleMethod;
	prototype.updateTeamMemberRole = updateTeamMemberRoleMethod;
	prototype.removeTeamMember = removeTeamMemberMethod;
	prototype.createTeamInvite = createTeamInviteMethod;
	prototype.getTeamInvite = getTeamInviteMethod;
	prototype.getPendingTeamInviteByToken = getPendingTeamInviteByTokenMethod;
	prototype.getTeamInviteByToken = getTeamInviteByTokenMethod;
	prototype.revokeTeamInvite = revokeTeamInviteMethod;
	prototype.acceptTeamInvite = acceptTeamInviteMethod;
	prototype.createTeamApiKey = createTeamApiKeyMethod;
	prototype.getTeamStorageLocator = getTeamStorageLocatorMethod;
	prototype.upsertTeamStorageLocator = upsertTeamStorageLocatorMethod;
	prototype.loadTeamProfileByName = loadTeamProfileByNameMethod;
	prototype.evaluateTeamDeletionBlockers = evaluateTeamDeletionBlockersMethod;
	prototype.prepareTeamDeletion = prepareTeamDeletionMethod;
	prototype.listPersistedTeamInboxItems = listPersistedTeamInboxItemsMethod;
	prototype.upsertTeamInboxItem = upsertTeamInboxItemMethod;
	prototype.deleteTeamInboxItem = deleteTeamInboxItemMethod;
	prototype.deleteTeamInboxItemsByItemKey = deleteTeamInboxItemsByItemKeyMethod;
	prototype.listTeamInboxItems = listTeamInboxItemsMethod;
	prototype.getTeamHomeSummary = getTeamHomeSummaryMethod;
}
